drivers/SmartThings/zigbee-contact/fingerprints.yml

These devices do not support the temperature measurement capability.

PHX-46 Correct profiles

---

.github/workflows/create-driver-channel.yml

When a new PR is opened that contains a modified driver, a new channel should be created with that driver assigned and an invite link should be posted on the PR

Add github action for automatic channel creation

---

drivers/SmartThings/zwave-window-treatment/fingerprints.yml
drivers/SmartThings/zwave-window-treatment/src/iblinds-window-treatment/init.lua
drivers/SmartThings/zwave-window-treatment/src/iblinds-window-treatment/v3.lua
drivers/SmartThings/zwave-window-treatment/src/preferences.lua

@SmartThingsCommunity/srpol-pe-team @greens

CHAD-8546 - additional fingerprint

---

drivers/SmartThings/zigbee-contact/fingerprints.yml
drivers/SmartThings/zigbee-contact/profiles/smartsense-multi.yml
drivers/SmartThings/zigbee-contact/src/init.lua
drivers/SmartThings/zigbee-contact/src/multi-sensor/multi_utils.lua
drivers/SmartThings/zigbee-contact/src/smartsense-multi/init.lua
drivers/SmartThings/zigbee-contact/src/test/test_smartsense_multi.lua

@greens Please, could You review the code ?
cc: @SmartThingsCommunity/srpol-pe-team

SmartSense Multi

---

drivers/SmartThings/zwave-mouse-trap/profiles/pest-control-battery.yml

[CHAD-8639] Added metadata info to pest-control-battery profile

---

drivers/SmartThings/zwave-siren/profiles/aeon-siren.yml
drivers/SmartThings/zwave-siren/profiles/alarm-battery.yml
drivers/SmartThings/zwave-siren/profiles/alarm-switch.yml
drivers/SmartThings/zwave-siren/profiles/yale-siren-tamper.yml
drivers/SmartThings/zwave-siren/profiles/yale-siren.yml

[CHAD-8243] Added metadata info for some siren profiles

---

drivers/SmartThings/zigbee-motion-sensor/fingerprints.yml
drivers/SmartThings/zigbee-motion-sensor/src/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_thirdreality_sensor.lua
drivers/SmartThings/zigbee-motion-sensor/src/thirdreality/init.lua

@greens 
Please, could You take a look at the code ?
cc: @SmartThingsCommunity/srpol-pe-team

CHAD-8544 - Third Reality 3RMS16BZ

---

drivers/SmartThings/zwave-bulb/profiles/switch-level-colortemp.yml
drivers/SmartThings/zwave-fan/profiles/fan-3speed.yml
drivers/SmartThings/zwave-fan/profiles/fan-4speed.yml

@tpmanley @greens @varzac @dsobierajsk
Please, could You review the code ?
Corresponding values were changed in UI Metadata configuration files too (approved, merged, deployed to ACC and PROD)
cc: @SmartThingsCommunity/srpol-pe-team

CHAD-8647 - changes mnmn values to SmartThingsEdge #2

---

drivers/SmartThings/zigbee-thermostat/profiles/base-thermostat-fanless.yml
drivers/SmartThings/zigbee-thermostat/profiles/base-thermostat-no-operating-state.yml
drivers/SmartThings/zigbee-thermostat/profiles/base-thermostat.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-battery-powerSource.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-battery.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-sinope-th1300.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-sinope-th1400.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-sinope.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-stelpro-profile.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-temperature-temperaturealarm.yml

Moving Temperature Measurement to be the top capability in thermostat profiles so that it is displayed in the devices list

Moving capabilities in thermostat profiles

---

drivers/SmartThings/zigbee-water-leak-sensor/fingerprints.yml
drivers/SmartThings/zigbee-water-leak-sensor/src/init.lua
drivers/SmartThings/zigbee-water-leak-sensor/src/test/test_thirdreality_water_leak_sensor.lua
drivers/SmartThings/zigbee-water-leak-sensor/src/thirdreality/init.lua

Original DTH: https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/orvibo-Moisture-Sensor.src/orvibo-Moisture-Sensor.groovy

[CHAD-8543] Ported additional fingerprints of the 'Orvibo Moisture Sensor' for 'Third Reality 3RWS18BZ'

---

drivers/SmartThings/zwave-sensor/fingerprints.yml
drivers/SmartThings/zwave-sensor/profiles/motion-light.yml
drivers/SmartThings/zwave-sensor/src/test/test_everspring_motion_light_sensor.lua

https://smartthings.atlassian.net/browse/CHAD-8747

[CHAD-8747] Changed device type of Everspring Motion Light

---

drivers/SmartThings/zwave-thermostat/profiles/qubino-flush-thermostat.yml

[CHAD-8742] Added metadata info to qubino-flush-thermostat profile

---

drivers/SmartThings/zigbee-switch/profiles/on-off-level-intensity.yml

Fixed category for DM2500ZB from Light to Switch
Signed-off-by: Keuckdo Bang <keuckdo.bang@samsung.com>

[CHAD-8746] Fixed category for DM2500ZB from Light to Switch

---

drivers/SmartThings/zwave-thermostat/profiles/qubino-flush-thermostat-cooling.yml
drivers/SmartThings/zwave-thermostat/src/qubino-flush-thermostat/init.lua
drivers/SmartThings/zwave-thermostat/src/test/test_qubino_flush_thermostat.lua

Only display the currently configured mode's setpoint

CHAD-8808 Qubino Thermostat:

---

drivers/SmartThings/zigbee-thermostat/src/test/test_sinope_thermostat.lua
drivers/SmartThings/zwave-smoke-alarm/src/test/test_fibaro_smoke_sensor.lua

I discovered these while doing some testing. They have no affect on the existing drivers, just tests.

Fixup unit test bugs

---

drivers/SmartThings/zigbee-contact/profiles/multi-sensor.yml

[CHAD-9000](https://smartthings.atlassian.net/browse/CHAD-9000)
[BUG-5385](https://smartthings.atlassian.net/browse/BUG-5385)

[CHAD-9000] Change the category to the same icon as in DTH

---

drivers/SmartThings/zigbee-button/fingerprints.yml
drivers/SmartThings/zigbee-button/src/ewelink/init.lua
drivers/SmartThings/zigbee-button/src/init.lua
drivers/SmartThings/zigbee-button/src/test/test_ewelink_button.lua

Original DTH: https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/ikea-button.src/ikea-button.groovy

[CHAD-8538] Ported additional fingerprint of the 'Ikea Button DTH' for the 'eWeLink WB01'

---

drivers/SmartThings/zigbee-contact/src/multi-sensor/init.lua
drivers/SmartThings/zigbee-contact/src/multi-sensor/multi_utils.lua
drivers/SmartThings/zigbee-contact/src/smartsense-multi/init.lua
drivers/SmartThings/zigbee-contact/src/test/test_smartthings_multi_sensor.lua

Stop generating contact events from IAS zone messages if the device is installed on a garage door

CHAD-9222 IAS Zone/garage door interaction

---

drivers/SmartThings/zigbee-contact/src/test/test_aqara_contact_sensor.lua
drivers/SmartThings/zigbee-power-meter/src/test/test_zigbee_power_meter_consumption_report.lua
drivers/SmartThings/zwave-switch/src/test/test_zooz_zen_30_dimmer_relay.lua
drivers/SmartThings/zwave-thermostat/src/test/test_qubino_flush_thermostat.lua

The 44.x release artifact fixed an integration test bug that impacts
tests where messages were expected to be sent but they were not sent.

Bugfix newly added tests that are failing due to integration test bug

---

drivers/SmartThings/zwave-lock/fingerprints.yml

Adding 400 Series (ZW2 Finger Prints Yale)

Update fingerprints 400 Series ZW2.yml

---

drivers/SmartThings/zwave-siren/src/init.lua
drivers/SmartThings/zwave-siren/src/test/test_zwave_siren.lua

https://smartthings.atlassian.net/browse/CHAD-9325

Call default state for zwave-siren capabilities

---

drivers/SmartThings/zwave-sensor/src/fibaro-motion-sensor/init.lua
drivers/SmartThings/zwave-sensor/src/init.lua
drivers/SmartThings/zwave-sensor/src/test/test_fibaro_motion_sensor.lua

[CHAD-9562] Added accelerationSensor events for Fibaro Motion Sensor

---

drivers/SmartThings/zwave-smoke-alarm/src/fibaro-smoke-sensor/init.lua
drivers/SmartThings/zwave-smoke-alarm/src/test/test_fibaro_smoke_sensor.lua

Adds cleared temperatureAlarm event on add
corrects profile used for tests, add simple test of temperature alarm defaults

CHAD-9658 Fibaro Smoke: TemperatureAlarm

---

drivers/SmartThings/zwave-switch/fingerprints.yml
drivers/SmartThings/zwave-switch/profiles/child-switch.yml
drivers/SmartThings/zwave-switch/profiles/zooz-zen-30-dimmer-relay-new.yml
drivers/SmartThings/zwave-switch/profiles/zooz-zen-30-dimmer-relay.yml
drivers/SmartThings/zwave-switch/src/test/test_zooz_zen_30_dimmer_relay.lua
drivers/SmartThings/zwave-switch/src/zooz-zen-30-dimmer-relay/init.lua

[CHAD-9172] Re-Port to Parent Child: Zooz Double Switch Zen30

---

drivers/SmartThings/bose/src/lustre/ws.lua
drivers/SmartThings/zwave-switch/src/qubino-switches/qubino-relays/qubino-flush-1-relay/init.lua

Here is the command to find all these in the repo:
`luacheck --std lua53 ./ | grep "accessing undefined variable"`

Fix luacheck lints for accessing undefined variable

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/profiles/switch-power-2.yml
drivers/SmartThings/zigbee-switch/src/test/test_multi_switch_power.lua
drivers/SmartThings/zigbee-switch/src/zigbee-dual-metering-switch/init.lua

Re-Port parent/child zigbee switch power

[CHAD-9170] Re-Port parent/child zigbee switch power

---

drivers/SmartThings/zigbee-button/src/test/test_ikea_open_close.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/ikea/init.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/somfy/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/ikea/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_ikea_motion.lua

The ikea motion sensor and the somfy buttons both also had this fallback behavior in their DTHs, even though it is not on-spec.

CHAD-9480 Add fallback to group 0

---

.github/workflows/delete-channel.yml
Jenkinsfile
tools/deploy.py
tools/run_driver_tests.py

Differentiates between failures and errors when running tests Ensures a clean working directory in Jenkins when deploying drivers Delete driver channel invites when the PR that created it is closed Adds a small sleep after zipping the driver package to ensure correct execution of deploy script

CI Improvements

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2200K-4000K.yml
drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2200K-5000K.yml
drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2200K-6500K.yml
drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2500K-6000K.yml
drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2700K-5000K.yml
drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2700K-6500K.yml
drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-1800K-6500K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-2000K-6500K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-2200K-4000K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-2200K-5000K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-2200K-6500K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-2700K-5000K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb.yml

Updates white color temp ranges with embedded profile config based on vid from former DTH fingerprint.
CHAD-9469: https://smartthings.atlassian.net/browse/CHAD-9469

zigbee-switch: Update white color temp ranges

---

drivers/SmartThings/zwave-siren/profiles/philio-sound-siren.yml

CHAD-9563: https://smartthings.atlassian.net/browse/CHAD-9563

Remove unsupported alarm options for Philio Sound Siren

---

drivers/SmartThings/zwave-thermostat/fingerprints.yml
drivers/SmartThings/zwave-thermostat/profiles/base-thermostat-8to20C.yml

Changed heating and cooling range for Aeotec thermostat from 0-40°C to 8-28°C.

[CHAD-8785] Changed heating and cooling range for Aeotec thermostat.

---

drivers/SmartThings/zigbee-motion-sensor/src/aqara/aqara_utils.lua
drivers/SmartThings/zigbee-motion-sensor/src/aqara/high-precision-motion/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/aqara/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/aqara/motion-illuminance/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_aqara_high_precision.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_aqara_motion_illuminance.lua

* Updated motion detection
* Update a default frequency value
* get and set detection frequency variable
* Remove unused code

[Aqara] Motion detection updated  (#355)

---

drivers/SmartThings/zigbee-thermostat/profiles/base-thermostat-fanless.yml
drivers/SmartThings/zigbee-thermostat/profiles/base-thermostat.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-battery-powerSource.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-battery.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-popp-danfoss.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-sinope-th1300.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-sinope-th1400.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-sinope.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-stelpro-profile.yml
drivers/SmartThings/zigbee-thermostat/profiles/thermostat-temperature-temperaturealarm.yml
drivers/SmartThings/zigbee-water-leak-sensor/profiles/water-temp-tempalarm-battery.yml
drivers/SmartThings/zwave-sensor/profiles/fibaro-door-window-sensor-2.yml
drivers/SmartThings/zwave-sensor/profiles/water-battery-tempalarm.yml
drivers/SmartThings/zwave-smoke-alarm/profiles/co-battery-temperature-tamperalert-temperaturealarm.yml
drivers/SmartThings/zwave-smoke-alarm/profiles/fibaro-co-sensor-zw5.yml
drivers/SmartThings/zwave-smoke-alarm/profiles/smoke-battery-temperature-tamperalert-temperaturealarm.yml
drivers/SmartThings/zwave-smoke-alarm/profiles/temperaturealarm-battery.yml
drivers/SmartThings/zwave-thermostat/profiles/base-thermostat-without-battery.yml
drivers/SmartThings/zwave-thermostat/profiles/base-thermostat.yml
drivers/SmartThings/zwave-thermostat/profiles/qubino-flush-thermostat-cooling.yml
drivers/SmartThings/zwave-thermostat/profiles/qubino-flush-thermostat.yml
drivers/SmartThings/zwave-thermostat/profiles/thermostat-no-battery.yml
drivers/SmartThings/zwave-thermostat/profiles/thermostat-no-humidity.yml
drivers/SmartThings/zwave-thermostat/profiles/thermostat-temperature-temperaturealarm.yml

thermostatOperatingState” and “temperatureAlarmt” updated to  only contain capabilities that are supported by the device.

[CHAD-8803] "thermostatOperatingState” and “temperatureAlarm” updated

---

drivers/SmartThings/zigbee-thermostat/profiles/thermostat-popp-danfoss.yml

Updated 'thermostat-popp-danfoss' profile to have correct temperature ranges

[CHAD-9183] Updated 'thermostat-popp-danfoss'

---

drivers/SmartThings/zwave-thermostat/fingerprints.yml
drivers/SmartThings/zwave-thermostat/profiles/aeotec-radiator-thermostat.yml

https://smartthings.atlassian.net/browse/CHAD-8784

Fix aeotec thermostat profile to correct setpoint and measurement ranges

---

drivers/SmartThings/zwave-thermostat/profiles/qubino-flush-thermostat-cooling.yml
drivers/SmartThings/zwave-thermostat/profiles/qubino-flush-thermostat.yml

Updated 'qubino-flush-thermostat' and 'qubino-flush-thermostat-cooling' to have temperature range of (-13F to 176F)

[CHAD-8813] Updated 'qubino-flush-thermostat' and 'qubino-flush-thermostat-cooling'

---

drivers/SmartThings/zigbee-switch/src/test/test_multi_switch_no_master.lua
drivers/SmartThings/zigbee-switch/src/test/test_multi_switch_power.lua
drivers/SmartThings/zwave-switch/src/multi-metering-switch/init.lua
drivers/SmartThings/zwave-switch/src/test/test_fibaro_double_switch.lua
drivers/SmartThings/zwave-switch/src/test/test_fibaro_walli_double_switch.lua
drivers/SmartThings/zwave-switch/src/test/test_multi_metering_switch.lua
drivers/SmartThings/zwave-switch/src/test/test_multichannel_device.lua
drivers/SmartThings/zwave-switch/src/test/test_qubino_flush_2_relay.lua
drivers/SmartThings/zwave-switch/src/test/test_wyfy_touch.lua
drivers/SmartThings/zwave-switch/src/test/test_zooz_zen_30_dimmer_relay.lua
drivers/SmartThings/zwave-switch/src/zwave-dual-switch/init.lua

Added unit tests to cover `create_device` calls for mcd devices

---

drivers/SmartThings/philips-hue/profiles/white-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white-and-color-ambiance.yml
drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/init.lua

Fixes: CHAD-10100
Depends-On: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/474

fix: Add ranges to color temperature capabilities

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/hue/types.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/utils.lua

Forgot to refactor all usages of `device_network_id` to `parent_assigned_child_key` with the previous `EDGE_CHILD` refactor.

fix: Forgot that EDGE_CHILD devices don't have DNIs

---

drivers/SmartThings/samsung-audio/src/disco.lua
drivers/SmartThings/samsung-audio/src/init.lua

[Replaced USN to MAC as Device Identifier]

Replaced USN to MAC as Device Identifier

---

drivers/SmartThings/matter-switch/src/init.lua

Signed-off-by: Hunsup Jung <hunsup.jung@samsung.com>

Modify temp_attr_handler function in matter-switch driver

---

drivers/SmartThings/zwave-sensor/src/aeotec-multisensor/multisensor-6/init.lua
drivers/SmartThings/zwave-sensor/src/aeotec-multisensor/multisensor-7/init.lua
drivers/SmartThings/zwave-sensor/src/test/test_aeotec_multisensor_6.lua
drivers/SmartThings/zwave-sensor/src/test/test_aeotec_multisensor_7.lua

Edited added handler to include a Configuration:Get() call to query for power source in Aeotech Multisensor 6 & 7

Aeotech Multisensor:added configuration get command

---

drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua

Now that the underlying bug has been fixed in:
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/411

Fixes matter test that was written incorrectly

---

drivers/SmartThings/zwave-switch/fingerprints.yml
drivers/SmartThings/zwave-switch/profiles/smartplug-switch-power-energy.yml
drivers/SmartThings/zwave-switch/src/test/test_dawon_smart_plug.lua

[CHAD-10275](https://smartthings.atlassian.net/browse/CHAD-10275)

CHAD-10275 Change the device type of zwave dawon smartPlug(switch -> smartPlug)

---

drivers/SmartThings/zwave-sensor/src/homeseer-multi-sensor/init.lua
drivers/SmartThings/zwave-sensor/src/test/test_homeseer_multi_sensor.lua

Edited homeseer multisensor sub-driver to support device refresh specified from DTH.

zwave-sensor: Homeseer Multisensor

---

drivers/SmartThings/zwave-sensor/src/aeotec-multisensor/multisensor-6/init.lua
drivers/SmartThings/zwave-sensor/src/aeotec-multisensor/multisensor-7/init.lua
drivers/SmartThings/zwave-sensor/src/test/test_aeotec_multisensor_6.lua
drivers/SmartThings/zwave-sensor/src/test/test_aeotec_multisensor_7.lua

Had to rework previously merged code to move get commands from init function to wakeup notification handler.

reworked wakeup handler

---

drivers/SmartThings/matter-sensor/profiles/temperature-battery.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity-battery.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity.yml
drivers/SmartThings/matter-sensor/profiles/temperature.yml

TempSensor is not a defined type.

BUG-6974 Correct matter temp sensor category

---

drivers/SmartThings/zigbee-window-treatment/fingerprints.yml
drivers/SmartThings/zigbee-window-treatment/profiles/vimar-window-treatment-profile.yml
drivers/SmartThings/zigbee-window-treatment/profiles/window-treatment-profile-no-firmware-update.yml
drivers/SmartThings/zigbee-window-treatment/src/init.lua
drivers/SmartThings/zigbee-window-treatment/src/vimar/init.lua

Add support for: 
- Vimar Smart Roller Shutter (xx594)
- Vimar Smart Roller Shutter Module (03982)

Add zigbee-window-treatment for Vimar xx594 and 03982

---

drivers/SmartThings/matter-sensor/profiles/humidity-battery.yml
drivers/SmartThings/matter-sensor/profiles/humidity.yml
drivers/SmartThings/matter-sensor/profiles/temperature-battery.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity-battery.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity.yml
drivers/SmartThings/matter-sensor/profiles/temperature.yml

added humidityOffset and tempOffset preferences to applicable matter-sensor profiles to match with Zigbee/zwave profiles

added preferences to matter-sensor profiles

---

.github/scripts/check_duplicates.py

This change consists of a few changes:
* Add preferences to the check when comparing profiles
* Move component comparison logic to its own function
* Print out "profile-comment-body.md" contents at end of script

Add preferences to duplicate profile script; various improvements

---

drivers/SmartThings/zwave-siren/src/philio-sound-siren/init.lua
drivers/SmartThings/zwave-siren/src/test/test_philio_sound_siren.lua

PR for task: https://smartthings.atlassian.net/browse/CHAD-10239?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=1252022#comment-1252022

CHAD-10239 Add emit event in handling chime

---

drivers/SmartThings/zwave-thermostat/profiles/aeotec-radiator-thermostat.yml

https://smartthings.atlassian.net/browse/CHAD-8786

Add step to aeotec thermostat setpoint; remove unneeded capabilities

---

drivers/SmartThings/matter-switch/fingerprints.yml

This reverts commit 376cdbeed9c6e664942ebb19a1823e2bdbf204d7.

Add fingerprints for Eve Energy

---

drivers/SmartThings/matter-sensor/fingerprints.yml

Eve Door and Window fingerprint add for certification request.

Eve door window

---

drivers/SmartThings/sonos/src/api/cmd_handlers.lua

Fix keying in to `volume` instead of `groupVolume`.

---

drivers/SmartThings/samsung-audio/src/command.lua
drivers/SmartThings/samsung-audio/src/handlers.lua
drivers/SmartThings/samsung-audio/src/init.lua

Audio Notification feature implementation as referred at https://smartthings.atlassian.net/browse/CHAD-10452

Implement Audio Notification Capability

---

drivers/SmartThings/zwave-switch/src/fibaro-double-switch/init.lua
drivers/SmartThings/zwave-switch/src/test/test_fibaro_double_switch.lua

https://smartthings.atlassian.net/browse/HCS-4161

Add delay for switch on/off on Fibaro double switch

---

drivers/SmartThings/wemo/src/discovery.lua

Several crashes are occurring because the location header is not always parsed. This could be because the regex was not considering all valid headers, or because the header didn't exist. This change makes sure no crash occurs in either case.

Wemo disco http response processing improvement

---

drivers/SmartThings/zwave-switch/profiles/zooz-zen-30-dimmer-relay-new.yml
drivers/SmartThings/zwave-switch/profiles/zooz-zen-30-dimmer-relay.yml
drivers/SmartThings/zwave-switch/src/test/test_zooz_zen_30_dimmer_relay.lua
drivers/SmartThings/zwave-switch/src/zooz-zen-30-dimmer-relay/init.lua

Adds "stateChange: true" for all button events.
Fixes some preferences that were integers instead of enums

HCS-4170 HCS-4173 Zooz Zen 30 fixes

---

drivers/SmartThings/zwave-siren/src/ecolink-wireless-siren/init.lua
drivers/SmartThings/zwave-siren/src/test/test_ecolink_wireless_siren.lua

on/off capability handlers were not handled by sub driver, results in incorrect status reporting, changed to reflect DTH behavior

edited how ecolink wireless siren handles on/off and status reporting

---

drivers/SmartThings/matter-lock/src/init.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_codes.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_cota.lua
drivers/SmartThings/matter-media/fingerprints.yml
drivers/SmartThings/matter-media/src/init.lua
drivers/SmartThings/matter-media/src/test/test_matter_media_speaker.lua
drivers/SmartThings/matter-media/src/test/test_matter_media_video_player.lua
drivers/SmartThings/matter-sensor/src/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_sensor.lua
drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_featuremap.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat.lua
drivers/SmartThings/matter-window-covering/src/init.lua
drivers/SmartThings/matter-window-covering/src/test/test_matter_window_covering.lua

* Make mock devices more like real devices
* Write new unit tests to improve code coverage
* Note unsupported functionality in driver code comments

Unit test coverage based on matter cert test case audit

---

drivers/SmartThings/zigbee-switch/src/rgbw-bulb/init.lua

[CHAD-10783] Fixed unexpected colorTemperature change for ABL-LIGHT-Z-201

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/lunchbox/rest.lua
drivers/SmartThings/philips-hue/src/lunchbox/sse/eventsource.lua

PR contains 3 commits addressing some general edge cases and stability issues with the Hue driver.

Hue: Fixes for CHAD-10827, CHAD-10798, general reliability/stability improvements

---

drivers/SmartThings/zigbee-switch/fingerprints.yml

Change-Id: I9e7a69d16dfb83a8259ad2c38823c47856882900

add thirdreality smart plug with power

---

drivers/SmartThings/zwave-switch/src/multi-metering-switch/init.lua

This change attempts to add a delay between the reset and the get, as was present in the DTH

CHAD-10714 Reset works inconsistently for aeotec multi switch

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/profiles/aqara-light.yml
drivers/SmartThings/zigbee-switch/src/aqara-light/init.lua
drivers/SmartThings/zigbee-switch/src/init.lua
drivers/SmartThings/zigbee-switch/src/preferences.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_light.lua

Aqara Smart Dimmer Controller T1 Pro

[Aqara] Aqara Smart Dimmer Controller T1 Pro

---

drivers/SmartThings/philips-hue/src/init.lua

We previously only addressed stray bulbs during the "added" codepaths that are hit during fresh join and during migration.
I'm not sure how one can get in to a situation where they have stray bulbs post-added, but we've seen it, so this is a fix for it.
Fixes: CHAD-10941

fix: Address stray bulbs at init.

---

Jenkinsfile

Adds the channel(s) that will be updated to the build name for better visibility.
Adds the drivers changed to the build description for easier viewing

Jenkins build description enhancements

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/aqara/init.lua
drivers/SmartThings/zigbee-switch/src/aqara/multi-switch/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_wall_switch.lua

Add new zigbee device.
Aqara Smart Wall Switch (No Neutral, Double Rocker)

[Aqara] Aqara Smart Wall Switch (No Neutral, Double Rocker)

---

tools/deploy.py

Reverts SmartThingsCommunity/SmartThingsEdgeDrivers#767

Revert "force update of all drivers on new production"

---

drivers/SmartThings/sonos/search-parameters.yml

Add search parameters for the Sonos driver.
https://smartthings.atlassian.net/browse/CHAD-10630

Sonos: Add search parameters

---

drivers/SmartThings/bose/search-parameters.yml

Adds search parameters for the Bose driver.
https://smartthings.atlassian.net/browse/CHAD-10631

Bose: Add search parameters

---

drivers/SmartThings/philips-hue/search-parameters.yml

Add search parameters for the phillips-hue driver.
https://smartthings.atlassian.net/browse/CHAD-10632

hue: Add search parameters

---

Jenkinsfile
tools/deploy.py

Also includes a new parameter to allow setting specific drivers to be deployed even if they were not changed.

Change to a more widely-available jenkins agent

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/lunchbox/rest.lua

This reverts commit 90a67884dfbce68bfac01ed24e07f07ef3620f89, reversing changes made to 716407fa5716ccfa73e156c88b3c3376d5fb630f.

Revert "Merge pull request #774 from SmartThingsCommunity/fix/CHAD-11148-migration-crash-resilience

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/lunchbox/rest.lua
drivers/SmartThings/philips-hue/src/lunchbox/sse/eventsource.lua

This commit does several things:
1. Attempts to move most networking operations off the device/driver threads
2. Adds looping/retry to "rediscovery" logic in init/migrate
3. Adds timeouts to all cosock channels

Make the driver more resilient to network issues

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/lunchbox/sse/eventsource.lua
drivers/SmartThings/philips-hue/src/utils.lua

Adds back some choice hue logging statements for better migration debugging.

Add back some hue logging in hub logs for migration testing

---

drivers/SmartThings/sonos/src/lunchbox/rest.lua

Agreed it was worth hotfixing while discussing via Zoom, here's the cherry-picked commit from the main branch.

Sonos hotfix for missing error handling in socket receive path

---

drivers/SmartThings/sonos/src/fields.lua
drivers/SmartThings/sonos/src/init.lua
drivers/SmartThings/sonos/src/lustre/ws.lua
drivers/SmartThings/sonos/src/ssdp.lua

Network conditions can cause some values to come in incomplete,
be missing entirely, or cause other such issues.
This PR adds some resiliency to this:
1. SSDP Scanning can now run indefinitely, to deal with delay and
congestion on some networks
2. We've added some nil checking in a few places where network
conditions can lead to nil values

Sonos Edge Driver networking reliability fixes

---

drivers/SmartThings/sonos/src/types.lua

runtime error: [string "cosock.lua"]:296: [string "types.lua"]:254: attempt to index a nil value (field '?')

Sonos crash fix

---

drivers/SmartThings/zigbee-presence-sensor/capabilities/movementSensor.yaml
drivers/SmartThings/zigbee-presence-sensor/fingerprints.yml
drivers/SmartThings/zigbee-presence-sensor/profiles/aqara-presence-sensor-fp1.yml
drivers/SmartThings/zigbee-presence-sensor/src/aqara/init.lua
drivers/SmartThings/zigbee-presence-sensor/src/arrival-sensor-v1/init.lua
drivers/SmartThings/zigbee-presence-sensor/src/init.lua
drivers/SmartThings/zigbee-presence-sensor/src/test/test_aqara_presence_sensor_fp1.lua

Add Aqara presence sensor FP1.

[Aqara] Aqara Presence Sensor FP1

---

drivers/SmartThings/zigbee-window-treatment/src/test/test_zigbee_window_shade_battery_yoolax.lua
drivers/SmartThings/zigbee-window-treatment/src/yoolax/init.lua

Some users reported window shades that were not generating final closed/open events after being issued an open/close command. Upon investigation, the window shade was not sending attribute updates despite supposedly having attribute reporting configured. With this change, if no update is received within 30s, the driver will re-bind to the cluster and re-configure the attribute, and then issue an attribute read

BUG-7996 Re-bind yoolax window shades if no update received

---

drivers/SmartThings/philips-hue/src/cosock/socket/internals.lua

These changes are in the lua libs but we need to get some data
from the existing fleet before this goes to GA, so we're going
to vendor it in the driver for now.

Cosock diagnostic logs from SE PRs #1538 and #1543

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/white-color-temp-bulb/init.lua

https://smartthings.atlassian.net/browse/CHAD-11428

Add missing fingerprints of DURAGREEN

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/hue/types.lua
drivers/SmartThings/philips-hue/src/init.lua

These are fixes that we validated in Alpha against users with connectivity issues to very promising results, so we want to get them in to Beta today such that they make it in to the production release tomorrow.

Early-release-hue-fixes-to-beta

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/multi-switch-no-master/init.lua

Migrate some HEIMAN Switch from DTH to EdgeDriver
HS6SW1A-W-EF-3.0
HS6SW2A-W-EF-3.0
HS6SW3A-W-EF-3.0
Refer to:
https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zigbee-multi-switch.src/zigbee-multi-switch.groovy

Add HEIMAN Switch

---

drivers/SmartThings/zwave-fan/src/zwave-fan-3-speed/init.lua

This new 3-speed fan fingeprint was added, but without the corresponding addition into the sub-driver.

Fix up pull #605

---

drivers/SmartThings/zigbee-button/fingerprints.yml
drivers/SmartThings/zigbee-button/src/test/test_heiman_button.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/heiman/init.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/init.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/supported_values.lua

Migrate HS6SSB-W-EF-3.0 from DTH to EdgeDriver
Refer to:
https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zigbee-scene-keypad.src/zigbee-scene-keypad.groovy

Add HEIMAN HS6SSB-W-EF-3.0 Scene Panel

---

drivers/SmartThings/zigbee-button/fingerprints.yml
drivers/SmartThings/zigbee-button/src/test/test_wallhero_button.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/init.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/supported_values.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/wallhero/init.lua
drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/test/test_wallhero_switch.lua
drivers/SmartThings/zigbee-switch/src/wallhero/init.lua

The manufacturer has modified the display name and model

Change the name of the wallhero switch and scene

---

drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-switch/profiles/light-color-level-2700K-6500K.yml

Pull request for Nanoleaf Essential Models.
Models include:
- Primary: Essentials A19/A60
- Reference: Essentials BR30
- Reference: Essentials GU10
- Reference: Essentials Downlight
- Reference: Essentials Lightstrip

Nanoleaf Essentials

---

drivers/SmartThings/matter-switch/fingerprints.yml

right device label: Cync Full Color A19, Cync Indoor Plug

Update fingerprints.yml for right device label

---

drivers/SmartThings/matter-window-covering/fingerprints.yml

Pull Request to add Eve MotionBlinds for WWST

Eve MotionBlinds

---

drivers/SmartThings/zigbee-button/src/test/test_shinasystem_button.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/shinasystems/init.lua

https://smartthings.atlassian.net/browse/CHAD-11725
I found this problem while testing another issue.(https://smartthings.atlassian.net/browse/CHAD-11697)

Add hub group for SiHAS button

---

drivers/SmartThings/zigbee-window-treatment/fingerprints.yml
drivers/SmartThings/zigbee-window-treatment/src/invert-lift-percentage/init.lua

Added Nexentro Actuator:
NEXENTRO Blinds Actuator

Added NEXENTRO Blinds Actuator

---

drivers/SmartThings/matter-switch/src/init.lua

This changes the endpoint-component mapping to use the component as the key for the map. This is the same as was done for https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/994
This change is required because our lua libs cannot handle tables with numerical keys that don't start at 1. See here for more detail: https://smartthings.atlassian.net/browse/MTR-453

Matter Switch: use component as key for endpoint map

---

drivers/SmartThings/matter-button/src/init.lua

Hue accessories like the Tap Dial Switch that use the Matter Button driver do support the PowerSource cluster but they do not implement the optional BatPercentageRemaining attribute. The `battery` capability requires the percentage remaining so we're going to remove the `battery` capability from these devices for now.
We have plans to replace this code with something more dynamic in the future, plus we want to expose the battery information for these devices somehow.
Note: This change will only apply to newly joined devices.
https://smartthings.atlassian.net/browse/MTR-474

matter-button: Fix warning related to battery with Hue switches/buttons

---

drivers/SmartThings/matter-button/src/init.lua
drivers/SmartThings/matter-button/src/test/test_matter_multi_button.lua
drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-switch/src/init.lua

This rolls up the changes from the following PRs into beta to address issues in the matter drivers beta.
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/994
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/995
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/996
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/997
After this, #996 will be hot fixed to production.

Roll up matter driver changes to beta

---

drivers/SmartThings/matter-switch/fingerprints.yml

This is a cherry-pick from beta of the changes in #996

Hotfix dimmer bulbs to restore level control functionality

---

drivers/SmartThings/zigbee-range-extender/fingerprints.yml

Added Nexentro Actuator:
NEXENTRO Pushbutton Interface

Added NEXENTRO Pushbutton Interface Fingerprint

---

.github/workflows/upload-driver-packages.yml
tools/deploy.py

Also added .pem to deploy.py and upload-driver-packages.yml since .pem is another common extension for these types of files.

fix: Update deploy.py to capture .crt and .pem files

---

drivers/SmartThings/zigbee-switch/fingerprints.yml

Added Nexentro Actuator:
NEXENTRO Switching Actuator

Added NEXENTRO Switching Actuator Fingerprints

---

drivers/SmartThings/matter-sensor/fingerprints.yml

Add support for Netatmo Smart 2-in-1 Sensor (occupancy and contact Matter sensor)

Add fingerprint for Netatmo Smart 2-in-1 Sensor

---

drivers/SmartThings/sonos/src/init.lua

Subtle edge cases with the persistent store's eventual consistency mean that it's possible for these stores to get in to a bad state, and some of the APIs on the hub will hard crash when given stale data on older hub firmware versions that are still actively supported. Moving these stores to be ephemeral could slow down detection of IP address changes but shouldn't hamper functionality.

fix: Remove some lookups from persistent store

---

drivers/SmartThings/zwave-lock/fingerprints.yml

WWST CERT submission for the Yale Assure 2 Biometric Z-Wave Lock

Assure 2 Biometric 410

---

drivers/SmartThings/zwave-lock/fingerprints.yml

WWSTCERT for Yale Assure 2 Bio 430 Z-Wave Lock

WWST CERT for Yale Assure 2 Bio 430

---

drivers/SmartThings/zwave-lock/fingerprints.yml

WWST CERT Request to add the Yale Asure 2 BIO 450 Z-Wave Lock

Yale-Assure-2-Bio-450

---

drivers/SmartThings/bose/src/disco.lua
drivers/SmartThings/bose/src/init.lua

Tested with my bose and changing its IP.

CHAD-11469: Detect Bose IP Changes

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/profiles/wallhero.yml
drivers/SmartThings/zigbee-switch/src/test/test_wallhero_switch.lua
drivers/SmartThings/zigbee-switch/src/wallhero/init.lua

This PR is used to make the backlight of WALLHREO adjustable

Change Backlight

---

drivers/SmartThings/zwave-lock/fingerprints.yml

Add support for TLJ Door Lock.

TLJ Door Lock fingerprint

---

drivers/SmartThings/matter-window-covering/fingerprints.yml
drivers/SmartThings/matter-window-covering/profiles/window-covering-battery.yml
drivers/SmartThings/matter-window-covering/profiles/window-covering.yml
drivers/SmartThings/matter-window-covering/src/init.lua
drivers/SmartThings/matter-window-covering/src/test/test_matter_window_covering.lua

Adds ability to profile switch to a profile with battery support on init.

Matter Window Covering: battery profile switching support

---

drivers/SmartThings/matter-switch/src/eve-energy/init.lua
drivers/SmartThings/matter-switch/src/test/test_eve_energy.lua

Taken from https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1088 with an additional fix

Eve Energy: group attribute reads to improve performance

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-switch/fingerprints.yml

Add heiman motion sensor for WWST.
Hi @lelandblue ,
Could you help to close the other PRs because I can't modify those PRs, I will resubmit motion sensor and door sensor separately. Thanks.

add heiman motion sensor  for WWST

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/profiles/switch-power-energy-consumption-report-aqara-t1.yml
drivers/SmartThings/zigbee-switch/src/aqara/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_smart_plug_t1.lua

* Aqara Smart Plug T1
* modification time
---------

Aqara Smart Plug T1 (#1127)

---

drivers/SmartThings/zigbee-lock/src/init.lua
drivers/SmartThings/zigbee-lock/src/test/test_zigbee_lock.lua

Commands can arrive from a zigbee lock after an unlock event in any order. This can be a problem if the door lock operation event arrives _after_ the attribute report about the door lock state. Because the door lock attribute update doesn't include any useful metadata, but it arrives first, the second command with the useful metadata is marked as a duplicate and debounced, dropping all of that useful metadata on the floor. This same issue can also happen with Z-Wave, but because of the overloading of the notification defaults, it will have to be fixed via updates to the lua libraries. This fix is also going into the lua libraries, but it's easier to also deploy it quicker here.

BUG2-659 Zigbee locks: fix out-of-order commands

---

drivers/SmartThings/matter-air-purifier/profiles/air-purifier.yml
drivers/SmartThings/matter-air-purifier/profiles/sve-air-purifier.yml
drivers/SmartThings/matter-air-purifier/src/init.lua

- `airPurifierFanMode`
- `filterState`
- `filterStatus`

matter-air-purifier: Support new capabilities

---

drivers/SmartThings/matter-air-purifier/profiles/air-purifier.yml
drivers/SmartThings/matter-air-purifier/src/init.lua

Update matter-air-purifier driver

---

tools/localizations/cn.csv

Name error，so change Agara to Aqara

Change Agara to Aqara

---

drivers/SmartThings/matter-appliance/fingerprints.yml
drivers/SmartThings/matter-appliance/profiles/refrigerator-freezer-tl.yml
drivers/SmartThings/matter-appliance/profiles/refrigerator-freezer-tn.yml
drivers/SmartThings/matter-appliance/src/init.lua

matter-appliance: Improve profile configuration

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/init.lua

The first thing we do is we store the API keys in the datastore right away instead of waiting for a device record to exist. This hardens us against the situation where the driver restarts for any reason while the Hue Bridge device's `added` handler is still executing and is early enough in its execution that we haven't stored the key on the device object yet.
We also address a regression from the automatic add/delete changes, which can lead to the creation of duplicate device records for bulbs in some specific circumstances.

fix: Add some hardening to the Hue discovery logic.

---

drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-switch/profiles/light-level-ColorTemperature-1500-9000k.yml

Adding New Profile to handle Light Range.

LIFX Matter Pull Request

---

drivers/SmartThings/zigbee-button/fingerprints.yml
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/ikea/init.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/init.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/supported_values.lua

Jira : https://smartthings.atlassian.net/browse/CHAD-12631

[CHAD-12631] fix(zigbee-button): Adding exception case of manufacturer information for IKEA button

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/profiles/aqara-led-bulb.yml
drivers/SmartThings/zigbee-switch/src/aqara-light/init.lua
drivers/SmartThings/zigbee-switch/src/preferences.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_led_bulb.lua

Aqara LED Light Bulb T1 (Tunable White)

Aqara LED Light Bulb T1 (Tunable White)

---

drivers/SmartThings/matter-thermostat/src/init.lua

matter-room-air-conditioner: Fix fan control percent feature

---

drivers/SmartThings/jbl/src/lunchbox/rest.lua

fixup! jbl variable sccope

---

drivers/SmartThings/jbl/src/lunchbox/rest.lua

Cannot onboading JBL 300 with 0.50.10 hubcore

Cannot onboading JBL 300

---

drivers/SmartThings/matter-sensor/src/air-quality-sensor/init.lua

Matter Sensor: Support default units for concentration clusters

---

drivers/SmartThings/matter-window-covering/src/init.lua
drivers/SmartThings/matter-window-covering/src/test/test_matter_window_covering.lua

Operational state is mismatching with actual status of window covering

Fix incorrect operational state issue by workaround

---

drivers/SmartThings/zwave-switch/fingerprints.yml

This is a PR to add two new devices that use the smartplug-switch-energy-power capabilities.

New Devices (Z-Wave Switch): Smart Plugs

---

drivers/SmartThings/zigbee-smoke-detector/src/aqara-gas/init.lua
drivers/SmartThings/zigbee-smoke-detector/src/test/test_aqara_gas_detector.lua

reference:
wash-2068
STSE-2612

fix aqara gas detector reonboarding issue

---

drivers/SmartThings/matter-switch/profiles/light-color-level-illuminance-motion.yml
drivers/SmartThings/matter-switch/profiles/light-color-level.yml
drivers/SmartThings/matter-switch/profiles/light-level-colorTemperature.yml
drivers/SmartThings/matter-switch/profiles/switch-color-level.yml
drivers/SmartThings/matter-switch/profiles/switch-level-colorTemperature.yml
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_lights.lua

This commit addresses minor issues discovered after PR 1220 was merged into main.

Matter-Switch: Fixes for color temp and level limit reads

---

drivers/SmartThings/matter-window-covering/fingerprints.yml
drivers/SmartThings/zigbee-illuminance-sensor/src/aqara/init.lua
drivers/SmartThings/zigbee-illuminance-sensor/src/test/test_illuminance_sensor_aqara.lua
drivers/SmartThings/zigbee-motion-sensor/src/aqara/high-precision-motion/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/aqara/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_aqara_high_precision.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_aqara_motion_illuminance.lua
drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/rgbw-bulb/init.lua
drivers/SmartThings/zigbee-switch/src/zigbee-dimming-light/init.lua
drivers/SmartThings/zigbee-water-leak-sensor/fingerprints.yml
drivers/SmartThings/zigbee-water-leak-sensor/src/init.lua
drivers/SmartThings/zigbee-water-leak-sensor/src/sengled/init.lua
drivers/SmartThings/zigbee-water-leak-sensor/src/test/test_sengled_water_leak_sensor.lua

Rolling up main to beta to get changes from https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1304 to beta before production deploy.

rolling up main to beta

---

drivers/SmartThings/zigbee-smoke-detector/profiles/gas-lifetime-selfcheck-aqara.yml
drivers/SmartThings/zigbee-smoke-detector/profiles/smoke-battery-aqara.yml

Use named vid instead of uuid for `Aqara Smart Natural Gas Detector` & `Aqara Smart Smoke Detector`

---

drivers/Aqara/aqara-lock/capabilities/lockCredentialInfo.yaml
drivers/Aqara/aqara-lock/config.yml
drivers/Aqara/aqara-lock/fingerprints.yml
drivers/Aqara/aqara-lock/presentation/lockCredentialInfo.presentation.yaml
drivers/Aqara/aqara-lock/profiles/aqara-lock-battery.yml
drivers/Aqara/aqara-lock/src/credential_utils.lua
drivers/Aqara/aqara-lock/src/init.lua
drivers/Aqara/aqara-lock/src/test/test_aqara_lock.lua

* add aqara-lock package and K100 driver
* modified code based on reviewer's comments
* I modified this code based on the feedback.
* update code
* add aqara-provisioning
* remove "aqara-provisioning" from aqara-feeder and add "aqara_provisioning" to aqara-lock
* fix user management errors
---------

[Aqara] Aqara doorlock K100 (#1296)

---

drivers/SmartThings/zigbee-motion-sensor/src/test/test_aqara_high_precision.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_aqara_motion_illuminance.lua

Improve code test coverage upon 90% for WASH-2068
aqara/aqara_utils.lua                31   2      93.94%
aqara/high-precision-motion/init.lua 78   0      100.00%
aqara/init.lua                       80   6      93.02%

Add TC to improve motion sensor code test coverage

---

drivers/SmartThings/matter-switch/src/init.lua

Only set the find_child function for parent-child devices. This is because in cases where a bridge is onboarded with many devices, the set_find_child function is call which sets the find_child function. When the bridge is onboarded, it then calls get_devices() when when the first event is emitted because the device checks for any child devices the current device might have. This get_devices() call ends up adding all devices in the driver to the device cache. Once in the device cache, the `init` event is skipped. However, there is a race condition where when adding a large number of bridged devices, some devices can be added to the device cache before they have initialized, causing them to miss the `init` event. This happens when a device with a find_child function emits an event for a …

Matter Switch: only set_find_child for parent-child devices

---

drivers/SmartThings/philips-hue/PROGRESS.md
drivers/SmartThings/philips-hue/src/consts.lua
drivers/SmartThings/philips-hue/src/handlers/attribute_emitters.lua
drivers/SmartThings/philips-hue/src/handlers/commands.lua
drivers/SmartThings/philips-hue/src/handlers/refresh_handlers.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/hue/types.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/utils.lua

This is a purely structural refactor.
Depends on #1334

 Refactor attribute event emitters in to a module.

---

drivers/SmartThings/zigbee-switch/src/aqara/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_smart_plug.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_smart_plug_t1.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_switch_module.lua

This is a fix for re-onboarding scenario:
STSE-2617

fix issue that Aqara Smart Plug T1 doesn't work after reonboarding

---

drivers/SmartThings/zigbee-switch/src/aqara-light/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_led_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_light.lua

fix Aqara LED Light Bult T1 reonboarding issue

---

drivers/Aqara/aqara-feeder/src/init.lua
drivers/Aqara/aqara-feeder/src/test/test_aqara_pet_feeder.lua

1. add new error status event
2. fix abnormal feeding logs in history tab and life cycle issues

[Aqara/Smart Pet Feeder] add new event and fix issues

---

drivers/SmartThings/zigbee-contact/src/smartsense-multi/init.lua
drivers/SmartThings/zigbee-contact/src/test/test_smartsense_multi.lua

The original SmartSense Multi has a different z-axis than the newer sensors.
When installed on the garage door it is parallel to the ground when the door
is closed and perpendicular to the ground when the door is open. For this
reason it can't share the garage door handling code that the newer sensors
use. This change implements the necessary custom handling and adds a unit
test.
https://smartthings.atlassian.net/browse/CHAD-13098

zigbee-contact: Fix garage door handling for SmartSense Multi 

---

drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/aqara-light/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_led_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_light.lua

This PR is for the weekly release that happens when we move changes in to meta, to Beta.

Weekly deploy from Main to Beta

---

drivers/SmartThings/matter-sensor/src/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_sensor.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_sensor_featuremap.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_sensor_rpc.lua

Subscribe to the temperature limit attributes and set capability constraint based on the limits.

Matter Sensor:  Temp limits dynamic constraints

---

drivers/SmartThings/zwave-window-treatment/fingerprints.yml

This PR is to add the RYSE SmartShade device to the Edge Drivers Repo

New Device (Z-Wave Window Treatment) RYSE SmartShade

---

drivers/SmartThings/matter-sensor/fingerprints.yml

This is an addition of the Matter Aqara Motion and Light Sensor P2 device that is seeking WWST Certification.

New Device (Matter Sensor) Aqara Motion and Light Sensor P2

---

drivers/Aqara/aqara-lock/capabilities/antiLockStatus.yaml
drivers/Aqara/aqara-lock/capabilities/lockAlarm.yaml
drivers/Aqara/aqara-lock/profiles/aqara-lock-battery.yml
drivers/Aqara/aqara-lock/src/init.lua
drivers/Aqara/aqara-lock/src/test/test_aqara_lock.lua
drivers/SmartThings/matter-appliance/src/init.lua
drivers/SmartThings/matter-appliance/src/matter-dishwasher/init.lua
drivers/SmartThings/matter-appliance/src/matter-laundry-washer/init.lua
drivers/SmartThings/matter-lock/capabilities/lockAlarm.yml
drivers/SmartThings/matter-lock/fingerprints.yml
drivers/SmartThings/matter-lock/profiles/lock-lockalarm-nobattery.yml
drivers/SmartThings/matter-lock/profiles/lock-lockalarm.yml
drivers/SmartThings/matter-lock/src/init.lua
drivers/SmartThings/matter-lock/src/test/test_aqara_matter_lock.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_codes.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_cota.lua
drivers/SmartThings/matter-rvc/src/init.lua
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/zigbee-lock/fingerprints.yml
drivers/SmartThings/zwave-switch/fingerprints.yml
drivers/SmartThings/zwave-switch/profiles/leviton-zw15s.yml
drivers/SmartThings/zwave-switch/profiles/leviton-zw6hd.yml
drivers/SmartThings/zwave-switch/src/preferences.lua
tools/localizations/cn.csv

Still holding Hue back, but we intend to resolve that later this week.

Rolling up Beta to Production

---

drivers/SmartThings/matter-pump/config.yml
drivers/SmartThings/matter-pump/fingerprints.yml
drivers/SmartThings/matter-pump/profiles/pump-level.yml
drivers/SmartThings/matter-pump/profiles/pump-only.yml
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/init.lua
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/server/attributes/ControlMode.lua
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/server/attributes/EffectiveControlMode.lua
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/server/attributes/EffectiveOperationMode.lua
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/server/attributes/OperationMode.lua
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/server/attributes/PumpStatus.lua
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/server/attributes/Speed.lua
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/server/attributes/init.lua
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/types/ControlModeEnum.lua
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/types/Feature.lua
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/types/OperationModeEnum.lua
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/types/PumpStatusBitmap.lua
drivers/SmartThings/matter-pump/src/PumpConfigurationAndControl/types/init.lua
drivers/SmartThings/matter-pump/src/embedded-cluster-utils.lua
drivers/SmartThings/matter-pump/src/init.lua

These matter pump changes were taken from this Matter 1.2 PR so we could address some remaining open items: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1422

Matter Pump: add support for pump device type

---

drivers/SmartThings/matter-switch/fingerprints.yml

Fingerprint for WWST certification for Nanoleaf essentials device

Matter Switch: Add Nanoleaf Essentials Wifi Bulb fingerprint

---

drivers/SmartThings/matter-switch/fingerprints.yml

Add fingerprint for Matter Smart Light Bulb A21 RGBTW 1600lm WWST certification

Matter Switch: new device Linkind Smart Light Bulb A21 RGBTW 1600lm

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adds quotes around fingerprint ID from fingerprint introduced here: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1530

Matter Switch: add missing quotes around fingerprint id

---

drivers/SmartThings/matter-appliance/fingerprints.yml
drivers/SmartThings/matter-appliance/profiles/cook-surface-one-cook-surface-two-tl.yml
drivers/SmartThings/matter-appliance/profiles/cook-surface-one-cook-surface-two-tn.yml
drivers/SmartThings/matter-appliance/profiles/cook-surface-one-cook-surface-two.yml
drivers/SmartThings/matter-appliance/profiles/cook-surface-one-tl-cook-surface-two-tl.yml
drivers/SmartThings/matter-appliance/profiles/cook-surface-one-tl-cook-surface-two-tn.yml
drivers/SmartThings/matter-appliance/profiles/cook-surface-one-tl-cook-surface-two.yml
drivers/SmartThings/matter-appliance/profiles/cook-surface-one-tl.yml
drivers/SmartThings/matter-appliance/profiles/cook-surface-one-tn-cook-surface-two-tl.yml
drivers/SmartThings/matter-appliance/profiles/cook-surface-one-tn-cook-surface-two-tn.yml
drivers/SmartThings/matter-appliance/profiles/cook-surface-one-tn-cook-surface-two.yml
drivers/SmartThings/matter-appliance/profiles/cook-surface-one-tn.yml
drivers/SmartThings/matter-appliance/profiles/cook-surface-one.yml
drivers/SmartThings/matter-appliance/profiles/cook-top.yml
drivers/SmartThings/matter-appliance/src/init.lua
drivers/SmartThings/matter-appliance/src/matter-cook-top/init.lua
drivers/SmartThings/matter-appliance/src/matter-refrigerator/init.lua

Update matter-appliance driver for Cook Top device Type

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-thermostat/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/init.lua
drivers/SmartThings/zwave-bulb/src/init.lua
drivers/SmartThings/zwave-switch/src/init.lua

- [ X] Release
Cherry Picking the two PRs at the Risk Review Meeting to move to Beta before Production Release
1. https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1567
2. https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1520

Cherry Pick - PRs into Beta before Production Release

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_air_purifier.lua

Matter Thermostat: clamp percentage values

---

drivers/SmartThings/matter-lock/fingerprints.yml
drivers/SmartThings/matter-lock/src/aqara-lock/init.lua

- This PR is a fingerprint only code change to add a fingerprint for the Aqara U300 device. I anticipate that this will use the new sub-driver created for the U200 device. 
- The testing of this device certification will be handled by the WWST process.

New Device (Matter Lock) Aqara U300

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/multi-switch-no-master/init.lua

Add shinasystem's full buttons switch for wwst

---

drivers/SmartThings/matter-switch/fingerprints.yml

- Addition of a Fingerprint for the following device:
1. ProductName: Magic Cube DS001, ModelNumber: MFDS014. According to the DCL:
PID: 0x2005
VID: 0x1462
Matter Device Type : 10C
- Testing has not yet occurred by the team in SRPOL, once this is completed with passing results then I will merge the PR.

New Device (Matter Switch) Magic Cube DS001

---

drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/aqara/init.lua
drivers/SmartThings/zigbee-switch/src/aqara/multi-switch/init.lua
tools/localizations/cn.csv

Links to PR's:
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1532
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1562
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1623

Expedite #1532, #1562, and #1623 to `beta` ahead of `prod`

---

.github/workflows/run-tests.yml

Update Github Actions Artifacts version

---

.github/workflows/run-tests.yml
drivers/SmartThings/matter-switch/fingerprints.yml

Links to PRs:
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1630
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1633

 Expedite #1630 and #1633 to beta ahead of prod

---

drivers/SmartThings/matter-sensor/fingerprints.yml

Add fingerprint for WWST certification

Matter Sensor: add new device Heiman smoke sensor

---

drivers/SmartThings/matter-switch/fingerprints.yml

- [  X ] I have performed a self-review of my code
New fingerprint only submission for a Matter Switch device, the Legrand Radiant Smart Switch Model [WWMRL10WH] . I believe this is the product page, but could be mistaken[https://www.legrand.us/wiring-devices/designer-switches-and-outlets/radiant-smart-switch-with-netatmo-white/p/wnrl10wh?srsltid=AfmBOop4UlHRRcQMIF70QGH1JoHkIi9EuYIvSlHvFZoVcNozBuSIIf_g] . 
This device is in the Matter DCL with the following information:
Vendor ID: 4129 (0x1021)
Product ID: 5 (0x5)
Device Type ID: 256 (0x100)
Please review the profile assignment for this device.
The Partner has submitted ATS results for the WWST process.

New Device (Matter Switch) Legrand Radiant Smart Switch

---

drivers/Aqara/aqara-lock/src/init.lua
drivers/Aqara/aqara-lock/src/test/test_aqara_lock.lua

- [o] New feature
- [o] I have performed a self-review of my code

[Aqara] K100 - add supportedAlarmValues

---

tools/localizations/cn.csv

Add letianpai 1/2/3 switches and bulb Chinese name

Add letianpai 1/2/3 switches and bulb Chinese name

---

drivers/SmartThings/matter-lock/fingerprints.yml

- [  X ] WWST Certification Request
This PR is to add one fingerprint that will be certified by simularity, for a Matter Lock Device. The partner submitted this fingerprint (including the device label) on the SmartThings WWST Certification Console.
Here is reference to the device, in the Matter DCL
No other testing is currently planned. This PR will be merged, once approved. Thank you

New Device (Matter Lock) Level Bolt

---

drivers/SmartThings/matter-switch/fingerprints.yml

This PR is in support of a WWST FIngerprint only request, for the Innovation Matters Pushbutton Module device. According to the DCL, DCL the device is  15 (0xf)  
No further testing will be completed

New Device (Matter Switch) IM Pushbutton Module

---

drivers/SmartThings/matter-sensor/src/air-quality-sensor/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_air_quality_sensor.lua

Refactor the air quality sensor configure logic for readability and clarity.
Unit test added and old unit tests continue to pass. Tested with the VDA air quality sensor as well.

Matter Sensor: Streamline do_configure function in air quality sensor subdriver

---

drivers/SmartThings/matter-thermostat/src/init.lua

This _should_ be a pure refactor of the current doConfigure logic in the Matter Thermostat driver. Right now, lots of similar code is run in multiple places, and is confusing. Small changes have a greater capacity for error due to the multiple branches currently in use. This change aims to shrink all of this, without changing _any_ final profile configurations at all.

Update the doConfigure Logic in Matter Thermostat

---

drivers/SmartThings/sonos/src/init.lua

The intent of this is to reduce the size of the datastore for this driver.
Tested with the bose driver (since I dont have these devices)
* Confirmed datastore entry for the state_cache for each device is blown away
* Confirmed the state cache entries are not populated afterward

Remove state cache usage from sonos

---

drivers/SmartThings/sonos/src/types.lua

It seems that there are situations where a group update will contain data that does not map to cached data in the driver. This propagates as passing `nil` values to capability constructors, which in turn results in constraint violation errors during the pre-emit checks in the Lua Libs.
This PR does two things:
1. It adds additional logging around this path so we can gather information, as I cannot reproduce this on my setup.
2. It skips the event emit if any of the data isn't valid.
I've tested the change on my speakers and there are no regressions. I've also synthetically force things to be `nil` on this codepath, and it avoids a crash now. But I cannot reproduce the situation where this happens.

fix(sonos): Don't crash on group update w/ nil data

---

.github/workflows/run-tests.yml

Applying hotfix from https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1695
Will not result in a driver release as this does not change driver code.

hotfix(ci): luacov-cobertura dependency acquisition

---

drivers/Aqara/aqara-presence-sensor/src/discovery.lua
drivers/Aqara/aqara-presence-sensor/src/init.lua

fp2: Change in Credential Management Approach

---

drivers/Aqara/aqara-presence-sensor/src/lunchbox/rest.lua

alternative source for aqara fp2

---

drivers/SmartThings/zigbee-thermostat/src/init.lua
drivers/SmartThings/zigbee-thermostat/src/test/test_zigbee_thermostat.lua

Dynamically set heat and cool min/max setpoints for ZigBee thermostats by requesting the values from the device.

Chad 12671

---

drivers/SmartThings/zigbee-window-treatment/src/aqara/roller-shade/init.lua
drivers/SmartThings/zigbee-window-treatment/src/test/test_zigbee_window_treatment_aqara_roller_shade_rotate.lua

[Aqara RollerShade] Fix visibility of rotateState when idle

---

drivers/SmartThings/zigbee-presence-sensor/src/aqara/init.lua
drivers/SmartThings/zigbee-presence-sensor/src/test/test_aqara_presence_sensor_fp1.lua

fix possible operation failure issue in case of re-onboarding scenario

STSE-2610 Aqara presence sensor FP1: fix possible re-onboarding issue

---

drivers/Aqara/aqara-presence-sensor/src/lunchbox/rest.lua

- [] I have commented my code in hard-to-understand areas

fp2: use old lunchbox/rest.lua

---

drivers/Aqara/aqara-presence-sensor/src/lunchbox/rest.lua

Hotfix Aqara FP2 fixes to Beta

---

drivers/Aqara/aqara-presence-sensor/src/discovery.lua
drivers/Aqara/aqara-presence-sensor/src/init.lua
drivers/Aqara/aqara-presence-sensor/src/lunchbox/rest.lua

Expedite the following PR's to Production:
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1685
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1656
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1711

Expedite Assorted Aqara FP2 Fixes

---

drivers/SmartThings/matter-switch/fingerprints.yml

New Fingerprint addition for a WWST Request. The device is certified in the Matter DCL as the Matter Device type of "x10D".  The device is a Cync Reveal Full Color BR30
vendorId: 0x1339
productId: 0x006C
deviceProfileName: light-color-level-2000K-7000K
CxS - No further testing is planned

New Device (Matter Switch) Cync BR30

---

drivers/SmartThings/zigbee-lock/fingerprints.yml

Add Totem Q30/R50/R71/G30/N60

---

drivers/SmartThings/zigbee-lock/fingerprints.yml

Add fingerprints ahead of production release.

Expedite fingerprints to beta

---

drivers/SmartThings/zigbee-lock/fingerprints.yml
drivers/SmartThings/zigbee-thermostat/src/popp/init.lua
drivers/SmartThings/zigbee-thermostat/src/test/test_popp_thermostat.lua

rolling main up to beta

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding one Linkind , and also multiple new Matter devices from Ledvance
This is a WWST Certification request. After PR review, this PR will be ready to be merged and deployed.

New Devices (Matter Switch) Multiple Ledvance + Linkind

---

drivers/SmartThings/matter-lock/fingerprints.yml

Adding the fingerprint for the Nuki Smart Lock Ultra device
This PR can be merged after review.

New Device (Matter Lock) Nuki Smart Lock Ultra

---

drivers/SmartThings/matter-switch/fingerprints.yml

Add quotes around fingerprint id

Add quotes around fingerprint ID

---

drivers/SmartThings/matter-switch/profiles/light-level-2-button.yml

This change adds a new profile for the GE/Cync Dimmer/Keypad device.

Add profile for GE/Cync Dimmer/Keypad device

---

drivers/SmartThings/matter-switch/fingerprints.yml

New fingerprint addition for a new Matter Device, the Cync Paddle Dimmer. 
I was unable to verify this devices Matter Device Type in the DCL.

New Device (Matter Switch) Cync Paddle Dimmer

---

drivers/SmartThings/zigbee-lock/src/init.lua
drivers/SmartThings/zwave-lock/src/init.lua

CHAD-14232 clear codeState values in storage on driver restart

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua

When Cooling or Heating Setpoint is Fahrenheit, there is a problem that the value below the decimal point is not properly set.
You can refer to link below for more information.
https://smartthings.atlassian.net/browse/IOTE-4627

Fix abnormal rounding issue

---

drivers/SmartThings/zigbee-switch/src/aqara/init.lua
drivers/SmartThings/zigbee-switch/src/aqara/version/init.lua

[Aqara] Aqara switch "private mode" check

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/zwave-switch/src/multi-metering-switch/init.lua
drivers/SmartThings/zwave-switch/src/test/test_multi_metering_switch.lua
drivers/SmartThings/zwave-switch/src/test/test_shelly_multi_metering_switch.lua
drivers/SmartThings/zwave-switch/src/test/test_wyfy_touch.lua
drivers/SmartThings/zwave-switch/src/test/test_zwave_dual_switch.lua
drivers/SmartThings/zwave-switch/src/zwave-dual-switch/init.lua

Cherry pick the following PRs to Beta before the Beta to Prod Deploy
PR https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1726
PR: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1723
PR: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1752
PR: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1728

Attempt # 2 Cherry Pick to Beta before Production Release Nov 18

---

drivers/SmartThings/matter-switch/fingerprints.yml

This change is in support of a WWST Fingerprint addition for the U-Tec Smart Switch device. This was tested via the ATS.
According to the DCL this has a Matter Device Type ID of (0X10A) . 
PID: 0004
VID: 147F
ATS

New Device (Matter Switch) U Tech Smart Switch

---

.github/workflows/create-channel.yml
.github/workflows/duplicate-profiles-comment.yml
.github/workflows/publish-test-results.yml

See https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/security/dependabot/5

Update github dawidd6/action-download-artifact for security advisory

---

tools/localizations/cn.csv

Add Zemismart ZM25C multiple language support

---

drivers/SmartThings/matter-window-covering/fingerprints.yml

Add Zemismart ZM25C Curtain Motor

---

drivers/SmartThings/matter-window-covering/fingerprints.yml
tools/localizations/cn.csv

Cherry-pick WWST Matter window covering fingerprints in to Beta ahead of production

---

drivers/SmartThings/zigbee-lock/fingerprints.yml

Please review and thank you.
---
- Add fingerprints for TOTEM S50V
- Add fingerprints for TOTEM S93
- Add fingerprints for TOTEM W31V
- Sort fingerprints for TOTEM alphabetically
https://smartthings.atlassian.net/browse/PIOT-175
https://smartthings.atlassian.net/browse/PIOT-176
https://smartthings.atlassian.net/browse/PIOT-177
https://smartthings.atlassian.net/browse/WWSTCERT-4624
https://smartthings.atlassian.net/browse/WWSTCERT-4627
https://smartthings.atlassian.net/browse/WWSTCERT-4631

Add fingerprints for TOTEM S50V/S93/W31V and sort fingerprints for TOTEM alphabetically

---

drivers/Aqara/aqara-presence-sensor/src/fp2/api.lua

use deep copy for additional header
Register, delete, re-register, reconnect, and check status updates of three fp2s in Hub V3, Hub V2, SmartThings Stion, and Smart Monitor M5.

fp2: copy additional header

---

drivers/SmartThings/matter-window-covering/fingerprints.yml

Add Zemismart Zm02 Curtian Motor

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding two fingerprints for WWST: 
-  Aqara LED Bulb T2 CCT  ID " 4447/6146" has a Matter Device type in the DCL as (0x10C)
-  Aqara LED Bulb T2 RGB CCT id " 4447/6145" has a Matter Device type in the DCL as (0x10D)

New Devices (Matter Switch) Aqara Bulbs

---

drivers/SmartThings/zigbee-switch/src/preferences.lua
drivers/SmartThings/zwave-sensor/src/preferences.lua
drivers/SmartThings/zwave-smoke-alarm/src/init.lua

CHAD-12274 fixes occasional null pointer

---

tools/deploy.py
tools/localizations/cn.csv

Translation: make translation deploy tolerant of extra newlines

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding a device for a U-Tec Matter Bulb for a WWST Certification Request. The device is in the DCL with a Matter Device Type of (0x10D)

New Device (Matter Switch) U Tec Bulb

---

drivers/Aqara/aqara-lock/src/init.lua
drivers/Aqara/aqara-lock/src/test/test_aqara_lock.lua

[Aqara] add new feature to K100

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-switch/src/test/test_matter_multi_button_switch_mcd.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch_device_types.lua
drivers/SmartThings/zigbee-switch/src/test/test_all_capability_zigbee_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_led_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_light.lua
drivers/SmartThings/zigbee-switch/src/test/test_rgb_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_rgbw_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_zll_rgbw_bulb.lua
drivers/SmartThings/zwave-switch/src/test/test_fibaro_walli_double_switch.lua
drivers/SmartThings/zwave-switch/src/test/test_zooz_double_plug.lua

Expedite PR's #1804 and #1815 to Beta ahead of Production to skip Beta soak

Expedite Matter WWST PR's to Beta ahead of Production

---

drivers/SmartThings/matter-sensor/profiles/aqs-temp-humidity-tvoc-meas.yml
drivers/SmartThings/matter-sensor/src/air-quality-sensor/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_air_quality_sensor.lua
drivers/SmartThings/matter-switch/fingerprints.yml

19 December 2024: Expedite Main to Beta

---

drivers/SmartThings/matter-window-covering/fingerprints.yml
tools/localizations/cn.csv

modified cn.csv and fingerprints

---

drivers/SmartThings/matter-window-covering/fingerprints.yml
tools/localizations/cn.csv

Add device WISTAR WSERD30-B Smart Tubular Motor

Add device WISTAR WSERD30-B Smart Tubular Motor

---

drivers/SmartThings/matter-window-covering/fingerprints.yml
tools/localizations/cn.csv

Add devices WISTAR WSER50 Smart Tubular Motor

Add devices WISTAR WSER50 Smart Tubular Motor

---

drivers/SmartThings/matter-window-covering/fingerprints.yml

[Add devices WISTAR WSER40 Smart Tubular Motor](https://github.com/zhouchengyu-cell/SmartThingsEdgeDrivers/commit/e41522aa85173dc849c8a780020a41528a712758)

Add devices WISTAR WSER40 Smart Tubular Motor

---

.github/workflows/duplicate-profiles.yml
.github/workflows/run-tests.yml
.github/workflows/upload-driver-packages.yml

See this PR failing CI: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/12695239127/job/35386718873?pr=1857
It was mentioned in a comment from the [PR bumping this to v3](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1630) that the change from a few months ago was not future-proof: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1630/files#r1757174089 
Tested with the CI for [this PR](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/12697772988/job/35394807508?pr=1857)

Bump actions/upload-artifacts ocurrences from v3 to v4

---

drivers/SmartThings/matter-switch/fingerprints.yml

A fingerprint in matter-switch is misaligned by one space, causing formatting to fail.

Fix minor fingerprint formatting issue

---

drivers/SmartThings/jbl/profiles/jbl.yml
drivers/SmartThings/jbl/src/init.lua
drivers/SmartThings/jbl/src/jbl/api.lua
drivers/SmartThings/jbl/src/jbl/capability_handler.lua
drivers/SmartThings/jbl/src/jbl/device_manager.lua

…(#1797)"
This reverts commit 3743756985a908b5931856e34e2842337f2b9e55

Revert (JBL) Pr 1797

---

drivers/SmartThings/matter-switch/fingerprints.yml

This was also needed in prod today

Fix minor fingerprint formatting issue (#1859)

---

tools/localizations/cn.csv

Heiman Smoke Senor
Heiman CO Sensor
smart co sensor
Signed-off-by: cao wei <cw208096zn@163.com>

Add HEIMAN sensor multiple language supprot

---

drivers/SmartThings/matter-sensor/profiles/aqs-temp-humidity-co2-pm1-pm25-pm10-meas.yml
drivers/SmartThings/matter-sensor/src/air-quality-sensor/init.lua
drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_light_switch_h2.lua
drivers/SmartThings/matter-switch/src/test/test_electrical_sensor.lua

Expedite the following changes to beta to skip soak:
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1478
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1895
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1902

2025 February 03 Expedite to Beta ahead of Production

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding a new fingerprint for an Eve Light Switch device. 
Pid: 0x079
Vid: 0x130A
Matter Device Type ID according to the DCL: 257 (0x101)

New Device (Matter Switch) Eve Dimmer

---

drivers/SmartThings/matter-sensor/src/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_freeze_leak_sensor.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_rain_sensor.lua
drivers/SmartThings/matter-switch/src/init.lua

This is cherry picking the commits from #1925 and #1919.

hotfix matter sensor persistence and matter switch crash

---

drivers/SmartThings/matter-sensor/src/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_freeze_leak_sensor.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_rain_sensor.lua
drivers/SmartThings/matter-switch/src/init.lua

This is cherry picking the commits from https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1925 and https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1919, which were previously cherry-picked to beta in https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1932.

 production hotfix for matter sensor persistence and matter switch crash

---

drivers/SmartThings/matter-switch/src/init.lua

Logic for devices with temperature/humidity endpoints should be gated by specific vid/pid rather than the presense of these endpoints. This is to prevent other devices that may contain the endpoints from being affected unintentionally.
These changes only impact one specific vid/pid and are verified by existing test cases.

Matter Switch: fix temp/humidity handling

---

drivers/SmartThings/matter-switch/fingerprints.yml
tools/localizations/cn.csv

add fingerprint and cn.csv
Signed-off-by: cao wei <cw208096zn@163.com>

Add deviceZemismart M6 Hub

---

drivers/SmartThings/matter-sensor/fingerprints.yml
tools/localizations/cn.csv

add fingerprint and cn.csv
Signed-off-by: cao wei <cw208096zn@163.com>

Add Siterwell Smart Carbon Monoxide Alarm

---

drivers/SmartThings/matter-sensor/fingerprints.yml
tools/localizations/cn.csv

add Siterwell Door Window Sensor fingerprint and cn.csv
Signed-off-by: cao wei <cw208096zn@163.com>

Add Siterwell device:Door Window Sensor

---

drivers/SmartThings/hub/fingerprints.yml
drivers/SmartThings/hub/profiles/cooktop-hub.yml
drivers/SmartThings/hub/profiles/washer-dryer-hub.yml
drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-thermostat/fingerprints.yml
tools/localizations/cn.csv

This PR is to cherry pick to Beta.
I have reviewed the code:
- To make sure I grabbed all the commits for the related PRs approved
- Checked for errors after having to resolve a lot of conflicts
After this PR, I will compare Beta to Production and release to production. Then I will roll up Main to Beta.

Feb 19 Release: Adding PRs to Beta, before Production deploy

---

tools/localizations/cn.csv

I noticed that there was a duplicate line in the Beta branch for the Zemismart M6 Hub, so I am wanting to commit this to Beta before I continue on with todays deploy. 
I confirmed here that here [https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/beta/drivers/SmartThings/matter-switch/fingerprints.yml](url)  is no duplicate fingerprint for the device, just the translation file.

Fix Up (CN Translation File) Beta Only

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/profiles/switch-smart-bath-heater-laisiao.yml
drivers/SmartThings/zigbee-switch/src/init.lua
drivers/SmartThings/zigbee-switch/src/laisiao/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_laisiao_bath_heather.lua
tools/localizations/cn.csv

add laisiao bathroom heater

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding a new fingerprint for a WWST Submission for the Lifx Luna Device
VID: 0x1423
PID: 0x00DB

New Device (Matter Switch) Lifx Luna

---

drivers/SmartThings/matter-sensor/fingerprints.yml
tools/localizations/cn.csv

Adding a new fingerprint for a CN WWST Request that has completed testing
Smoke Alarm
vendorId: 0x1280
productId: 0x8014
Siterwell Motion Sensor
vendorId: 0x1280
productId: 0x0350

New Device (Matter Sensor) Siterwell Smoke Alarm CN and Motion Sensor

---

drivers/SmartThings/zigbee-humidity-sensor/fingerprints.yml
tools/localizations/cn.csv

add ThirdReality Smart Soil Moisture Sensor

---

drivers/SmartThings/matter-switch/profiles/light-level-power-energy-powerConsumption.yml
drivers/SmartThings/matter-switch/src/init.lua

- 1 Button, 1 Channel (PID=0x100A)
- 3 Buttons, 1 Channel (PID=0x1006)
Add Aqara Dimmer Switch H2 models
- Check normal operation through test for existing model
- Check the operation with a new device

Add Aqara Dimmer Switch H2 models

---

tools/localizations/cn.csv

Delete device:LeTianPai smart switch translations

---

drivers/SmartThings/matter-window-covering/fingerprints.yml
drivers/SmartThings/zigbee-humidity-sensor/fingerprints.yml
drivers/SmartThings/zigbee-lock/fingerprints.yml
tools/localizations/cn.csv

Beta hotfix/multiple wwst fingerprints

---

drivers/SmartThings/matter-thermostat/profiles/heat-pump-thermostat-humidity-thermostat-humidity.yml
drivers/SmartThings/matter-thermostat/profiles/heat-pump-thermostat-humidity-thermostat.yml
drivers/SmartThings/matter-thermostat/profiles/heat-pump-thermostat-humidity.yml
drivers/SmartThings/matter-thermostat/profiles/heat-pump-thermostat-thermostat-humidity.yml
drivers/SmartThings/matter-thermostat/profiles/heat-pump-thermostat-thermostat.yml
drivers/SmartThings/matter-thermostat/profiles/heat-pump-thermostat.yml
drivers/SmartThings/matter-thermostat/profiles/heat-pump.yml

Update category to Heat Pump for heat pump device type
https://smartthings.atlassian.net/browse/IOTE-4987

Feature(matter-thermostat): Update category for heat pump

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-switch/fingerprints.yml

WWST Cert
Originally these fingerprints were part of https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1905/files#diff-d421b34194f8b655303df53e5d9d5d991a51cef4fb3882b9f9858aae830074b7 however the three devices in this PR were removed from there becuase they are ready to be released to production. This PR will be for the three devices below that are ready for release.

New Devices (Matter Sensor + Matter Switch) 3 LG

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-thermostat/fingerprints.yml

Adding a new Matter Thermostat device for 3 Tado device called the
Smart Radiator Thermostat X
Vid: 0x134E
PID: 0x0001
Smart Thermostat X
vendorId: 0x134E
productId: 0x0002
Wireless Temperature Sensor X
vendorId: 0x134E
productId: 0x0006

New Device (Matter Thermo) Adding Tado devices

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-sensor/src/init.lua

Tado Wireless Temperature Sensor X (temperature-humidity)  not only needs a fingerprint #1996 but it requires to update this driver because it utilizes Thermostat.attributes.LocalTemperature

adds support for Thermostat/LocalTemperature

---

drivers/SmartThings/matter-switch/profiles/plug-level-energy-powerConsumption.yml
drivers/SmartThings/matter-switch/profiles/plug-level-power-energy-powerConsumption.yml
drivers/SmartThings/matter-switch/profiles/plug-level-power.yml
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_electrical_sensor.lua

This PR adds new profiles supporting the switchLevel capability for devices that support measuring power and energy.
Added new unit test.

Add new profiles for plugs with switchLevel, energy, power, and powerConsumption capabilities

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-sensor/src/init.lua
drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-thermostat/fingerprints.yml

Cherry-pick commits to beta ahead of production release.

Expedite changes to beta

---

drivers/SmartThings/matter-thermostat/fingerprints.yml

1. Fixed (2) typos where "themostat" was updated to be "thermostat" in the Matter Thermostat Generic Fingerprints
2. There was an invalid productID, so I updated that to follow standard hex notation

Fix Up (Matter Thermostat) 

---

drivers/SmartThings/matter-switch/profiles/light-color-level-fan.yml

This change adds a profile with components for a color light and a fan to support a future device configuration.

Add fan/light profile

---

drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-thermostat/fingerprints.yml

Expedite the following PR's to Beta to be included in the subsequent Production release:
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1873
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1888
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/2011

Expedite to Beta ahead of Production Release (Skip Beta Soak)

---

drivers/SmartThings/sonos/capabilities/softwareGeneration.yaml
drivers/SmartThings/sonos/profiles/sonos-player.yml
drivers/SmartThings/sonos/src/disco.lua
drivers/SmartThings/sonos/src/fields.lua
drivers/SmartThings/sonos/src/init.lua
drivers/SmartThings/sonos/src/types.lua

Expedite Sonos App Software Generation Reporting to Beta
Includes the following PR's:
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/2019

Expedite Sonos App Software Generation Reporting to Betaa

---

drivers/SmartThings/sonos/capabilities/softwareGeneration.yaml
drivers/SmartThings/sonos/profiles/sonos-player.yml
drivers/SmartThings/sonos/src/disco.lua
drivers/SmartThings/sonos/src/fields.lua
drivers/SmartThings/sonos/src/init.lua
drivers/SmartThings/sonos/src/types.lua

Expedite Sonos App Software Generation Reporting to Production
Includes the following PR's:
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/2019

Expedite Sonos App Software Generation Reporting to Prod

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding a fingerprint for one device, that is in the DCL
- id: 5264/6227
deviceLabel: Shelly Outdoor Plug S Gen3
vendorId: 0x1490
productId: 0x1853
deviceProfileName: plug-binary

New Device (Matter Switch) Shelly Outdoor Plug 5 Gen3

---

drivers/SmartThings/matter-sensor/fingerprints.yml

Adding a Fingerprint to the Matter Sensor Driver
VID: 0x102E
PID: 0x2010
Matter Device Type ID: 0x2c

New Device (Matter Sensor) LG Air Quality Sensor

---

drivers/SmartThings/matter-lock/fingerprints.yml

Adding a fingerprint per the WWST Process for a Level Door Lock.  VID: 0x129F
PID: 0x0004
This device is in the DCL. 
This device currently DOES NOT use the "New Matter Door Lock Experience".

New Device (Matter Lock) Level Lock Pro 0004

---

drivers/SmartThings/matter-lock/fingerprints.yml
drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/sonos/src/init.lua

Expedite Changes to Beta prior to production release (2025-03-31)

Expedite Changes to Beta for 2025-03-31 release

---

drivers/SmartThings/philips-hue/src/lunchbox/sse/eventsource.lua
drivers/SmartThings/philips-hue/src/utils/init.lua

philips-hue: Re-set socket timeout on sockets after ssl wrap

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding a new fingerprint for GE Cync 
vid: 0x1339
pid: 0x00B6

New Device (Matter Switch) Cync Full Color A19 Clear Spiral

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding a fingerprint for WWST, this device was tested on the ATS. 
- id: 4129/6
deviceLabel: Radiant Smart LED Dimmer
vendorId: 0x1021
productId: 0x0006
deviceProfileName: switch-level

New Device (Matter Switch) Legrand Radiant Smart LED Dimmer

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding a fingerprint for the Aqara W100 Device seeking WWST Certification
vendorId: (0x115F)
productId: (0x2004)
Matter Device Type ID: (0x302)
https://csa-iot.org/csa_product/climate-sensor-w100/

New Device (Matter Switch) Aqara W100

---

drivers/SmartThings/matter-lock/src/new-matter-lock/init.lua

Add Nuki's products to new-matter-lock driver
https://smartthings.atlassian.net/browse/WWST-9511?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

Add Nuki's products to new-matter-lock driver

---

drivers/SmartThings/zigbee-window-treatment/fingerprints.yml

Adding a new Zigbee Window Treatment device for WWST Certification, the Shade Revolution Indoor Shade Motor

New Device (Zigbee Window Treatment) Shade Revolution

---

drivers/SmartThings/matter-lock/src/new-matter-lock/init.lua

https://smartthings.atlassian.net/browse/STSE-3804

Add Yale Linus Smart Lock L2 to new-matter-lock driver

---

drivers/SmartThings/matter-thermostat/fingerprints.yml

Adding a fingerprint for a Bosch Device
VID: 0x1209
PID: 0x3012
Matter Device Type ID: 0x301

New Device (Matter Thermostat) Bosch Radiator Thermostat II [+M]

---

drivers/SmartThings/matter-switch/fingerprints.yml

Device Fingerprint Merge 51801d92 for MATTER FLEX RGBTW EU

---

drivers/SmartThings/matter-switch/fingerprints.yml

Device Fingerprint Merge 3767deb8 for LEDVANCE MATTER PLUG CH

---

drivers/SmartThings/matter-switch/fingerprints.yml

Device Fingerprint Merge 45c4be77 for MATTER COMP OUT PLUG EU

---

drivers/SmartThings/matter-switch/fingerprints.yml

Device Fingerprint Merge 15835d03 for MATTER PLUG EU BK

---

drivers/SmartThings/matter-switch/fingerprints.yml

Device Fingerprint Merge af8f2197 for Matter Push button 2-gang

---

drivers/SmartThings/matter-switch/fingerprints.yml

Reverts SmartThingsCommunity/SmartThingsEdgeDrivers#2066

Revert "Device Fingerprint Merge af8f2197 for Matter Push button 2-gang"

---

drivers/SmartThings/zwave-switch/fingerprints.yml

Adding fingerprint for WWST CxS request

New Device (Z-Wave Switch) Shelly Wave Plug S

---

drivers/SmartThings/matter-lock/fingerprints.yml
drivers/SmartThings/matter-lock/src/new-matter-lock/init.lua

https://smartthings.atlassian.net/browse/STSE-3818

[STSE-3818] Feature(matter-lock) Add eufy lock products to new-matter-lock driver

---

drivers/SmartThings/matter-sensor/fingerprints.yml

Adding fingerprint for WWST request. Originally this fingerprint was requested in a separate PR but that needed to be separated so I am making this new PR.

New Device (Matter Sensor) LG Motion Sensor 2030

---

drivers/SmartThings/zwave-button/fingerprints.yml
drivers/SmartThings/zwave-button/src/configurations.lua
drivers/SmartThings/zwave-button/src/zwave-multi-button/init.lua
drivers/SmartThings/zwave-button/src/zwave-multi-button/shelly_wave_i4/init.lua

- [x ] New feature
- [ x] I have performed a self-review of my code
- [ x] I have commented my code in hard-to-understand areas
- [ x] I have verified my changes by testing with a device or have communicated a plan for testing
- [ x] I am adding new behavior, such as adding a sub-driver, and have added and run new unit tests to cover the new behavior

Add shelly wave i4 driver

---

drivers/SmartThings/matter-sensor/profiles/co-comeas-colevel-battery.yml
drivers/SmartThings/matter-sensor/src/smoke-co-alarm/init.lua

Add new profile to fit a newly found use case.

Add co-comeas-colevel-battery profile

---

drivers/SmartThings/matter-lock/fingerprints.yml
drivers/SmartThings/matter-switch/fingerprints.yml

Expedite New Matter Fingerprints to Beta ahead of Production Rollup.
Brings in the following PR's:
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/2033
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/2115
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/2117

2025-05-12 Expedite Matter Fingerprints to Beta

---

drivers/SmartThings/matter-switch/fingerprints.yml

WWSTCERT-6271 Cync Button Switch with Traveler
WWSTCERT-6274 Cync Paddle Switch with Traveler
WWSTCERT-6277 Cycn Toggle Switch with Traveler

WWSTCERT-6271 WWSTCERT-6274 WWSTCERT-6271 Cync switches

---

drivers/SmartThings/zigbee-button/fingerprints.yml
drivers/SmartThings/zigbee-button/src/ezviz/init.lua
drivers/SmartThings/zigbee-button/src/init.lua
drivers/SmartThings/zigbee-button/src/test/test_ewelink_button.lua
drivers/SmartThings/zigbee-button/src/test/test_ezviz_button.lua

Add generic fingerprint in Zigbee_button driver for supporting Ezviz button

Support for EZVIZ button

---

drivers/SmartThings/matter-switch/fingerprints.yml

WWSTCERT-6302 Cync Button Dimmer w Traveler
WWSTCERT-6305 Cync Motion Dimmer w Traveler

WWSTCERT-6302/WWSTCERT-6305 Cync dimmers

---

tools/localizations/cn.csv

Add translations in `cn.csv` for the product `NL 72`, which was certificated in Global area before, to go through CN WWST.

[WWSTCERT-6173] Add translations for Nanoleaf NL72

---

drivers/SmartThings/matter-sensor/src/test/test_matter_bosch_button_contact.lua

Adding unit tests for Bosch Button Contact device

---

drivers/SmartThings/zigbee-switch/src/aqara/init.lua

SRC-G raised a PLM about product `Aqara Smart Wall Switch T1 (With Neutral, Single Rocker)`, which have redundant conditions in ST routine.
Refer to line 164, I managed to fix this by sending event to attribute `supportedButtonValues` of capability `button`. I tested this product and everything went well.
Please check and thank you.

[PLM P250519-03276] Fix issues

---

drivers/SmartThings/matter-lock/src/new-matter-lock/init.lua
drivers/SmartThings/matter-lock/src/test/test_new_matter_lock.lua

matter-lock: Update weekdays -> weekDays

Cherry pick test fixes to beta

---

drivers/SmartThings/sonos/src/api/sonos_connection.lua
drivers/SmartThings/sonos/src/api/sonos_ssdp_discovery.lua
drivers/SmartThings/sonos/src/lifecycle_handlers.lua
drivers/SmartThings/sonos/src/sonos_driver.lua
drivers/SmartThings/sonos/src/sonos_state.lua
drivers/SmartThings/sonos/src/types.lua
drivers/SmartThings/sonos/src/utils.lua

This PR fixes two main issues:
1. There were downstream bugs that were hidden by a previous fix related to an unbounded queue growing; in fixing that, we surfaced another bug that was unintentionally relying on the buggy behavior.
2. There were a few bugs related to speaker groups that were left over from the original refactor, related to devices becoming joined or separated in specific ways, that were surfaced during regression testing of the other fix.
Tested on a real multi-speaker topology

fix: Address regressions around group controls and onboarding

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/aqara/init.lua
drivers/SmartThings/zigbee-switch/src/aqara/multi-switch/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_wall_switch.lua

…all switch (no neutral, single) has been fixed.

[Aqara]  Aqara wall switch (no neutral, single) - fix the button function configuration

---

drivers/SmartThings/matter-thermostat/profiles/thermostat-cooling-only-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-heating-only-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-nobattery.yml

Expedite the following PR to Beta:
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/2167

2025-06-09 Expedite to Beta

---

drivers/Aqara/aqara-lock/fingerprints.yml
drivers/Aqara/aqara-lock/src/init.lua

[Aqara] Smart Door Lock - L100 model added

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-sensor/profiles/motion-illuminance-temperature-humidity-battery.yml
drivers/SmartThings/matter-sensor/profiles/motion-illuminance-temperature-humidity-batteryLevel.yml

Add new profile and corresponding fingerprint.

Matter Sensor: Add motion-illuminance-temperature-humidity-battery profile and fingerprint

---

drivers/SmartThings/sonos/src/sonos_driver.lua

There were some slight changes made to the responses from the REST and WebSocket LAN APIs for Sonos App controlled speakers that were not backported to S1 Controller controlled speakers.
Some of the refactors made during the refactors to support OAuth added more stringnent response checking, but some of those checks were built around fields that aren't present in the API responses for S1 controlled speakers.
Borrowed an S1 compatible speaker from a friend over the weekend to test. Will be sent to internal QA for verification after we merge to Alpha.

fix: Fix Sonos S1 Controller API compatibility regression

---

drivers/SmartThings/philips-hue/src/utils/batched_command_utils.lua
drivers/SmartThings/philips-hue/src/utils/init.lua

Hot Fix as described here:
https://smartthings.atlassian.net/wiki/spaces/HUBPLT/pages/4014541676/Risk+Assessment+June+17+2025+-+Hot+Fix

Hot-Fix to Prod: philips-hue: Fix batched command handling for grandchildren devices

---

drivers/SmartThings/matter-sensor/src/air-quality-sensor/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_air_quality_sensor.lua

Include supported modes support for aqs health concern capabilities

---

drivers/SmartThings/hub/fingerprints.yml
drivers/SmartThings/hub/profiles/v4-hub.yml
drivers/SmartThings/matter-lock/profiles/lock-user-schedule-unlatch.yml
drivers/SmartThings/matter-lock/profiles/lock-user-unlatch.yml
drivers/SmartThings/matter-lock/src/lock_utils.lua
drivers/SmartThings/matter-lock/src/new-matter-lock/init.lua
drivers/SmartThings/matter-lock/src/test/test_new_matter_lock.lua
drivers/SmartThings/matter-switch/fingerprints.yml

Beta hotfix/multiple hotfixes

---

drivers/SmartThings/matter-lock/src/new-matter-lock/init.lua

https://smartthings.atlassian.net/wiki/spaces/DLT/pages/3903553957/Aqara+U200+Lite+testing

Add Aqara U200 Lite to new-matter-lock driver

---

drivers/SmartThings/sonos/src/api/sonos_connection.lua
drivers/SmartThings/sonos/src/api/sonos_ssdp_discovery.lua
drivers/SmartThings/sonos/src/lifecycle_handlers.lua
drivers/SmartThings/sonos/src/sonos_driver.lua
drivers/SmartThings/sonos/src/sonos_state.lua
drivers/SmartThings/sonos/src/ssdp.lua
drivers/SmartThings/sonos/src/utils.lua

Hotfix to apply changes made in https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/2213.

Hotfix Sonos Crash Fixes to Production

---

drivers/SmartThings/sonos/src/sonos_driver.lua
drivers/SmartThings/zigbee-button/src/st/zigbee/zdo/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/st/zigbee/zdo/init.lua

Hotfix #2220 and #2218 to production

Prod hotfix

---

drivers/SmartThings/zigbee-bed/capabilities/aiMode.yaml
drivers/SmartThings/zigbee-bed/capabilities/autoInflation.yaml
drivers/SmartThings/zigbee-bed/capabilities/leftControl.yaml
drivers/SmartThings/zigbee-bed/capabilities/mattressHardness.yaml
drivers/SmartThings/zigbee-bed/capabilities/rightControl.yaml
drivers/SmartThings/zigbee-bed/capabilities/strongExpMode.yaml
drivers/SmartThings/zigbee-bed/capabilities/yoga.yaml
drivers/SmartThings/zigbee-bed/config.yml
drivers/SmartThings/zigbee-bed/fingerprints.yml
drivers/SmartThings/zigbee-bed/profiles/shus-smart-mattress.yml
drivers/SmartThings/zigbee-bed/src/init.lua
drivers/SmartThings/zigbee-bed/src/shus-mattress/custom_capabilities.lua
drivers/SmartThings/zigbee-bed/src/shus-mattress/custom_clusters.lua
drivers/SmartThings/zigbee-bed/src/shus-mattress/init.lua
drivers/SmartThings/zigbee-bed/src/test/test_shus_mattress.lua
tools/localizations/cn.csv

This reverts commit e298ca23b79bdace0b0b64b2b5644c1593301427.

Revert "Revert "add zigbee-bed shus mattress device""

---

drivers/SmartThings/matter-switch/fingerprints.yml

WWSTCERT-6937 Shelly 2L Gen3
WWSTCERT-6940 Shelly 1 Mini Gen3

WWSTCERT-6934 Shelly 1L Gen3

---

drivers/SmartThings/zigbee-lock/src/init.lua

This did not prevent any codes from not being scanned, but it did prevent the scan complete event from being emitted. This also moves the default handlers into the driver itself. We encountered one user who didn't seem to have the defaults registered, and despite us not being able to reproduce or find a bug, this seems like it fixes the issue for that user.

Off by 1 error prevents code scan complete event

---

drivers/SmartThings/zigbee-switch/fingerprints.yml

WWSTCERT-6783 SONOFF Zigbee Smart Wall Switch
WWSTCERT-6787 SONOFF Zigbee Smart Wall Switch

WWSTCERT-6779 SONOFF Zigbee Smart Wall Switch

---

drivers/SmartThings/matter-switch/fingerprints.yml

WWSTCERT-7070 Zemismart WiFi Smart Switch
WWSTCERT-7073 Zemismart WiFi Smart Switch

WWSTCERT-7067 Zemismart WiFi Smart Switch

---

tools/localizations/cn.csv

Add the cn.csv of the two ThirdReality devices

---

drivers/SmartThings/matter-window-covering/fingerprints.yml

WWSTCERT-6604
WWSTCERT-6607
WWSTCERT-6610
WWSTCERT-6613
WWSTCERT-6616
WWSTCERT-6619
WWSTCERT-6622

Smart Window Covering Series

---

drivers/SmartThings/matter-thermostat/profiles/air-purifier-modular.yml

Tested by partner to confirm that capability shows up correctly.

Add fineDustSensor as optional capability for air purifiers

---

drivers/SmartThings/zigbee-lock/fingerprints.yml

Add fingerprints according to Cbs WWST certification process.
[WWSTCERT-7367](https://smartthings.atlassian.net/browse/WWSTCERT-7367)
[PIOT-245](https://smartthings.atlassian.net/browse/PIOT-245)
[WWSTCERT-7367]: https://smartthings.atlassian.net/browse/WWSTCERT-7367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIOT-245]: https://smartthings.atlassian.net/browse/PIOT-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WWSTCERT-7367] Add fingerprints for Totem door lock S90

---

drivers/SmartThings/matter-switch/profiles/light-level-power-energy-powerConsumption.yml
drivers/SmartThings/matter-switch/profiles/light-power-energy-powerConsumption.yml
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_climate_sensor_w100.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_light_switch_h2.lua
drivers/SmartThings/matter-switch/src/test/test_electrical_sensor.lua
drivers/SmartThings/matter-switch/src/test/test_matter_button.lua
drivers/SmartThings/matter-switch/src/test/test_matter_light_fan.lua
drivers/SmartThings/matter-switch/src/test/test_matter_multi_button.lua
drivers/SmartThings/matter-switch/src/test/test_matter_multi_button_switch_mcd.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch_device_types.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_lights.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_plugs.lua

Hot fix changes from https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/2320

Beta hotfix matter switch energy changes

---

drivers/SmartThings/matter-switch/fingerprints.yml
tools/localizations/cn.csv

WWSTCERT-7463 Add device:Zemismart M1 hub

---

drivers/SmartThings/matter-window-covering/fingerprints.yml
tools/localizations/cn.csv

Add devices:Wistar Smart Tubular Motor

---

drivers/SmartThings/matter-switch/profiles/9-button-battery.yml
drivers/SmartThings/matter-switch/profiles/9-button-batteryLevel.yml
drivers/SmartThings/matter-switch/profiles/9-button.yml
drivers/SmartThings/matter-switch/src/init.lua

https://smartthings.atlassian.net/browse/CHAD-16315
Tested with a physical device with 9 Generic Switch endpoints

matter-switch: Add profile for 9-button device

---

drivers/SmartThings/zigbee-motion-sensor/fingerprints.yml
drivers/SmartThings/zigbee-motion-sensor/profiles/frient-motion-temp-illuminance-battery.yml
drivers/SmartThings/zigbee-motion-sensor/src/frient/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_frient_motion_sensor2_pet.lua

Frient motion sensor2 pet moszb 153 add support

---

drivers/SmartThings/zigbee-window-treatment/fingerprints.yml

Hanssem requested to update the deviceLabel of it's the window treatment

STSE-3979 Hanssem: Update deviceLabel

---

drivers/Aqara/aqara-lock/profiles/aqara-lock-battery.yml
drivers/Aqara/aqara-lock/src/init.lua
drivers/Aqara/aqara-lock/src/test/test_aqara_lock.lua

[Aqara] Add BatteryLevel Capability to K100
