CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

cla-assistant is now configured to ensure contributors have
agreed to the CLA before contributions will be accepted.

Add Contributing Guidelines and Code of Conduct

---

drivers/SmartThings/zwave-mouse-trap/profiles/pest-control-battery.yml

The profile was using the ContactSensor category but GenericSensor is more appropriate since this device doesn't have a contact sensor and there isn't a more specific category available for a device like this.
https://smartthings.atlassian.net/browse/CHAD-8638

Z-Wave Mouse Trap: Fix icon by changing category to GenericSensor

---

drivers/SmartThings/zwave-sensor/src/ezmultipli-multipurpose-sensor/init.lua
drivers/SmartThings/zwave-sensor/src/init.lua
drivers/SmartThings/zwave-sensor/src/test/test_ezmultipli_multipurpose_sensor.lua

Add code handles color contorl in a non-standard way.
- add ezmultipli_multipurpose_sensor sub driver
- add basic_report_handler in the sub driver
- add set_color in the sub driver
ticket
https://smartthings.atlassian.net/browse/CHAD-5945

EZMultipli: Add handling for non-standard color control

---

drivers/SmartThings/zwave-electric-meter/profiles/base-electric-meter.yml

Aeon Energy Meter capabilities should be ordered as they were with the DTH

HCS-2892 Change order of capabilities

---

drivers/SmartThings/zigbee-button/profiles/iris-one-button-battery.yml
drivers/SmartThings/zigbee-button/profiles/one-button-battery.yml
drivers/SmartThings/zigbee-button/profiles/one-button-temp-battery.yml
drivers/SmartThings/zigbee-button/src/init.lua
drivers/SmartThings/zigbee-button/src/test/test_zigbee_button.lua

Default presentation uses the first capability listed for the dashboard status and a couple profiles in this driver listed battery first, thus showing battery percentage rather than button status. This fixes the problem by listing button first in the capabilities and adding an emit_event to the added_handler.
https://smartthings.atlassian.net/browse/CHAD-8645

Chad 8645 zigbee-button: Make button status visible in dashboard

---

drivers/SmartThings/zigbee-button/profiles/one-button-temp-battery.yml

The default icon for the RemoteController category is different than the icon the SmartThings button uses when using a DTH. The new Button category will be mapped to the same icon that device uses when backed by a DTH.
https://smartthings.atlassian.net/browse/CHAD-8642

zigbee-button: Change category (and icon) for SmartThings button

---

drivers/SmartThings/zwave-sensor/fingerprints.yml
drivers/SmartThings/zwave-sensor/profiles/aeotec-temp-humidity-dew-mold.yml

CHAD-8725 - new device profile for Aeotec aerQ sensors
@SmartThingsCommunity/srpol-pe-team @greens

CHAD-8725 - adds a new device profile for Aeotec aerQ sensors

---

drivers/SmartThings/zigbee-contact/profiles/contact-battery-temperature.yml

CHAD-8847 - adds tempOffset to the device profile

CHAD-8847 - adds tempOffset to the device profile

---

drivers/SmartThings/zwave-thermostat/fingerprints.yml

Bugfix HCS-2753: Added '000B' as fingerprint to zwave-thermostat

HCS-2753: Added '000B' as fingerprint to zwave-thermostat

---

.github/workflows/create-channel.yml
.github/workflows/publish-test-results.yml
.github/workflows/run-tests.yml

Test results could not be published from forks. This uses artifact uploads to enable that.

Enhancements to test-running

---

drivers/SmartThings/zigbee-power-meter/fingerprints.yml
drivers/SmartThings/zigbee-power-meter/profiles/power-meter-consumption-report.yml
drivers/SmartThings/zigbee-power-meter/src/ezex/init.lua
drivers/SmartThings/zigbee-power-meter/src/frient/init.lua
drivers/SmartThings/zigbee-power-meter/src/init.lua
drivers/SmartThings/zigbee-power-meter/src/shinasystems/init.lua
drivers/SmartThings/zigbee-power-meter/src/test/test_zigbee_power_meter_consumption_report.lua

[CHAD-8872](https://smartthings.atlassian.net/browse/CHAD-8872)
- Add specific vid for EZEX power meter to display in Energy plugin.
- Fix bug
[CHAD-8897](https://smartthings.atlassian.net/browse/CHAD-8897)
- Add missing fingerprints in [DTH](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zigbee-power-meter.src/zigbee-power-meter.groovy) and add sub-drivers for them.

CHAD-8872 - Add missing fingerprints in power-meter and vid for EZEX power meter

---

drivers/SmartThings/zigbee-illuminance-sensor/fingerprints.yml
drivers/SmartThings/zigbee-illuminance-sensor/profiles/battery-illuminance.yml
drivers/SmartThings/zigbee-illuminance-sensor/src/init.lua
drivers/SmartThings/zigbee-illuminance-sensor/src/test/test_illuminance_sensor.lua

Most zigbee illuminance sensors are battery powered sensors, so the driver should be updated to include that capability.
Adds unit tests for battery percentage report handling and configurations

Add battery-illuminance profile for default illuminance profile

---

drivers/SmartThings/zigbee-switch/src/test/test_zll_rgb_bulb.lua
drivers/SmartThings/zigbee-switch/src/zll-dimmer-bulb/ikea-xy-color-bulb/init.lua

The original code wasn't handling the setHue and setSaturation commands
correctly. The light would flash but not change to the desired color. To
fix the problem, a short timer is started when receiving either the setHue
or setSaturation commands instead of sending a command to the device right
away. The hue (or saturation) value is cached temporarily, and if the other
command is received before the timer expires then both the cached value and
the value from the second command are used to calculate the x/y and are sent
to the device. If only one of the two commands is sent before the timer
expires then the value from that command is combined with the latest known
color state to calculate the x/y.
https://smartthings.atlassian.net/browse/CHAD-8948

zigbee-switch: Fix color handling for Ikea RGB bulbs

---

drivers/SmartThings/zwave-switch/fingerprints.yml

Added fingerprint for Enerwave Dimmer Switch (ID: 011A/0102/0202). Ticket changes to CHAD-9079: https://smartthings.atlassian.net/browse/CHAD-9079?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

[HCS-2662] Added fingerprint for Enerwave Dimmer Switch (ID: 011A/0102/0202)

---

drivers/SmartThings/zwave-sensor/src/sensative-strip/init.lua
drivers/SmartThings/zwave-sensor/src/test/test_sensative_strip.lua

When migrating devices, only checking the device configuration on add would lead to sensative open/closed sensors continuing to display the water detection capability indefinitely. Now the driver will query the config on wakeup until it has received a report.

CHAD-8998 Re-check device configuration on WakeUp

---

drivers/SmartThings/zigbee-range-extender/fingerprints.yml

Hi,
we would like to add the Aeotec Range Extender 7 Zi fingerprint due it's already in the edge driver certification process.
(Please excuse the faulty pull requests before - there was a Github user mismatch on the windows Github client, so the user was not able to sign the CLA agreement)
Thank you in advance.
Regards,
zwave-mke

Add Aeotec Range Extender 7 Zi fingerprint

---

drivers/SmartThings/zigbee-presence-sensor/src/arrival-sensor-v1/init.lua
drivers/SmartThings/zigbee-presence-sensor/src/init.lua
drivers/SmartThings/zigbee-presence-sensor/src/presence_utils.lua
drivers/SmartThings/zigbee-presence-sensor/src/test/test_st_arrival_sensor_v1.lua
drivers/SmartThings/zigbee-presence-sensor/src/test/test_zigbee_presence_sensor.lua

This changes the logic to always start a presence timeout timer on device init.
This means that even if the device was in the offline state it will trigger a
not present event.

HCS-2732: Always start a presence timeout on init

---

drivers/SmartThings/zigbee-water-leak-sensor/fingerprints.yml

changed profile to one that includes tempOffset, fix for CHAD-9312
https://smartthings.atlassian.net/browse/CHAD-9312?focusedCommentId=1196390&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1196390

zigbee-water-leak-sensor: changed Nortek profile

---

drivers/SmartThings/zigbee-lock/src/init.lua
drivers/SmartThings/zigbee-lock/src/lock_utils.lua
drivers/SmartThings/zigbee-lock/src/samsungsds/init.lua
drivers/SmartThings/zigbee-lock/src/test/test_zigbee_lock_code_migration.lua
drivers/SmartThings/zwave-lock/src/init.lua
drivers/SmartThings/zwave-lock/src/test/test_zwave_lock_code_migration.lua

This allows us to use the lock codes synced as a part of the DTH->Edge migration to pre-populate our lock state to avoid extra events, and give us necessary context.

Add lock support for lock codes after migration from DTHs

---

drivers/SmartThings/zwave-window-treatment/profiles/iblinds-window-treatment-v3.yml
drivers/SmartThings/zwave-window-treatment/src/iblinds-window-treatment/init.lua
drivers/SmartThings/zwave-window-treatment/src/preferences.lua

Parameters 3, and 7-10 were missing from the driver, they have been added.

Add missing parameters to iblinds

---

drivers/SmartThings/zigbee-lock/src/lock_utils.lua
drivers/SmartThings/zigbee-lock/src/test/test_zigbee_lock_code_migration.lua
drivers/SmartThings/zwave-lock/src/init.lua
drivers/SmartThings/zwave-lock/src/test/test_zwave_lock_code_migration.lua

The data field for lock codes being used in migration is a string of encoded JSON not a JSON field itself.  So it must be decoded before use.
CHAD-9084
CHAD-8772

Expect lock code device data field to be string

---

drivers/SmartThings/zwave-button/src/test/test_zwave_multi_button.lua
drivers/SmartThings/zwave-button/src/zwave-multi-button/init.lua

Some remotes send two events when the button is held, one on the hold and one on the release. To maintain parity with DTHs this will be disabled for now

Do not emit unsupported button events

---

drivers/SmartThings/zwave-electric-meter/profiles/qubino-3-phase-meter.yml

Switched ordering of energy meter and power meter in qubino-3-phase profile to change join icon from energy consumption to power meter. 
https://smartthings.atlassian.net/browse/CHAD-9411?focusedCommentId=1205226&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1205226

CHAD-9411: Edited zwave electric meter profile

---

drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temp-battery.yml
drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temperature.yml

Changed temperatureMeasurement to be first in zigbee humidity sensor profiles (where applicable) so temperature is the default presentation. 
https://smartthings.atlassian.net/browse/BUG-6075

switched profile orders in zigbee humidity sensor

---

drivers/SmartThings/zigbee-button/src/zigbee-multi-button/ikea/init.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/somfy/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/ikea/init.lua

Properly fall back to group 0 only if no other binding table entries are found.

CHAD-9609 IKEA button zigbee group binding fix

---

drivers/SmartThings/zigbee-thermostat/src/test/test_zenwithin_thermostat.lua
drivers/SmartThings/zigbee-thermostat/src/zenwithin/init.lua

Hub v45 will have an updated temp conversion function that this driver should rely on. It uses 2 digits of precision.

CHAD-9577 Use util function for temp conversion

---

tools/run_driver_tests.py

See https://peps.python.org/pep-0394/#for-python-script-publishers. When running in a virtualenv, the actual "python3" executable is not at the fully qualified path.  Using "/usr/bin/env" is a best practice that allows virtualenv to work properly as per the PEP.

Use python shebang line that respsects virtualenvs

---

drivers/SmartThings/matter-sensor/fingerprints.yml

The fingerprinting logic can find the driver of the device by using the generic fingerprint instead of manufacturer specific fingerprint. For this reason, this change removes samsung fingerprints for matter-sensor.

Remove samsung fingerprints for matter-sensor

---

drivers/SmartThings/zigbee-valve/fingerprints.yml

Adds the fingerprint for the production model. I'm guessing the "TBD" fingerprint was literally that.

CHAD-9650 Waxman valve: add fingerprint

---

drivers/SmartThings/matter-switch/fingerprints.yml

The fingerprinting logic can find the driver of the device by using the generic fingerprint instead of manufacturer specific fingerprint. For this reason, this change removes samsung fingerprints for matter-switch.

Remove samsung fingerprints for matter-switch

---

drivers/SmartThings/zwave-switch/profiles/inovelli-dimmer-power-energy.yml
drivers/SmartThings/zwave-switch/profiles/inovelli-dimmer.yml
drivers/SmartThings/zwave-switch/src/inovelli-LED/init.lua
drivers/SmartThings/zwave-switch/src/inovelli-LED/inovelli-lzw31sn/init.lua
drivers/SmartThings/zwave-switch/src/test/test_inovelli_button.lua
drivers/SmartThings/zwave-switch/src/test/test_inovelli_dimmer.lua
drivers/SmartThings/zwave-switch/src/test/test_inovelli_dimmer_led.lua
drivers/SmartThings/zwave-switch/src/test/test_inovelli_dimmer_power_energy.lua

CHAD-9392 - changes in the Inovelli dimmer driver
- moves ledBar to separate component, 
- fixes unit tests

CHAD-9392 - Inovelli dimmers - moves ledBar to separate component, fixes unit tests

---

drivers/SmartThings/zwave-siren/profiles/alarm-switch.yml

[BUG-6167] Removed metadata from alarm-switch profile

---

drivers/SmartThings/zwave-switch/src/qubino-switches/qubino-relays/qubino-flush-2-relay/init.lua

Hi @greens in this PR, I've added just refreshing device after added lifecycle to avoid "Connected" status for child devices

Added refresh in added lifecycle for qubino flush relay 2

---

drivers/SmartThings/zigbee-lock/src/init.lua

When deleting a code, locks will respond to our getPIN request and also send a programming event. Both indicate that a code has been deleted, but only the first should generate an event.

HCS-2748 Duplicate lock deleted event

---

drivers/SmartThings/matter-lock/fingerprints.yml
drivers/SmartThings/matter-thermostat/fingerprints.yml
drivers/SmartThings/matter-window-covering/fingerprints.yml

The fingerprinting logic can find the driver of the device by using the generic fingerprint instead of manufacturer specific fingerprint. For this reason, this change removes samsung fingerprints for matter devices.

Remove samsung fingerprints for matter devices

---

drivers/SmartThings/bose/src/command.lua
drivers/SmartThings/zigbee-thermostat/src/sinope/init.lua
drivers/SmartThings/zwave-bulb/src/fibaro-rgbw-controller/init.lua
drivers/SmartThings/zwave-smoke-alarm/src/init.lua
drivers/SmartThings/zwave-switch/src/aeon-smart-strip/init.lua
drivers/SmartThings/zwave-switch/src/eaton-5-scene-keypad/init.lua
drivers/SmartThings/zwave-thermostat/src/fibaro-heat-controller/init.lua
drivers/SmartThings/zwave-thermostat/src/test/test_fibaro_heat_controller.lua
drivers/SmartThings/zwave-window-treatment/src/test/test_qubino_flush_shutter.lua
drivers/SmartThings/zwave-window-treatment/src/window-treatment-venetian/qubino-flush-shutter/init.lua

Ran `luacheck --std lua53 ./ | grep "accessing undefined variable"` against the repo and found some bugs. This PR doesn't fix all of the issues found, but the remainder will take a bit more time and I didn't want to wait to get these fixes in.

luacheck: Fix some of the "accessing undefined variable" bugs

---

drivers/SmartThings/matter-window-covering/src/init.lua

Removed handle refresh from matter window covering driver as it is not longer needed and to take care of a previous nil value.`if read_request = nil` in handle refresh function.

removed handle refresh from matter window covering

---

drivers/SmartThings/zwave-switch/src/inovelli-LED/inovelli-lzw31sn/init.lua
drivers/SmartThings/zwave-switch/src/test/test_inovelli_button.lua
drivers/SmartThings/zwave-switch/src/test/test_inovelli_dimmer_scenes.lua

fixes CHAD-9781, HCS-3775 
- removes unsupported button states from button1, button2, button3
- fixes in unit tests

fixes CHAD-9781, HCS-3775

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua

This hack was needed prior to matter release, but is no longer needed, since all hubs have the correct name in their lua libs now.

Remove require hack for previous matter SDK cluster attribute renames

---

drivers/SmartThings/zwave-virtual-momentary-switch/src/init.lua
drivers/SmartThings/zwave-virtual-momentary-switch/src/test/test_zwave_virtual_momentary_switch.lua

The on function in zwave virtual momentary contact immediately sent the off command after the on command without the three second delay.  The `momentary_switch_on` function was edited to include the 3 second delay. The issue was that the value of the `switch_off` function was being passed into the delay command not the actual function, so `switch_off` was called and then its return value was passed into the delay function, which was a `nil` value. Tests were also edited to test for 3 second delay.
https://smartthings.atlassian.net/browse/CHAD-9560

CHAD-9560: fixed on function in zwave virtual momentary contact

---

drivers/SmartThings/bose/src/listener.lua

This was discovered during some migration testing. However, there does appear to be a mobile app/plugin bug where these supportedTrackControlCommands never actually result in the app ui changing (I have confirmed the events leave the hub). I am still able to push next/prev and see the events come down to the driver.

Remove supportedTrackControlCommands when playing radio source

---

drivers/SmartThings/zigbee-button/src/init.lua
drivers/SmartThings/zigbee-button/src/test/test_ikea_remote_control.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/ikea/TRADFRI_remote_control.lua

Added read request in added handler for Ikea remote control in zigbee button driver. Will send a read `BatteryPercentageRemaining` upon the device being handled to fix initial nil battery status, also fixed tests. 
https://smartthings.atlassian.net/browse/BUG-6272

added read request for battery percent for ikea remote control

---

drivers/SmartThings/matter-lock/profiles/base-lock.yml
drivers/SmartThings/matter-lock/profiles/lock-without-codes.yml

The Lock Capability supports locked, unknown, unlocked, and unlocked with timeout. Matter cluster only ever maps to locked, unknown, and unlocked, so we should only have those states available in the devices capability to not mislead the user when setting automations based on state. 
This is an alternative to #308 that doesn't require managing metadata separately. 
@greens @bflorian I am currently unable to package this driver in prod, and am curious if the capability configuration feature has been released yet or not?

Matter-lock lock state configuration to exclude unsupported states

---

drivers/SmartThings/zigbee-thermostat/profiles/thermostat-battery-powerSource.yml
drivers/SmartThings/zigbee-valve/profiles/valve-battery-powerSource.yml
drivers/SmartThings/zwave-sensor/profiles/aeotec-multisensor-6.yml
drivers/SmartThings/zwave-sensor/profiles/aeotec-multisensor-7.yml
drivers/SmartThings/zwave-sensor/profiles/water-battery-powersource.yml

Updated all zigbee-valve profiles. All powerSources now only consist of battery and mains.

[CHAD-8804] zigbee-thermostat/zigbee-valve/zwave-sensor: Set correct possible options for power source

---

drivers/SmartThings/zigbee-illuminance-sensor/profiles/base-illuminance.yml
drivers/SmartThings/zigbee-illuminance-sensor/profiles/battery-illuminance.yml
drivers/SmartThings/zwave-sensor/profiles/aeotec-multisensor-6.yml
drivers/SmartThings/zwave-sensor/profiles/aeotec-multisensor-7.yml
drivers/SmartThings/zwave-sensor/profiles/fibaro-motion-sensor.yml
drivers/SmartThings/zwave-sensor/profiles/generic-sensor.yml
drivers/SmartThings/zwave-sensor/profiles/illuminance-battery.yml
drivers/SmartThings/zwave-sensor/profiles/illuminance-temperature.yml
drivers/SmartThings/zwave-sensor/profiles/motion-battery-illuminance-temperature-interval.yml
drivers/SmartThings/zwave-sensor/profiles/motion-battery-illuminance-temperature.yml
drivers/SmartThings/zwave-sensor/profiles/motion-battery-illuminance.yml
drivers/SmartThings/zwave-sensor/profiles/motion-battery-temperature-illuminance-humidity.yml
drivers/SmartThings/zwave-sensor/profiles/motion-switch-color-illuminance-temperature.yml
drivers/SmartThings/zwave-sensor/profiles/multi-functional-motion.yml
drivers/SmartThings/zwave-sensor/profiles/water-illuminance-temperature.yml

Updated Zwave-sensor file. All illuminance range has been configured to 0 - 32000 lux.

[CHAD-8781] zwave-sensor/zigbee-illuminance-sensor: Set correct range on illuminance measurement values

---

drivers/SmartThings/zwave-switch/src/inovelli-LED/inovelli-lzw31sn/init.lua
drivers/SmartThings/zwave-switch/src/test/test_inovelli_button.lua
drivers/SmartThings/zwave-switch/src/test/test_inovelli_dimmer_scenes.lua

CHAD-9693 - fixes mapping scenes to components
in a [DTH](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/78747fa5a3b42a0c801f1095f8f7521da968ba42/devicetypes/smartthings/inovelli-dimmer.src/inovelli-dimmer.groovy#L422):
- scene 2 is mapped to the button1 (UP)
- scene 1 is mapped to the button2 (DOWN)
- scene 3 is mapped to the button3 (CONFIGURE)

CHAD-9693 - fixes mapping scenes to components

---

drivers/SmartThings/zwave-thermostat/src/qubino-flush-thermostat/init.lua
drivers/SmartThings/zwave-thermostat/src/test/test_qubino_flush_thermostat.lua

**GPD-2090 - fix for changing thermostat mode**
- added missing commands to `do_refresh`
- `device_added` sends only `Configuration.Get`
- device is refreshed after handling `Configuration.REPORT` - because `CONFIGURED_MODE` field is already set here, so `ThermostatSetpoint:Get` is called with proper parameter in `do_refresh` later
- device reports `-999.9` if the digital temperature sensor is not connected to it so I added this constant: `DIGITAL_TEMPERATURE_SENSOR_NOT_CONNECTED = -999.9` and this value is not handled by defaults
- changes unit tests to because of fixes mentioned above

GPD-2090 - fix for changing thermostat mode

---

drivers/SmartThings/zigbee-switch/src/multi-switch-no-master/init.lua
drivers/SmartThings/zigbee-switch/src/zigbee-dual-metering-switch/init.lua
drivers/SmartThings/zwave-switch/src/fibaro-double-switch/init.lua
drivers/SmartThings/zwave-switch/src/multi-metering-switch/init.lua
drivers/SmartThings/zwave-switch/src/qubino-switches/qubino-relays/qubino-flush-2-relay/init.lua
drivers/SmartThings/zwave-switch/src/zooz-zen-30-dimmer-relay/init.lua
drivers/SmartThings/zwave-switch/src/zwave-dual-switch/init.lua

This mitigates a situation where when a device is switched from one driver to another, there is an Added event that creates duplicate children. Note this situation should be prevented by the ST platform, and will be fixed in a future release.

Add checks for child existence on device added events

---

drivers/SmartThings/zigbee-siren/fingerprints.yml
drivers/SmartThings/zigbee-siren/profiles/switch-alarm-generic-siren-7.yml
drivers/SmartThings/zwave-siren/fingerprints.yml
drivers/SmartThings/zwave-siren/profiles/aeon-siren.yml
drivers/SmartThings/zwave-siren/profiles/aeotec-doorbell-siren-battery.yml
drivers/SmartThings/zwave-siren/profiles/aeotec-doorbell-siren.yml
drivers/SmartThings/zwave-siren/profiles/alarm-battery.yml
drivers/SmartThings/zwave-siren/profiles/ecolink-wireless-siren.yml
drivers/SmartThings/zwave-siren/profiles/everspring-siren.yml
drivers/SmartThings/zwave-siren/profiles/multifunctional-siren.yml
drivers/SmartThings/zwave-siren/profiles/philio-sound-siren.yml
drivers/SmartThings/zwave-siren/profiles/yale-siren-tamper.yml
drivers/SmartThings/zwave-siren/profiles/yale-siren.yml

**CHAD-9317 - fixes zwave and zigbee sirens**
I updated following device profiles so they don't use generic or device specific UI metadata anymore:
- aeon-siren
- aeotec-doorbell-siren
- aeotec-doorbell-siren-battery
- alarm-battery
- alarm-battery-tamper
- ecolink-wireless-siren
- everspring-siren
- multifunctional-siren
- philio-sound-siren
- switch-alarm-generic-siren-7
- yale-siren
- yale-siren-tamper

CHAD-9317 - customized device profiles in zwave and zigbee sirens drivers

---

drivers/SmartThings/samsung-audio/src/disco.lua
drivers/SmartThings/wemo/src/discovery.lua
drivers/SmartThings/wemo/src/protocol.lua

I tried to onboard a few wemo devices, but the driver discovery crashed due to this require failing.

Bugfix require socket.ltn12 rather than ltn12 in wemo driver

---

drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2200K-4000K.yml
drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2200K-5000K.yml
drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2200K-6500K.yml
drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2500K-6000K.yml
drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2700K-5000K.yml
drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2700K-6500K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-1800K-6500K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-2000K-6500K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-2200K-4000K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-2200K-5000K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-2200K-6500K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-2500K-6000K.yml
drivers/SmartThings/zigbee-switch/profiles/rgbw-bulb-2700K-5000K.yml
drivers/SmartThings/zwave-switch/profiles/multichannel-switch-level.yml
drivers/SmartThings/zwave-switch/profiles/switch-level-indicator.yml
drivers/SmartThings/zwave-switch/profiles/zooz-zen-30-dimmer-relay-new.yml
drivers/SmartThings/zwave-switch/profiles/zooz-zen-30-dimmer-relay.yml

Some zwave/zigbee profiles have been added since https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/160, so this essentially extends that work to these new profiles. 
https://smartthings.atlassian.net/browse/CHAD-8941

Set switchLevel range to [1,100] for zwave/zigbee dimmers

---

drivers/SmartThings/zigbee-switch/src/aqara/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_smart_plug.lua

Edited
Before
- energyMeter.energy is "kWh"
- powerConsumptionReport.powerConsumption is "kWh"
After
- energyMeter.energy is "kWh"
- powerConsumptionReport.powerConsumption is "Wh"

[Aqara] Smart Plug : Updated unit for the powerConsumptionReport

---

drivers/SmartThings/bose/src/init.lua
drivers/SmartThings/bose/src/listener.lua

Handle a situation where we receive a now playing update over the websocket before having set supportedMediaPlaybackCommands due to device init/refresh. This can happen during migration.

Bose utilize get_latest_state

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_featuremap.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua

This implements setpoint limits for thermostats according to the spec. 
When the device is configured, the driver reads the min/max heat/cool setpoint limits and the min setpoint deadband limit attributes; these values are persisted on the device object. Note that we only consider the AbsX variety of  setpoint limit attributes (i.e. AbsMinHeatingSetpoint not MinHeatingSetpoint).
If a set point command has a value outside the min/max or deadband, we will log a warning with the relevant information and then emit a capability event with the current cached setpoint value. This will prevent a timeout error in the app, and will indicate to the user that the setpoint did not actually change.

Matter thermostat setpoint limits

---

drivers/SmartThings/zigbee-siren/profiles/switch-alarm-generic-siren-7.yml
drivers/SmartThings/zwave-siren/profiles/aeon-siren.yml
drivers/SmartThings/zwave-siren/profiles/aeotec-doorbell-siren-battery.yml
drivers/SmartThings/zwave-siren/profiles/aeotec-doorbell-siren.yml
drivers/SmartThings/zwave-siren/profiles/alarm-battery-tamper.yml
drivers/SmartThings/zwave-siren/profiles/alarm-battery.yml
drivers/SmartThings/zwave-siren/profiles/ecolink-wireless-siren.yml
drivers/SmartThings/zwave-siren/profiles/everspring-siren.yml
drivers/SmartThings/zwave-siren/profiles/multifunctional-siren.yml
drivers/SmartThings/zwave-siren/profiles/philio-sound-siren.yml
drivers/SmartThings/zwave-siren/profiles/yale-siren-tamper.yml
drivers/SmartThings/zwave-siren/profiles/yale-siren.yml

In yaml, the word 'off' can be treated as a keyword that is equivalent to boolean false. This causes an issue where the enabled value of 'off' is incorrectly translated to false.
This is specific to YAML 1.1, as described here:
https://yaml.org/type/bool.html

Fix yaml issue in siren embedded configs

---

drivers/SmartThings/matter-thermostat/src/init.lua

This is temporary until api v3 has been released to all hubs to allow for reading of the Thermostat cluster's AttributeList attribute to determine support for the ThermostatRunningState attribute which backs SmartThings ThermostatOperatingState capability, and is an optional attribute.
I have yet to encounter a matter thermostat that supports the optional attribute being used in this profile switching case.
#370 implements reading of the AttributeList

All matter thermostats are nostate profiles

---

drivers/SmartThings/bose/src/disco.lua
drivers/SmartThings/bose/src/handlers.lua
drivers/SmartThings/bose/src/init.lua
drivers/SmartThings/bose/src/listener.lua
drivers/SmartThings/bose/src/utils.lua

When devices are migrated, we must pull the serial number from the device data rather than the device_network_id (which is what devices joined via the driver use) because the DTH backed devices use MAC addresses for the dni, which are not available to edge driver devices.
This also fixes a bug with discovery on device init where when multiple devices are discovered at the same time, the last discovered device IP is used for all the websocket connections. This situation happens exclusively during migration

Fix migration discovery issue

---

.github/workflows/duplicate-profiles.yml

Update to version to 1.2.4 to avoid bug when dealing with files that are renamed in a PR.

Update file-changes-action version to 1.2.4

---

.github/scripts/check_duplicates.py
.github/workflows/duplicate-profiles.yml

Fix logic in duplicate profile checking script to account for profiles with multiple components. Previously, the script would indicate a duplicate if just one of the components in a profile matches another profile.
Also, refactored some of the logic for readability and brevity

Fix multi-component issues in duplicate profile check

---

drivers/SmartThings/wemo/src/discovery.lua

https://smartthings.atlassian.net/browse/CHAD-9941 => Fix for the ST (Search Target) field to handle edge migration (DTH -> LUA)

Modified Search Target in M-SEARCH Discovery

---

drivers/SmartThings/matter-lock/src/init.lua
drivers/SmartThings/matter-media/src/init.lua
drivers/SmartThings/matter-sensor/src/init.lua
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-window-covering/src/init.lua

This is needed for devices to have the correct provisioning state set with the default driver switch handler when devices switch drivers.

Add supported_capabilities field to matter driver templates

---

.github/scripts/check_duplicates.py

Fix an issue where profiles would be considered duplicates if one had a correct subset of capabilities of the other profile. Also, refactor some logic for readability.

Fix "subset duplicate" issue in profile duplicate script

---

drivers/SmartThings/philips-hue/profiles/white-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white-and-color-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white.yml
drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/init.lua

Hue has per-product dimming values, and it would be nice to accomodate those. But
there are two problems. The first is that Hue allows for fractional values,
the second is that the min-dimming is often < 1. The DTH simply treated all hue
devices as having a minimum dimming value of 1. So we do that here to maintain
behavior parity with the DTH.
We also update the profiles to have ranges on switch level.
Fixes: Chad-10099
Depends-On: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/475

fix: Fix behavior of dimmer capability at the bottom of the range

---

drivers/SmartThings/philips-hue/profiles/white-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white-and-color-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white.yml
drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/init.lua

The established behavior for a Hue bulb on our platform is to turn on if it's off
and it receives a dimming event. This fixes that regression.
Fixes: CHAD-10104
Depends-On: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/473

fix: Set bulbs on if off when handling switchLevel

---

drivers/SmartThings/philips-hue/profiles/white-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white-and-color-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white.yml
drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/init.lua

Some bridges won't use their MAC-based Bridge ID as the hostname when responding
to mDNS queries. We were relying on that functionality in our discovery loop so
we fix that by querying the bridge config info, which is an endpoint that does
not require auth and that has the MAC address as an explicitly reported field.
Fixes: CHAD-10160

fix: Perform explicit MAC lookup at discovery

---

drivers/SmartThings/philips-hue/profiles/white-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white-and-color-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white.yml
drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/init.lua

This PR addresses multiple reported issues from QA, internal testing, and beta testing.
- The first commit addresses coroutine safety on the REST API; If multiple capability commands arrived in quick enough succession, it could cause a crash because multiple callsites would be waiting for a response on the TCP socket at the same time, leading to `select`ing from multiple callsites which cosock will properly and defensively treat as an error condition. This is done by adopting what is basically an actor/handle pattern for the Hue API instances.
- The second commit fixes an issue where certain network topologies or user configurations can mask the bridge's MAC Address at discovery time when processing mDNS responses, so we now always query the bridge directly for this information.
- The …

fix: Addresses several issues with the Hue driver discovered in beta testing

---

drivers/SmartThings/matter-lock/profiles/nonfunctional-lock.yml
drivers/SmartThings/matter-lock/src/init.lua
drivers/SmartThings/matter-lock/src/lock_utils.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_codes.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_cota.lua

When a lock is added to the driver, and we receive a RequirePINforRemoteOperation report set to true, we kick off the process of setting a COTA credential. First we SetCredential at index 1, if it fails because that slot is occupied we retry with the next available index which is reported in the SetCredentialResponse. Edge cases that are detected:
* The generated credential is a duplicate of a PIN that already exists
* We cannot set a credential because there is no space left on the device
* The user deletes the COTA credential
Work to be done:

Matter lock cota edge cases

---

.github/scripts/check_duplicates.py
.github/workflows/duplicate-profiles.yml

Fixes an issue where multiple "No duplicate profiles detected." messages would be posted on PR's. The script will now edit the same comment everytime it is run.

Fix multiple comments from duplicate profile script

---

drivers/SmartThings/philips-hue/src/disco.lua

EDGE_CHILD didn't exist when I started this driver, and now it does.
Open question: How do we fix devices already in the wild?

fix: use EDGE_CHILD type for lights

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/profiles/switch-power-smartplug-no-firmware-update.yml
drivers/SmartThings/zigbee-switch/profiles/vimar-switch-power-smartplug.yml
drivers/SmartThings/zigbee-switch/src/zigbee-switch-power/init.lua
drivers/SmartThings/zigbee-switch/src/zigbee-switch-power/vimar/init.lua

Add support with a custom sub-driver for:
- Vimar Smart Actuator with Power Metering (xx593)

Add zigbee-switch for Vimar xx593

---

drivers/SmartThings/wemo/src/discovery.lua
drivers/SmartThings/wemo/src/init.lua
drivers/SmartThings/wemo/src/util.lua

The MAC printed on the device and advertised in device metadata is used for the access point that the wemo device sets up for onboarding, and the MAC that is used once on the homes network is one more than what is advertised in metadata. The DTH got the actual MAC because its discovery pulls this info from the network; the driver queries the device for this info because it is not available on the socket that we have in drivers. This change will consider MAC addrs that are off by one as equal when discovering devices on the LAN.
An alternative approach would be to "calculate" the actual mac address from what is reported from the device, but there is no guarantee that all wemo devices will actually being doing this MAC change. Documentation is very limited.

Wemo MAC differences on migrated devices

---

drivers/SmartThings/sonos/src/api/sonos_connection.lua
drivers/SmartThings/sonos/src/api/sonos_websocket_router.lua
drivers/SmartThings/sonos/src/init.lua
drivers/SmartThings/sonos/src/types.lua

If a speaker is in a group but its coordinator isn't on the platform
we still want to be able to work with the speaker. The driver actually
worked like this originally but migration readiness broke this.
This fix restores that functionality. It also adds explicit reconnect logic
instead of waiting for an eventual reconnect based on group status
changes.
Fixes: CHAD-10235, CHAD-10136, CHAD-10005

Fix CHAD-10235: Address issues when coordinator speaker isn't joined

---

drivers/SmartThings/wemo/src/init.lua

The driver will still try to re-discover the ip/port when the devices are initialized, and will overwrite this value if it does discover the device, but sometimes wemo devices stop responding to ssdp after being on the network for awhile, even though they are still reachable.

Extract DTH discovered ip/port from migrated devices

---

drivers/SmartThings/zigbee-thermostat/src/fidure/init.lua
drivers/SmartThings/zigbee-thermostat/src/init.lua
drivers/SmartThings/zigbee-thermostat/src/test/test_fidure_thermostat.lua
drivers/SmartThings/zigbee-thermostat/src/test/test_zenwithin_thermostat.lua
drivers/SmartThings/zigbee-thermostat/src/test/test_zigbee_thermostat.lua
drivers/SmartThings/zigbee-thermostat/src/zenwithin/init.lua

The DTHs for the fidure and Zen zigbee thermostats were reporting a custom event when they received ThermostatRunningMode attribute reports, while the zigbee thermostat DTH maps them to mode events.
Also, the zigbee thermostat base driver included a read of the attribute that was not present in the DTH.

BUG-6885 Change sub-driver handling of ThermostatRunningMode

---

drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/hue/cie_utils.lua
drivers/SmartThings/philips-hue/src/hue/fields.lua
drivers/SmartThings/philips-hue/src/init.lua

When this driver was originally published it used the HSV < - > CIE 1931 XY math in `st.utils` which is based on the math from `zll-rgbw-bulb` but it turns out that the transform for Hue isn't actually the same.
This PR introduces the same color conversion math that was used in the Protocol Handler for Hue, making the edge driver behave more like existing Hue integrations.

Port HSV < - > xy math from the Protocol Handler

---

drivers/SmartThings/philips-hue/src/hue/cie_utils.lua

We use snake case for our Lua code, and in the process of porting some old C code from a protocol handler I forgot to `snake_case` some variables.

Fix: fix ported C code with wrong stlye

---

drivers/SmartThings/zwave-thermostat/fingerprints.yml
drivers/SmartThings/zwave-thermostat/profiles/base-thermostat-ct100.yml
drivers/SmartThings/zwave-thermostat/src/ct100-thermostat/init.lua
drivers/SmartThings/zwave-thermostat/src/test/test_ct100_thermostat.lua

A lot of behavior was ported over from the DTH which, I think, in hindsight, could have been foregone. I've attempted to pare this driver back to the z-wave standard except for some polling that seems as though it might have been necessary. This also includes a new profile with a range defined to match the set point bounds in the DTH.

BUG-6683 Simplify CT100 driver

---

drivers/SmartThings/zwave-switch/src/eaton-accessory-dimmer/init.lua
drivers/SmartThings/zwave-switch/src/init.lua

This functionality existed in the DTHs, but was not ported over fully. Appears non-standard and so not being added to defaults, but is at least useful for the Evalogik dimmer switch

BUG-6884 Handle Switch Multi stop command

---

drivers/SmartThings/sonos/profiles/sonos-player.yml
drivers/SmartThings/sonos/src/api/cmd_handlers.lua
drivers/SmartThings/sonos/src/api/event_handlers.lua
drivers/SmartThings/sonos/src/api/sonos_connection.lua
drivers/SmartThings/sonos/src/api/sonos_websocket_router.lua
drivers/SmartThings/sonos/src/init.lua
drivers/SmartThings/sonos/src/lunchbox/rest.lua
drivers/SmartThings/sonos/src/types.lua

Remove the `Rewind` and `Fast Forward` capabilities because not everything in the plugin is respecting the supported command event emission.
Fixes: CHAD-10316
No ticket, just some issues that were found during development that would result in crashes sometimes during disconnect.
Add the `mediaGroup` capability and its handlers/emissions back to Sonos. Erroneously dropped when porting.
Fixes: CHAD-10310
Add the `audioNotification` and its handlers back to Sonos. Erroneously dropped when porting.
Fixes: CHAD-10289

Fix Sonos issues related to capability mismatches from DTH to Edge Driver

---

drivers/SmartThings/zwave-sensor/src/aeotec-multisensor/init.lua
drivers/SmartThings/zwave-sensor/src/test/test_aeotec_multisensor_6.lua

Notification report handler overwrote defaults without redefining handling of tamper. Also re-added some handling of other events from the DTH that were missing here.

HCS-4016 Enable tamper detection for Aeon Multi 6/7

---

drivers/SmartThings/zigbee-contact/src/smartsense-multi/init.lua
drivers/SmartThings/zigbee-contact/src/test/test_smartsense_multi.lua

The original `can_handle` function was not working, so anytime one of the original SmartThings multi sensors would join, it would not correctly map to the smartsense-multi subdriver. This is due to the fact that the multisensors don't report that they support the cluster 0xFC03 (custom smartsense multi cluster), so the previous `can_handle` implementation would never return true. Now, we just check the manufacturer and the model in the `can_handle` function to ensure that the function returns true for the appropriate sensors.

zigbee-contact: Fix vibration/3-axis reporting for original SmartThings multi sensor

---

.github/scripts/check_duplicates.py

Some profiles don't have a category (such as "thing" profiles like matter-thing.yml and zigbee-thing.yml). This addresses that by using the `get()` function to access the category in the python dictionary so that if no category is found, then `get()` will return `None` instead of a `KeyError` that would happen when using `["key"]`.

Handle cases where there is no category in duplicate profile check

---

drivers/SmartThings/bose/src/disco.lua

This has been encountered once in the field (discovered by nil index error), and there is not much we can do about it until it happens again and we see what was received from the device to determine if it is a device issue we can recover from during discovery.

Handle invalid response from bose device during discovery

---

.github/workflows/duplicate-profiles-comment.yml

I missed this little change, but I hope this is the last thing needed for this to run smoothly.

Fix PR number in duplicate profile comment workflow

---

drivers/SmartThings/zwave-lock/src/init.lua
drivers/SmartThings/zwave-lock/src/test/test_zwave_lock.lua
drivers/SmartThings/zwave-lock/src/test/test_zwave_lock_code_migration.lua

This brings behavior back in line with the DTH.

Refresh of lock with codes causes too many events

---

drivers/SmartThings/wemo/src/init.lua

Consider all dimmers as regular smart switches.
Some Wemo switches erroneously report that they are dimmers, so the change prevents switchLevel capability from being added to all wemo devices. Note this is the same as current DTH behavior and is not a loss of functionality on the platform.

Wemo dimmers are unreliably reported

---

drivers/SmartThings/zigbee-switch/fingerprints.yml

The following device had the incorrect profile assignment looking at the DTH, it should have moved to a profile with the switch level capability. 
manufacturer: AduroSmart Eria    model: BDP3001

fixed incorrect profile assignment for AduroSmart Eria device

---

drivers/SmartThings/bose/src/disco.lua
drivers/SmartThings/bose/src/init.lua
drivers/SmartThings/bose/src/listener.lua

Harden the SSDP header regex to handle more valid HTTP headers. Also provide more explicit logging for the various discovery conditions.
Spawn device init as a cosock task in case it takes a long time, so the device thread is not blocked.
Device added and device init result in initialization code running once to account for existing lan bugs where sometimes init is not run when newly joined devices are added.
Make disco loop more robust to avoid overuse of sockets when multiple devices are being discovered/migrated at one time. This will follow the pattern I used for Wemo where the disco loop can service multiple discovery requests from the driver (due to init or scan nearby) with a single multicast discovery request.
Refresh should restart the websocket listener if it needs to be. This …

Bose discovery hardening

---

drivers/SmartThings/matter-lock/src/init.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_cota.lua

In any non-SUCCESS DlStatus in the SetCredentialResponse for setting the COTA cred on a device, if there is a next_credential_index available then we attempt to set the COTA cred there.

Matter-lock cota SetCredential FAILURE handling

---

drivers/SmartThings/bose/src/command.lua
drivers/SmartThings/bose/src/listener.lua
drivers/SmartThings/bose/src/utils.lua

xml fields that are not present are parsed as empty tables, but when used with our capabilities should be nil. This adds better sanitization for all xml values we put into capability events.

Sanitize xml fields from bose devices

---

drivers/SmartThings/bose/src/init.lua
drivers/SmartThings/sonos/src/api/sonos_connection.lua
drivers/SmartThings/wemo/src/init.lua

This function was added to the lua libs included with 0.46 hub firmware, so any hubs still on 0.45 will crash (i.e. SCH/ST Wifi)

Do not use st.utils.backoff builder in all lan drivers

---

drivers/SmartThings/matter-sensor/fingerprints.yml

Minor fix to the label to include temperature short-form for a fingerprint that includes both device types, since this gets used as a default label in the app post onboarding.

Fix label for Matter temperature and humidity sensor

---

drivers/SmartThings/zigbee-contact/src/smartsense-multi/init.lua
drivers/SmartThings/zigbee-contact/src/test/test_smartsense_multi.lua

When this device reports its status, it sends a 16-bit temperature value as a part of the report. This was being incorrectly handled as an 8-bit value. This fix ensures the status handlers properly handle the temperature value as a uint16.

Fix status/status report handling for smartsense multi

---

drivers/SmartThings/zwave-thermostat/src/init.lua
drivers/SmartThings/zwave-thermostat/src/test/test_aeotec_radiator_thermostat.lua
drivers/SmartThings/zwave-thermostat/src/test/test_fibaro_heat_controller.lua
drivers/SmartThings/zwave-thermostat/src/test/test_qubino_flush_thermostat.lua
drivers/SmartThings/zwave-thermostat/src/test/test_zwave_thermostat.lua

This is a workaround for handling fractional setpoint in zwave thermostats while a more permanent fix is added to the lua libs. Fractional values such as 21.5 are expected to be represented with an int value and a corresponding precision value such that the temperature = value * 10^(-precision).

Add special handling for fractional endpoints

---

drivers/SmartThings/samsung-audio/src/handlers.lua

"https://smartthings.atlassian.net/browse/CHAD-10011" -> Fix for delay in Play and Volume command.
Power On/Off command is not responsive for samsung-audio (known issue with cloud DTH case too).
Play is using power command which is causing delay in command execution. So, commented the power command.
For Volume setting, now emitting the new set volume (received in device response) back to ST app.

Play and Volume Delay Fix

---

drivers/SmartThings/samsung-audio/profiles/samsung-audio.yml

Fix Issues for https://smartthings.atlassian.net/browse/CHAD-10342 (POST mig: "Fast forward" and "Rewind" options appear in automation trigger)

Fix FF and RW in Automation for Post Mig

---

drivers/SmartThings/sonos/src/init.lua

This replaces #601. The group_* reference has been added to the CmdHandlers
cc: @dljsjr

[Sonos] Correct Alignment of mediaGroup Commands & CmdHandlers

---

drivers/SmartThings/sonos/profiles/sonos-player.yml
drivers/SmartThings/sonos/src/api/cmd_handlers.lua

This is a PR to address a separate community PR that wanted to shore up behavior for loading favorites to a Sonos queue: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/577
The linked PR definitely presents a better take on what the default behavior should be, however, the existing integration we provide uses the speaker's default behavior which is equivalent to the `Append` preference in this PR.
cc @TheMegamind

[Sonos] Add preference for the load faves queue behavior

---

drivers/SmartThings/zwave-fan/fingerprints.yml

This device was actually matching a zwave switch [fingerprint](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/5f908dd06f7031e1dae2e6b6518af90eaeb60d87/drivers/SmartThings/zwave-switch/fingerprints.yml#L25-L29) because that fingerprint omitted the ProductId.
Here is the actual device: https://products.z-wavealliance.org/products/3928?selectedFrequencyId=2

Add missing zwave fan fingerprint

---

drivers/SmartThings/zwave-lock/src/test/test_zwave_lock.lua

There was a bug in the z-wave defaults that didn't get caught by this test but should have. The bug: When we were emitting code events, we were always using the fallback form of `Code N` even if a user supplied lock code name was set.
The test as written uses the fallback code name as the user supplied code name, meaning that the test didn't catch the edge case when the user supplied a name that wasn't the same as the default.

fix(zwave-lock): Update a faulty setCode test

---

drivers/SmartThings/sonos/src/api/event_handlers.lua

Sonos can send playback metadata updates that dont include the title, which is a required field in our capability.
Fixes: CHAD-10520

fix(Sonos): Dont emit audio track data with no title

---

drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/hue/fields.lua
drivers/SmartThings/philips-hue/src/init.lua

Our color conversions don't properly wrap the value of 100% hue (360 degrees) around to be equivalent to 0% hue (0 degrees). This workaround does that wrapping, and reverses it when we receive a device update.

CHAD-10232 Handle overlap of 0/360 degrees in HSV color space

---

drivers/SmartThings/zwave-switch/fingerprints.yml

Adds fingerprints specifically for the 3301/3201 Leviton products. Without this change, the fingerprint was too permissive and was causing the Levition 3601 product to incorrectly match the same switch level profile as the 3301/3201 products. The 3601 product should now correctly match the right generic fingerprint.

Add Leviton dimmer switch fingerprints

---

drivers/SmartThings/zwave-switch/src/test/test_aeotec_dimmer_switch.lua
drivers/SmartThings/zwave-switch/src/test/test_aeotec_nano_dimmer.lua
drivers/SmartThings/zwave-switch/src/test/test_fibaro_double_switch.lua
drivers/SmartThings/zwave-switch/src/test/test_qubino_din_dimmer.lua
drivers/SmartThings/zwave-switch/src/test/test_qubino_flush_dimmer.lua
drivers/SmartThings/zwave-switch/src/test/test_zwave_dimmer_power_energy.lua

The preference order for the default on/off command was changed in v47 because of the differences in functionality between binary switch on and switch multilevel on. Namely, switch multilvel on returns to the most recent on value, which was viewed as preferred.

Change switch on/off default commands to reflect v47

---

drivers/SmartThings/matter-lock/src/init.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_cota.lua

A couple spots were missed when refactoring the cota credential setting operations previously. This fixes those callsites

Matter Lock: Fix set_cota_credential refactor bug

---

drivers/SmartThings/bose/src/listener.lua

This reverts commit d7dc244e7eb03d3f7b6fa6395cb0a9edff0cb62d.
this is needed to enable migrations sooner rather than later. Very little impact to users.

Revert "Remove supportedTrackControlCommands when playing radio source"

---

drivers/SmartThings/zigbee-window-treatment/src/aqara/init.lua
drivers/SmartThings/zigbee-window-treatment/src/test/test_zigbee_window_treatment_aqara.lua
drivers/SmartThings/zigbee-window-treatment/src/test/test_zigbee_window_treatment_aqara_roller_shade_rotate.lua

Added code to send a command to the device to be not member of the group.
```lua
local function do_configure(self, device)
...
device:send(Groups.server.commands.RemoveAllGroups(device))
...
end
```

[Aqara] Update a doConfigure handler in the zigbee-window-treatment driver

---

drivers/SmartThings/wemo/src/init.lua

This reverts commit 2690e669d0e6063f64a89992845f28eeb97befcf.
This will not affect migration from DTHs (non of which include the switch level capability). The original reason for the change was because our testing encounter a device that reported dimmer funcitonality via ssdp discovery but didn't actually support it, so the capability was on the device but non functional. There are wemo dimmers that do work properly so we should keep this functionality for those devices.

Revert "Wemo dimmers are unreliably reported"

---

drivers/SmartThings/matter-sensor/profiles/humidity-battery.yml
drivers/SmartThings/matter-sensor/profiles/humidity.yml
drivers/SmartThings/matter-sensor/profiles/temperature-battery.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity-battery.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity.yml
drivers/SmartThings/matter-sensor/profiles/temperature.yml

Use Thermostat category because it results in a better icon than the GenericSensor category.

Update matter-sensor temperature sensor device category

---

drivers/SmartThings/zwave-switch/src/aeotec-smart-switch/init.lua
drivers/SmartThings/zwave-switch/src/init.lua
drivers/SmartThings/zwave-switch/src/test/test_aeotec_smart_switch.lua

It was discovered that, with the reordering of default switch on commands, that the Aeotec Smart Switch 6 reports Switch Multilevel support, but does not respond to Switch Multilevel commands. This workaround reverts it to using the same commands as the DTH.

CHAD-10664 Workaround for Aeotec Smart Switch 6

---

drivers/SmartThings/philips-hue/src/handlers.lua

When we refactored COLOR_GAMUT -> GAMUT, we missed a spot. This can cause refresh actions to fail for color lights.

fix: Fixes a place where a key rename was missed.

---

drivers/SmartThings/matter-switch/profiles/switch-3.yml
drivers/SmartThings/matter-switch/profiles/switch-4.yml
drivers/SmartThings/matter-switch/profiles/switch-5.yml
drivers/SmartThings/matter-switch/profiles/switch-6.yml
drivers/SmartThings/matter-switch/profiles/switch-7.yml
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch.lua

Since the generic fingerprinting is lacking in our ability to support multi-switch devices, we must detect them when being configured and profile switch if necessary.
Only devices that will work with the default handling will be switched:
1. They have multiple endpoints that support the OnOff cluster
2. Those endpoints have IDs that are consecutive to line up with our profile naming scheme to allow for component <-> endpoint mappings
I added profiles for multi switches up to 7 switches. Im not aware of even one powerstrip that is certified that has multiple endpoints.

Better matter multi-switch handling

---

drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/init.lua

This PR fixes two small issues that manifested in several small bugs:
1. We found a few more places where the new color gamut logic wasn't hardened and could allow for nil index errors
2. At some point we removed synthetic event emit on init, but never added a synthetic event emit on add to make up for it.

Hue bug fixes for event emit and initialization

---

drivers/SmartThings/bose/src/handlers.lua

Default is set to 30 for now, could be a preference, but the app should allow this to be set when creating a scene/automation

Bose handle nil level in audionotification

---

drivers/SmartThings/zwave-switch/fingerprints.yml

Add fingerprint for Leviton plug. Without explicitly adding this fingerprint, the device would match to the zwave-relay DTH rather than matching with the generic zwave fingerprint based on the ordering in the ranking phase of fingerprint matching.

Add fingerprint for Leviton legacy plug

---

drivers/SmartThings/zwave-switch/src/multi-metering-switch/init.lua
drivers/SmartThings/zwave-switch/src/test/test_multi_metering_switch.lua
drivers/SmartThings/zwave-switch/src/test/test_wyfy_touch.lua

- Fixes the method used for calculating the number of child devices
- Triggers a refresh when the root node sends updates, otherwise ignores them

CHAD-10712 Multi metering switch fixes

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua

Currently color control commands will fail if the switch/light is in the off state, but setting an options override for this will allow them to be successful while in the off state.

Use matter color control option to execute commands if off

---

drivers/SmartThings/matter-thermostat/profiles/thermostat-cooling-only-nostate-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-cooling-only-nostate-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-heating-only-nostate-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-nostate-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-heating-only-nostate-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-cooling-only-nostate-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-fan-cooling-only-nostate-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-fan-heating-only-nostate-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-fan-nostate-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-heating-only-nostate-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-nostate-nobattery.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-nostate-nobattery.yml
drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_featuremap.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua

I only added profiles for the nostate profiles since currently all thermostats are joined using those profiles.

Matter-thermostat add support for mains powered thermostats

---

drivers/SmartThings/zwave-sensor/profiles/aeotec-multisensor-6.yml

Icon of aeotec-multipurpose-6 sensor was wrong.
should be displayed as MotionSensor
https://aeotec.com/products/aeotec-multi-sensor-6

Icon of aeotec-multipurpose-6 sensor was wrong.

---

drivers/SmartThings/sonos/profiles/sonos-player.yml

We disabled the enum commands, but did not fully
disable the playbackStatus capability command values.
Fixes: CHAD-10815

fix(sonos): Properly remove FF and Rewind.

---

drivers/SmartThings/matter-switch/src/color_utils.lua
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua

The lua libs utils function returns NAN for these inputs which results failed capability event serialization when they are reported by a device. The utils function itself will be fixed in hub FW 0.48.x

Bugfix matter color control error on XY values of (0, 0)

---

drivers/SmartThings/matter-switch/src/init.lua

This functionality will be in the lua libs in 0.48 but only for devices that dont override the component_to_endpoint function.

Handle non-sequential matter endpoints in matter-switch

---

drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-switch/profiles/matter-bridge.yml

This maps to the matter-thing fingerprint since the platform does not yet support matter bridges.

Add generic fingerprint for matter bridges

---

drivers/SmartThings/zwave-thermostat/src/ct100-thermostat/init.lua
drivers/SmartThings/zwave-thermostat/src/test/test_ct100_thermostat.lua

customer devices were failing to respond. The DTH would have included a 500ms wait between each command, so this aims to restore that in hopes of the device being capable of responding.

BUG-7616 Add delays to gets after setpoint sets for CT100

---

drivers/SmartThings/sonos/src/api/sonos_connection.lua

This is mainly just a mitigation to unblock internal users experiencing crashes while testing other features. Im not sure when this would happen, but it seems like something in the device initialization failed to collect household info for the device. Ill try to get some more logs to investigate why this is happening.

Bugfix sonos listener receives message for unknown household

---

drivers/SmartThings/bose/src/listener.lua

The driver attempted to reconnect a devices websocket at most 10 times, before stopping. This meant that if the device did not come back online within 20 minutes, the device would be offline forever, or at least until the driver is restarted or the device is refreshed while it is reachable on the network.

Bugfix: Bose devices sometimes marked offline "forever"

---

drivers/SmartThings/zigbee-contact/src/multi-sensor/centralite-multi/init.lua
drivers/SmartThings/zigbee-contact/src/test/test_centralite_multi_sensor.lua

Original DTH was setting this value at 0x02 whereas the driver was configuring it to 20, leading to an order of magnitude-higher acceleration threshold.

BUG-7236 Fixes typo leading to less-sensitive Centralite multi-sensors

---

drivers/SmartThings/wemo/search-parameters.yml

This change adds search parameters to the wemo driver.
https://smartthings.atlassian.net/browse/CHAD-10633

CHAD-10633: Wemo search parameters

---

drivers/SmartThings/samsung-audio/search-parameters.yml

This change adds the search-parameters.yml file to the samsung audio driver.
https://smartthings.atlassian.net/browse/CHAD-10634

Samsung-audio: Add search-parameters to driver

---

drivers/SmartThings/wemo/src/init.lua

Some users are unable to onboard wemo devices with the LightSwitch model

Add missing wemo model name to profile match

---

.github/workflows/upload-driver-packages.yml
tools/deploy.py

Previous changes that added search-parameters files to some drivers didn't include changes to the deploy script to include those files so they were never included in the driver package. This change updates the deploy script to include them.

deploy: Add search-parameters to driver package

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/lunchbox/rest.lua

Best viewed commit-by-commit. First commit is a revert to the debug logging changes, so it's kind of noisy.
- Be smarter about situations where we create new API connections
- Recover some necessary state information in bridge `init` that can get lost but is needed for lights that still need to migrate
- Wrap a throwing function call in a `pcall`
Fixes: [CHAD-11148](https://smartthings.atlassian.net/browse/CHAD-11148)

fix: Make the Hue Driver resilient to crashes during migration

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/lunchbox/rest.lua
drivers/SmartThings/philips-hue/src/utils.lua

We introduced some accidentally quadratic behavior that was leading
to a massive amount of cosock tasks getting spawned.
We had to refactor the data flow a little bit in order to achieve this,
so the behavior may appear to have a changed a bit more than preferred.
However, the savings on CPU/Memory/network overhead are appreciable.

Refactor migration to avoid over-spawning tasks

---

drivers/SmartThings/zigbee-switch/src/aqara/init.lua

The aqara zigbee switch driver was loading preferences as though they were capabilities.

Fix Aqara preference loading

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/lunchbox/rest.lua
drivers/SmartThings/philips-hue/src/lunchbox/sse/eventsource.lua
drivers/SmartThings/philips-hue/src/utils.lua

This PR preps Hue to get back in to its normal, non-debug state that we've been using for the EU Alpha users.
We guard against one small capability bug, and then we revise logging entirely to be suitable for a production driver once again.
- fix: clamp hue/sat attr emit values to [0,100]: ad8490bcd40a1bebf4f6907dcf930584357ac461
- chore: Tidy up Hue driver logging: 3ccd9c36b6ddddb52739c567fa2deb3ed6f7fde7

Refactor Hue Driver back to non-debug state

---

drivers/SmartThings/zwave-sensor/src/ezmultipli-multipurpose-sensor/init.lua
drivers/SmartThings/zwave-sensor/src/test/test_ezmultipli_multipurpose_sensor.lua

Changes these commands to be more similar to the DTH commands (removes extra fields not used in DTH).

BUG-7315 Change EZMultiPli set color commands

---

drivers/SmartThings/matter-switch/fingerprints.yml

Previous change added an extra `matterManufacturer` key which caused the driver to not package.

fixup! Update fingerprints.yml (#481)

---

drivers/SmartThings/sonos/src/init.lua

This lets the backoff in the background task function properly.

fix: Remove the inner retry loop if no retry fn

---

drivers/SmartThings/sonos/src/api/sonos_websocket_router.lua
drivers/SmartThings/sonos/src/init.lua
drivers/SmartThings/sonos/src/ssdp.lua
drivers/SmartThings/sonos/src/utils.lua

This removes all logs below info-level from the hub logs.
Note, a handful of the critical log messages we used for debugging will still be available:
* `Found device for Sonos search query with MAC addr %s, comparing to %s` - for MAC addr.  Will still be in hub logs, but the quantity should be significantly reduced thanks to https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/826
* `Received SSDP response for non-primary Sonos device in a bonded set, skipping; SSDP Response: %s` - for checking number of bonded devices
* `Looking for Sonos Player on network for device (%s:%s)` - for dni
* `Couldn't find Sonos Player [%s] during SSDP scan, trying again shortly` - for finding DNI of devices that are still trying to be matched

Reduce Sonos logging but keep important logs in hub logs

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/utils.lua

Instead we rely on the static mapping. There have been reported issues with this code in the community and given that we have well established static mappings in the cloud now it's mostly not needed.

fix: Don't re-detect profiles during migration

---

drivers/SmartThings/matter-switch/fingerprints.yml

We would like to use "Eve Energy” without the country information for all end-user-facing strings. This commit updates the deviceLabel string in the fingerprints to remove the country information.

Eve: Update deviceLabel

---

drivers/SmartThings/zwave-sensor/src/aeotec-multisensor/multisensor-6/init.lua
drivers/SmartThings/zwave-sensor/src/aeotec-multisensor/multisensor-7/init.lua
drivers/SmartThings/zwave-sensor/src/enerwave-motion-sensor/init.lua
drivers/SmartThings/zwave-sensor/src/homeseer-multi-sensor/init.lua
drivers/SmartThings/zwave-sensor/src/init.lua
drivers/SmartThings/zwave-sensor/src/sensative-strip/init.lua
drivers/SmartThings/zwave-sensor/src/test/test_aeotec_multisensor_6.lua
drivers/SmartThings/zwave-sensor/src/test/test_aeotec_multisensor_7.lua
drivers/SmartThings/zwave-sensor/src/test/test_enerwave_motion_sensor.lua
drivers/SmartThings/zwave-sensor/src/test/test_everpsring_sp817.lua
drivers/SmartThings/zwave-sensor/src/test/test_everspring_PIR_sensor.lua
drivers/SmartThings/zwave-sensor/src/test/test_fibaro_door_window_sensor_2.lua
drivers/SmartThings/zwave-sensor/src/test/test_fibaro_door_window_sensor_with_temperature.lua
drivers/SmartThings/zwave-sensor/src/test/test_fibaro_flood_sensor_zw5.lua
drivers/SmartThings/zwave-sensor/src/test/test_fibaro_motion_sensor_zw5.lua
drivers/SmartThings/zwave-sensor/src/test/test_homeseer_multi_sensor.lua
drivers/SmartThings/zwave-sensor/src/test/test_no_wakeup_poll.lua
drivers/SmartThings/zwave-sensor/src/test/test_sensative_strip.lua
drivers/SmartThings/zwave-sensor/src/test/test_vision_motion_detector.lua
drivers/SmartThings/zwave-sensor/src/test/test_zwave_motion_light_sensor.lua
drivers/SmartThings/zwave-sensor/src/wakeup-no-poll/init.lua
drivers/SmartThings/zwave-smoke-alarm/src/fibaro-smoke-sensor/init.lua
drivers/SmartThings/zwave-smoke-alarm/src/test/test_fibaro_smoke_sensor.lua
drivers/SmartThings/zwave-thermostat/src/test/test_thermostat_heating_battery.lua
drivers/SmartThings/zwave-thermostat/src/thermostat-heating-battery/init.lua

This helps the hubs device health implementation work better for migrated devices by ensuring a WakeUpIntervalReport is received post migration. Note this will be done by default in the lua libs post 0.49.x hub FW release.

Send WakeUpIntervalGet once when device wakes up

---

drivers/SmartThings/zwave-switch/fingerprints.yml

Because we had two fingerprints with only one command class each, a device that supported both command classes would match to both with equal 'match score'. I've added a third fingerprint such that devices that support both binary and multilevel switch ccs will match to a multilevel profile

BUG-8069 Z-Wave Switch: fix generic fingerprint ranking

---

drivers/SmartThings/zwave-sensor/src/aeotec-multisensor/multisensor-6/init.lua
drivers/SmartThings/zwave-sensor/src/test/test_aeotec_multisensor_6.lua

Change is based on both reports from devices as well as closer inspection of DTH code.

BUG-7952: Aeotec Multi 6: fixes powerSource reports

---

drivers/SmartThings/zigbee-lock/src/init.lua
drivers/SmartThings/zigbee-lock/src/lock-without-codes/init.lua
drivers/SmartThings/zigbee-lock/src/lock_utils.lua
drivers/SmartThings/zigbee-lock/src/test/test_c2o_lock.lua
drivers/SmartThings/zigbee-lock/src/test/test_generic_lock_migration.lua

Because our fingerprinting system cannot distinguish between zigbee locks that do and do not support lock codes, users with non-WWST-certified devices that do support lock codes are unable to use that functionality on our platform. Previously they could easily switch the DTH to enable this, but with drivers this is not possible without a custom driver installed.
This logic attempts to determine whether a lock that was fingerprinted without user codes actually supports user codes or not, and switches the profile to one which does. It will also attempt to recover and lock codes carried over from migration.

Switch generic locks that support lock codes

---

drivers/SmartThings/zigbee-button/src/zigbee-multi-button/init.lua

It's possible that config is nil.
We should not use it without checking, otherwise we will hit nid index error.

Bug fix:  avoid indexing a nil object

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/hue/types.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/lunchbox/sse/eventsource.lua
drivers/SmartThings/philips-hue/src/utils.lua

The main change to the functionality of the driver in this PR is that *all* mDNS operations have been consolidated in to a function that does the requisite REST calls for discovered bridges and updates state on the driver's persistent store by accessing the `driver.datastore` table proxy directly.
I'm not normally in favor of using side-effect oriented flows like this, but in this specific case it actually solves a lot of problems for us:
1. It reduces the number of tasks trying to use the mDNS socket at the same time by removing mDNS operations from `search_for_bridges`
2. It reduces the number of tasks attempting REST network operations by having the various tasks that run during init and migration simply query the datastore cylically instead of querying the network cyclically (in the …

Add periodic mDNS Scanning to Philips Hue Edge Driver

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/hue/types.lua
drivers/SmartThings/philips-hue/src/init.lua

In the specific situation where a Hue topology gets migrated with a stale IP
address, we can get in to a situation where the change detection happens
before the `[joined_bridges]` map is populated, meaning that subsequent scans
won't know that an update needs to happen.
The DTH Protocol Handler is wise enough to find a Hue Bridge after its IP has changed and make sure its connecting properly but it doesn't *appear* that it updates the `ip` field on its device data reliably, so if a device migrates any time after its IP has changed it's likely that we'll receive the incorrect IP out of the gate, which would put us in this situation.
We rectify that by also factoring in the stored IP in the device's fields
when determining if a change has occurred.

Fix for Hue devices that migrated in to an incomplete state with stale IP data.

---

drivers/SmartThings/philips-hue/src/init.lua

This is a result of a workaround for a pre-release defect that was present during pre-release testing and has been fixed but we need to continue to support devices that may have encountered it.
For some devices the service ID will be captured in the DNI instead of the parent assigned child key and so we should check both, but due to an oversight we are only looking at the DNI currently.
This could assist in some rare situations where the v1 ID may not be stable, but I don't have any evidence that this bug is actually impacting any users.

fix: Check DNI + parent assigned key for strays

---

drivers/SmartThings/zigbee-vent/fingerprints.yml

The Keen Vent DTH used a generic, rather than mfr-specific fingerprint. This adds back in that FP to the driver so that users can re-add devices as vents.

Add Keen generic vent fingerprint

---

drivers/SmartThings/sonos/src/disco.lua
drivers/SmartThings/sonos/src/init.lua
drivers/SmartThings/sonos/src/ssdp.lua
drivers/SmartThings/sonos/src/types.lua
drivers/SmartThings/sonos/src/utils.lua

Similarly to Hue, this adds a periodic scan for detecting changes in IP address
at runtime after a device has onboarded.
This refactor isn't as surgical as the Hue one because the Sonos topology is
simpler, so we didn't do a deep gutting of the discovery logic and left it
mostly untouched, so we still actively perform SSDP scans during discovery.
Relaxing this for Sonos is likely best left to a refactor after we move the
SSDP APIs in to hubcore and expose them via the lua libs.
Fixes: [CHAD-11472](https://smartthings.atlassian.net/browse/CHAD-11472)
cc @TheMegamind

Sonos: Add Periodic SSDP scan to detect IP changes

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/profiles/button.yml
drivers/SmartThings/zigbee-switch/src/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_wallhero_switch.lua
drivers/SmartThings/zigbee-switch/src/wallhero/init.lua

* WALLHERO: Add 8-Way Switch EdgeDriver
* Remove 4-way Switch
* Minor Fix
1. Rename wallhero-scene-switch to button.
2. Replace child_device:emit_event with device:emit_event_for_endpoint.
3. Only set button capabilities for scene switch.
---------

Add WALLHERO Switch (#895)

---

drivers/SmartThings/zigbee-switch/src/test/test_duragreen_color_temp_bulb.lua
drivers/SmartThings/zigbee-switch/src/white-color-temp-bulb/duragreen/init.lua
drivers/SmartThings/zigbee-switch/src/white-color-temp-bulb/init.lua

DuraGreen is not compatible with current default switchlevel api,
It can't process options_mask and options_override.
Build specific command as a workaround.

DuraGreen Light: Build specific command

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/init.lua

Changes in hubcore 0.49 require LAN-parented Child Devices to manage their online/offline state explicitly instead of automagically following the parent's health, which is needed to allow for child devices to mark themselves offline independently.
There were places in the Hue driver that made assumptions around child devices always following their parents, so we need to make a few tweaks to address that.
Primarily:
1. Bulbs call `online()` on themselves at the end of their `init` block;
2. The Hue Bridge will walk all of its children and manually update their state to `offline` when the bridge goes offline, and will poll the actual Zigbee connectivity status reported by the bridge when the bridge comes `online`.
The goal here is to try and minimize state divergence between local device …

Update Hue Driver to accommodate 0.49.x changes for LAN Child Device Health

---

drivers/SmartThings/philips-hue/src/cosock.lua

A race condition bug in Cosock can lead to crashes, and we think we have a good bead on fixing the issue with these changes. Because these updated lua libs won't go out for a while, we're investigating keeping them as an in-tree patch to alleviate the issues in the driver for now.

fix: Patched cosock.lua to avoid spurious crash

---

tools/run_driver_tests.py

Windows's path is different with Linux's path. Therefore, some codes for processing file paths cannot be used across platforms.

Minor fix: Fix compatibility issues

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua

Some devices could report a value of 0 mireds, which would result
in a divide by zero error when converting to kelvin. This
introduces a check to make sure that 0 and other mired values
that are outside the range of the colorTemperature capability are
not handled since they are likely not real values.

Fix color temperature handling when attribute is outside capability range

---

drivers/SmartThings/matter-button/fingerprints.yml
drivers/SmartThings/matter-button/profiles/2-button-battery.yml
drivers/SmartThings/matter-button/profiles/2-button.yml
drivers/SmartThings/matter-button/profiles/4-button-battery.yml
drivers/SmartThings/matter-button/profiles/4-button.yml
drivers/SmartThings/matter-button/profiles/8-button-battery.yml
drivers/SmartThings/matter-button/profiles/8-button.yml
drivers/SmartThings/matter-button/profiles/button-battery.yml
drivers/SmartThings/matter-button/profiles/button.yml
drivers/SmartThings/matter-button/src/init.lua
drivers/SmartThings/matter-button/src/test/skip_test_latching_switch.lua
drivers/SmartThings/matter-button/src/test/test_matter_button_parent_child.lua
drivers/SmartThings/matter-button/src/test/test_matter_multi_button.lua

re-order type handling so that multi-press buttons have priority keep newly-created components and devices around in a map to avoid race conditions updating device storage
avoid race condition when switching profile
change multi buttons to support held events

Add multi-button support for matter button devices.

---

drivers/SmartThings/matter-window-covering/src/init.lua

The CurrentPositionLiftPercent100ths attribute can report a value of nil when the current position is unknown (e.g. calibration is needed). Add a check to make sure we do not try to use position if it is nil.

Add a nil check for matter window covering level in status handler

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/zigbee-dimming-light/init.lua

Added Nexentro Actuator:
NEXENTRO Dimming Actuator

Added NEXENTRO Dimming Actuator Fingerprints

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-sensor/profiles/matter-motion-battery.yml
drivers/SmartThings/matter-sensor/profiles/motion-contact.yml
drivers/SmartThings/matter-sensor/profiles/motion-illuminance-battery.yml
drivers/SmartThings/matter-sensor/profiles/motion-illuminance.yml
drivers/SmartThings/matter-sensor/src/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_sensor_featuremap.lua

The `matter-sensor` generic fingerprints all join to profiles with `battery` support by default. This change will attempt to check for battery support when the device is configured and then change to the appropriate version of the profile (battery or no battery).

Matter-sensor add support for mains powered sensors

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat_composed_bridged.lua

Our "default" endpoint logic current returns the lowest endpoint. For matter composed bridged devices, the current "default" endpoint would be the BRIDGED_NODE_DEVICE_TYPE endpoint because it is the lowest endpoint for the bridged device. However, that endpoint does not support the desired clusters, so we want to find the first endpoint that supports our desired cluster and map that to the corresponding component.
This should not affect existing behavior because for single endpoint non-bridged devices, the default endpoint would also support the given cluster.

Matter Thermostat: fix default endpoint mapping

---

drivers/SmartThings/matter-sensor/src/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_sensor.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_sensor_featuremap.lua

This moves the battery-checking logic from do_configure to init so that device will not have to be removed and re-added in order to join the correct profile.

Matter Sensor: check for battery on init

---

drivers/SmartThings/matter-button/src/init.lua
drivers/SmartThings/matter-button/src/test/test_matter_multi_button.lua

This fixes two problems with the endpoint/component mapping:
- The Lua table serializer cannot handle numerical keys that don't start at 1 (aka an array) because it serializing to JSON and JSON objects require keys to be strings.
- Using `#` to check the size of a Lua table only works if the keys start at 1
Due to the second issue, the driver wasn't even trying to write the map to persistance, but even if that was fixed the first issue caused the driver to crash.
To fix the first issue we switch to using the components as the key which are strings so there is no issue converting to/from JSON.
To fix the second issue we use another variable to determine if we should write the map to persistance.
With these changes and the 0.50 hub firmware the Hue multi-button devices are now working. …

matter-button: Fix multi-button devices that don't start at endpoint 1

---

drivers/SmartThings/zwave-window-treatment/src/aeotec-nano-shutter/init.lua
drivers/SmartThings/zwave-window-treatment/src/test/test_zwave_aeotec_nano_shutter.lua

The stateless curtain power button needs to set its available command values before it will function correctly in the app. This was done in the DTH but was missed in the porting work.
I've added changes so that a refresh of the device should bring an already-installed device back to a good state. These changes can be removed at a later date as future installs will have them from the added handler changes.

BUG-8651 Aeotec Nano Shutter: add missing event

---

drivers/SmartThings/matter-switch/fingerprints.yml

In Matter it is valid for an endpoint that supports a specific device type to also support additional device types that are subsets of that device type. The Hue White is an example of a device that does this. Since we didn't have a fingerprint for an endpoint with both OnOff Light and Dimmable Light device types the fingerprinting logic happened to be picking the fingerprint with just the OnOff device type which uses a profile without levelControl.
The fix is to add additional fingerprints for each of the device types that are a superset of other device type(s).
**Note: This requires devices to be removed and re-added since it only changes the fingerprinting and does not change the profile of already joined devices.**
https://smartthings.atlassian.net/browse/MTR-473

matter-switch: Fix devices (ex: Hue White) that did not have levelControl

---

drivers/SmartThings/zigbee-contact/fingerprints.yml

On DTHs this could have been accomplished by manually switching the DTH.

BUG-8648: Give PGC sensors the garage door preference

---

drivers/SmartThings/matter-switch/profiles/matter-bridge.yml

Matter bridges do expose their firmware version but it wasn't visible to users in the SmartThings app because the profile did not include the necessary firmwareUpdate capability. This just adds that capability to the profile.
https://smartthings.atlassian.net/browse/MTR-475

matter-switch: Add firmwareUpdate capability to the profile used by bridges

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-sensor/profiles/matter-motion-battery-illuminance.yml
drivers/SmartThings/matter-sensor/profiles/motion-illuminance-temperature-battery.yml
drivers/SmartThings/matter-sensor/profiles/motion-illuminance-temperature.yml
drivers/SmartThings/matter-sensor/src/init.lua

The Hue motion sensor supports motion, temperature and illuminance sensors so added a fingerprint for those device types. Like the other battery powered Hue accessories, the motion does not support reporting battery percentage remaining so the battery capability is not used for Hue sensors.
**Note**: This fix only applies to newly joined devices so existing devices will need to be removed and re-added.
https://smartthings.atlassian.net/browse/MTR-476

motion-sensor: (Hue) Expose temperature and remove non-functional battery

---

drivers/SmartThings/matter-button/src/init.lua
drivers/SmartThings/matter-lock/src/init.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_codes.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_cota.lua
drivers/SmartThings/matter-media/src/init.lua
drivers/SmartThings/matter-media/src/test/test_matter_media_speaker.lua
drivers/SmartThings/matter-media/src/test/test_matter_media_video_player.lua
drivers/SmartThings/matter-switch/src/eve-energy/init.lua
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-window-covering/src/init.lua
drivers/SmartThings/matter-window-covering/src/test/test_matter_window_covering.lua

The default endpoint used in matter drivers is currently the first non-zero endpoint. However, this can cause problems in cases like composed matter devices or aggregated bridged devices where the first non-zero endpoint is not where we would expect to find the relevant clusters for each driver. These changes return the first endpoint that supports a relevant cluster for each driver in order to prevent this issue.
These changes were already ported to matter-switch, matter-button, and matter-thermostat.
[CHAD-11752](https://smartthings.atlassian.net/browse/CHAD-11752)

Find default endpoint by cluster for remaining matter drivers

---

drivers/SmartThings/matter-switch/fingerprints.yml

ticket: https://smartthings.atlassian.net/browse/CHAD-11890
```
Not Working
color temperature light
DeviceType { id: 268, revision: 1 }, 
onoff
DeviceType { id: 256, revision: 1 }, 
bridged device
DeviceType { id: 19, revision: 1 }],
Working 
color temperature light
DeviceType { id: 268, revision: 1 }, 
bridged device
DeviceType { id: 19, revision: 1 }]
```
Bug Description
* Current matter switch fingerprinting fails to accurately fingerprint a color temperature light if it also contains support for an onoff device type. In the example above, the working device would be fingerprinted to `light-level-colorTemperature` where as the not working device would fingerprint to `light-binary`.
How/When it Happens
* When onboarding a matter light which only contains support for a color temperature …

CHAD-11890: Switch Driver fails to profile color temperature lights if paired with an onoff device type

---

drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/hue/types.lua
drivers/SmartThings/philips-hue/src/init.lua

Adds explicit checking for zigbee connectivity status as part of refresh, instead of always waiting for it to come in on the SSE stream.
Note that the zigbee connectivity status itself within the Hue network can be delayed.
Because we're now doing more network calls during refresh, I also adjusted the "refresh all" handler to use the bulk endpoints.
To keep the changeset on this small, I did it by overloading the functionality of the existing refresh for single lights. It's noted in comments that this isn't the most ideal, however, I'm in the process of planning out a rearch of this driver including with a test coverage plan, so I didn't think deep surgery was warranted given that we're going to be doing a complete redo soon.
Pardon the Mess™

Poll bulbs for their Zigbee Connectivity status explicitly when refreshing

---

drivers/SmartThings/philips-hue/src/disco.lua

There are some situations where many discovery handlers can be started
at the same time, and in some cases this can lead to issues like duped
devices being created because the event create requests happen close
enough together that they skirt through checks for things like DNI
duplication.
The proper fix for this is to disallow this in firmware, but this is
impacting users currently so a stop-gap fix in the LAN Edge Drivers
at a minimum -- where this is more likely to happen -- may not be a bad
idea.

fix: Only allow a single discovery handler

---

drivers/SmartThings/harman-luxury/profiles/l42ms.yaml

certifiedpreferences.doNotDisturbPlayback is available from ST App R4 to support Harman Luxury L42ms.

add certifiedpreferences.doNotDisturbPlayback for L42ms

---

drivers/SmartThings/matter-switch/fingerprints.yml

As of the device's software release of "780014029", the device reports itself with device type of 0x10C, which is primarily used for Lighting devices with only Color Temperature, but the device supports color control. Adding this fingerprint to account for the color functionality

Matter Switch: Manufacture fingerprint for Sengled A19

---

drivers/SmartThings/harman-luxury/profiles/l42ms.yaml

Hi all,
Harman decided to go a head and enable the mediaPresets capability after all.

Small Change

---

drivers/SmartThings/matter-thermostat/src/init.lua

The matter-thermostat driver is using the "fanOnly" value of the thermostatMode capability. But since this capability requires using the "fanonly" value, events using the "fanOnly" value are ignored. This change renames "fanOnly" to "fanonly".
https://developer.smartthings.com/docs/devices/capabilities/capabilities-reference/#thermostatMode

Matter Thermostat: Fix thermostatMode capability

---

drivers/SmartThings/samsung-audio/src/command.lua

Sometimes old devices are failing to successfully use https to download samsung hosted audio notification files, in that case we should re-attempt with http before completely failing.

Samsung audio fallback to http when https fails

---

drivers/SmartThings/zigbee-thermostat/src/init.lua

Some changes in another PR modified an existing profile in an breaking
way, and we asked for those changes to be reverted in the PR. Some stuff
got missed, though. This addresses the stragglers.

 fix: finish restoring popp_danfoss -> danfoss

---

drivers/SmartThings/zigbee-switch/src/aqara/multi-switch/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_switch_power.lua

fix routine condition error on child button of light switch

[Aqara] Smart Wall Switch(With Neutral, No Neutral)

---

drivers/SmartThings/bose/src/handlers.lua

Rather than defaulting to 30 if the audio notification doesn't provide a volume level, default to the current volume with a default of 30 only if the current volume is unknown.
addresses: #911

Bose use current volume as default audio notification

---

drivers/SmartThings/jbl/src/lunchbox/rest.lua
drivers/SmartThings/philips-hue/src/lunchbox/rest.lua
drivers/SmartThings/sonos/src/lunchbox/rest.lua

Previously, it was possible to get stuck in an infinite loop while parsing a chunked response if the socket was closed and didn't return any partial data. Now, we will return in that case and propagate the "closed" error so that try to reconnect after the error.
I have tested this with hue and can with sonos but I don't have a JBL to test with.

CHAD-11987: Fix potential infinite loops in lunchbox

---

drivers/SmartThings/matter-lock/src/test/test_matter_lock_codes.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_cota.lua

A bug in the unit test framework has allowed these tests to get past. The integration test framework bugfix will be released with the 51 lua libs.

Matter lock subscribe request unit test expectation fix

---

drivers/SmartThings/matter-button/src/init.lua
drivers/SmartThings/matter-button/src/test/test_matter_multi_button.lua

Some Switch devices will send a MultiPressComplete event at the end of a long press sequence and others will not. Normally the driver creates button capability events on receipt of the MultiPressComplete but in the case of a long press it creates the "held" event on receipt of the LongPress event. If it also receives a MultiPressComplete as part of that long press sequence then it should ignore it so as not to generate an incorrect extra event.
The problem was that if a new button press was started (as determined by the receipt of a InitialPress) the driver was still ignoring the next MultiPressComplete event, and so that button press sequence would be ignored.
The fix is to only ignore MultiPressComplete that occurs as part of a long press sequence. …

matter-button: Missing button press after a long press

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/wallhero/init.lua

Manufacturers wallhero add new model ACL-401S2I zigbee-switch.
Please review it.

wallhero add model ACL-401S2I

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/wallhero/init.lua

Manufacturers wallhero add new model ACL-401S3I zigbee-switch.
Please review it.

wallhero add model ACL-401S3I

---

drivers/SmartThings/zigbee-switch/fingerprints.yml

Manufacturers wallhero add new model ACL-401S1I zigbee-switch.
Please review it.

wallhero add model ACL-401S1I

---

drivers/SmartThings/zigbee-switch/fingerprints.yml

Manufacturers wallhero add new model ACL-401ON zigbee-switch.
Please review it.

wallhero add model ACL-401ON

---

drivers/SmartThings/samsung-audio/src/command.lua

These changes are being added to handle cooldown period in certain speaker models. After the notification is played, the speaker assumes the notification to keep on playing for sometime. During this period, if another message is played, it sends "ok" response for PausePlaybackEvent and the notification actually fails. 
Refer to below ticket for details.
https://smartthings.atlassian.net/browse/BUG-8312

Samsung Audio notification fallback to http to handle cooldown period

---

drivers/SmartThings/matter-switch/src/init.lua

The On/Off Light switch device type requires bindings in order to work correctly because the On/Off cluster on this device type is client type as specified in the matter spec. Because we do not support bindings, we have removed the generic fingerprint for this device type so that it will join as a matter-things so we do not expose broken funcitonality to users. However, we have found some devices that do not follow the spec and report an On/Off Light Switch device type and yet have a server type OnOff cluster. These out-of-spec devices would technically have worked before we decided to remove the fingerprints due to lack of binding support, so these devices will be broken now that they will join as matter-thing. This adds a workaround that allows us to check for a special case where a …

Support switching from matter-thing to switch-binary

---

drivers/SmartThings/zigbee-switch/src/test/test_wallhero_switch.lua
drivers/SmartThings/zigbee-switch/src/wallhero/init.lua

Because the APP page displays "Turn off indicator light" , so when "true", it should be closed

Reverse switch operation

---

drivers/SmartThings/matter-window-covering/src/init.lua
drivers/SmartThings/matter-window-covering/src/test/test_matter_window_covering.lua

The "device" parameter was missing in the match_profile() call on infoChanged. This would cause the infoChanged event to error and not check for a new profile match.
Added unit test to explicitly test this case.
cherry-pick of changes in https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1101

Matter Window Covering: add missing parameter

---

drivers/SmartThings/zwave-smoke-alarm/src/test/test_fibaro_smoke_sensor.lua

This fixes unit tests when using the v8 lua libs that were just released. The fix removes what were extra refresh commands due to a bug that was present in the v6 lua libs.

Fixup unit test for 51 wakeup notification bugfix

---

drivers/SmartThings/matter-button/profiles/6-button-battery.yml
drivers/SmartThings/matter-button/profiles/6-button.yml
drivers/SmartThings/matter-button/src/init.lua

Add profile to support 6-button matter button devices. This means 6-button devieces will be supported as MCD rather than parent-child.

Matter Button: add 6-button static profile support

---

drivers/SmartThings/sonos/src/ssdp.lua

The current way we parse the SSDP response headers can cause failures in discovering Sonos speakers with Unicode characters that require more than one byte for their representation, such as CJK characters.
The current parsing patterns use the '`%g`' character class, which does not match characters that don't fit in a single byte. While Lua itself is utf-8 compatible, and it is safe to use multi-code-point graphemes or clusters in Lua strings, the actual string library is byte-oriented for many operations. The pattern used currently tries to match each byte against the provided class, which causes it to fail to match and capture many headers.
We now use a parsing pass for header key/value pairs derived from [the Luncheon library with bug fixes](https://github.com/cosock/luncheon/pull/9) …

Fix parsing patterns for SSDP responses in Sonos

---

drivers/SmartThings/matter-window-covering/profiles/window-covering-profile.yml

This profile was intentionally duplicated here: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1091#issuecomment-1830284489
Adding a comment so it is clear that `window-covering-battery` should be used instead and that this profile should be deprecated.

Matter Window Covering: add comment to deprecate window-covering-profile

---

drivers/SmartThings/matter-switch/src/eve-energy/init.lua
drivers/SmartThings/matter-switch/src/test/test_eve_energy.lua

Remove an unnecessary switch state read. The switch state should be already reported by the device itself so this frequent read is not necessary here.

Eve Energy: Improve the performance by removing unnecessary read

---

drivers/SmartThings/matter-switch/src/eve-energy/init.lua
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_eve_energy.lua
drivers/SmartThings/matter-switch/src/test/test_matter_bridge.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_mcd.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child.lua

Updates matter switch driver to use parent-child for multi switch devices rather than multi-component devices. Along with these changes, we will check for matter bridge devices before attempting a profile switch to prevent bridge devices from incorrectly switching to MCD switch profiles.

Matter Switch: use parent-child for multi switch devices

---

drivers/SmartThings/matter-switch/fingerprints.yml

This is a new WWST Matter device certification request for the Nanoleaf Smart Holiday String Lights  NL71.

new device (Matter Switch): Nanoleaf NL71 Holiday String Lights

---

drivers/SmartThings/philips-hue/src/init.lua

We like a lower interval to be kinder to the LAN and the hub, and we like
10 minutes. This was done in Sonos already but we left Hue at 1 minute, which
was the development testing period.

fix(hue): Don't mDNS scan every minute

---

drivers/SmartThings/zwave-lock/fingerprints.yml

This pull request is for multiple device adds under the Z-Wave Lock driver for the following Kaadas Locks. 
- [KA214](https://kaadassolutions.com/products/ka214-z-wave-touchpad-lever?variant=44660977697061)
- [KA211]( https://kaadassolutions.com/products/ka211-z-wave-touchpad-deadbolt?variant=44660952662309)
- [KA200](https://kaadassolutions.com/products/ka200-z-wave-key-free-keypad-deadbolt)
- [KA201](https://kaadassolutions.com/products/ka201-z-wave-keypad-deadbolt)
I have verified that these locks support the lockCode capability.

New device (Z-Wave Lock): Kaadas 00CD, 00C7, 00C8, 00C9

---

drivers/SmartThings/matter-sensor/profiles/humidity-battery.yml
drivers/SmartThings/matter-sensor/profiles/humidity.yml

Currently, it's displayed as a default image because the category of the humidity sensor is a GenericSensor.
To support the humidity Image, change the category of humidity sensor from GenericSensor to HumiditySensor.

Change the category of humidity sensor from GenericSensor to HumiditySensor.

---

drivers/SmartThings/philips-hue/src/lunchbox/rest.lua
drivers/SmartThings/sonos/src/lunchbox/rest.lua

The next Lua Libs release will include an update to the vendored dep Luncheon which has built-in support for chunked transfer encodings.
Previous versions of Luncheon did not support chunked transfer so we had to roll our own in order to handle large REST API responses.
We branch on the reported lua libs API version, using Luncheon directly if it's available, otherwise we continue to use the existing parsing.
Supercedes: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1148
Co-authored-by: Robert Masen <robert.masen@smartthings.com>

(Hue/Sonos) Use new Luncheon features if available

---

drivers/SmartThings/matter-switch/src/eve-energy/init.lua
drivers/SmartThings/matter-switch/src/test/test_eve_energy.lua

- Don't the power reports of the device if the device is off
- In the timer, we now check if the device is off using device:get_latest_state()
- Set the power to 0 before the read is skipped so that the power is correctly displayed and not using a stale value

Eve Energy: Improve the performance when the device is off

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/init.lua

Three commits here:
1. Automatically add or remove devices when SSE events indicating topology changes come in,
2. Check for changes in the devices joined to a Hue Bridge when we establish connectivity with a bridge. This handles the case where the Hue configuration changes while the hub is offline or the driver isn't running for some reason.
3. Wrap this new functionality so we have fallbacks on hubs that don't have the `try_delete_device` API in their Lua Libs.
Note that this won't be fully supported in production until the next release of hubcore that adds the delete API, by which time we also hope that the relevant cloud side changes will be ready as well. Hence the inclusion of the fallback if the `try_delete_device` function isn't available on the `Driver` table.

Automatically add/remove Hue lights when they are added/removed to Hue Bridge

---

drivers/SmartThings/matter-switch/fingerprints.yml

An issue with the fingerprint grading system is causing any bridged device with a matching vendorId to match to this fingerprint. We will remove this fingerprint while the issue is being resolved to prevent new bridged devices from joining with the wrong fingerprint.

Matter Switch: remove Aqara bridged fingerprint

---

tools/run_driver_tests.py

This change adds line number output to failure reports from the non-ci `run_driver_tests.py` script. This script doesn't run in CI/CD but can be useful for local development since it can take the `--filter` arg, which lets developers run groups of tests at once with JUnit reports.
Adding the line numbers to the `stdout` report is a QoL improvement for devs to jump to tests quickly; I've even been able to create a problem matcher for the output in VS Code now.
This also adds the line number of the test to the JUnit XML.
The `run_driver_tests_p.py` script that runs in CI/CD is unmodified.
Previous output example:
```console
Unit test failures in /home/dstephen/Developer/Workspaces/SmartThings/git/SmartThingsEdgeDrivers/drivers/SmartThings/zigbee-water-leak-sensor/src/test/test_centralite_wat …
```

Add line numbers to failure outputs for non-ci test script

---

drivers/SmartThings/matter-thermostat/fingerprints.yml
drivers/SmartThings/matter-thermostat/profiles/room-air-conditioner.yml
drivers/SmartThings/matter-thermostat/src/init.lua

- Add New Capabilities
- Add enumeration values

Update matter-thermostat driver

---

drivers/SmartThings/zigbee-lock/src/samsungsds/init.lua
drivers/SmartThings/zigbee-lock/src/test/test_zigbee_samsungsds.lua

override lock command handler from the sds lock
detailed description is here
https://smartthings.atlassian.net/browse/CHAD-12444

Zigbee Lock: Add lock command handler for sds doorlock

---

drivers/SmartThings/zigbee-window-treatment/src/test/test_zigbee_window_shade_battery_yoolax.lua
drivers/SmartThings/zigbee-window-treatment/src/yoolax/init.lua

Consolidates the timer logic used to check up on changing window shades into the sub-driver. Also uses a default response success from the device to indicate that the shade is moving. A subsequent poll should change the status to a stationary one if no updates are received within 30s.

BUG2-521 Rework yoolax window shade driver

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_featuremap.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua

This was just looking for the presence of the power source cluster whereas the correct check would be to look for the battery feature map bit in that cluster.

Fix the battery check in matter-thermostat, look for feature map

---

drivers/SmartThings/matter-switch/fingerprints.yml

This fingerprint had the wrong productID : https://smartthings.atlassian.net/browse/BUG2-1061

Matter Switch: fix Nanoleaf NL71K1 fingerprint

---

drivers/SmartThings/zigbee-motion-sensor/src/test/test_smartsense_motion_sensor.lua

I accidentally discovered that smartsense test run failed due to decode error.
The root cause is that our script use wrong encoding to open file.
This test script is "ISO-8859" encoding which includes "0xBD" which UTF-8 doesn't support.
```
❯ file test_smartsense_motion_sensor.lua
test_smartsense_motion_sensor.lua: ISO-8859 text
```
By default python3 uses UTF-8 to open file. That is we our script can't run smartsense test.
Import chardet lib to detect encoding format automatically to fix this issue.

Fix run_driver_tests.py UnicodeDecodeError

---

drivers/SmartThings/philips-hue/src/init.lua

This change puts an API Version guard around the call that performs the auto-add/auto-delete scan at startup, which is causing a crash on 0.47 TV's due to an issue with looking up non-existent UUID's.
We believe the root of the issue is that the non-existent UUID lookup is related to trying to look up the Hub UUID as the parent of the bridge. But because this is a pretty gnarly issue we're going to roll back completely while we're confirming our suspicion.

Hotfix: Revert auto-add/auto-delete on 0.47 hubs

---

drivers/SmartThings/matter-switch/fingerprints.yml

This is a fingerprint addition for the Zemismart Inline Module ZME2 Device. 
This will be a parent child Matter Device. 
The switch-binary profile was selected to support this device. 
We know that this device according to the DCL is 0x0103, and based on when the device joined in SRPOL this device supports the On/Off Cluster as a BOTH a client and as a server.

Adding Zemismart Inline Module ZME2 Device

---

drivers/SmartThings/matter-switch/src/init.lua

The On/Off Light Switch type supports the On/Off cluster as client, however some deviecs still report the On/Off light switch but implement On/Off cluster as server or both. There was previously a check to handle this case, but it did not account for multi-devices, so this expands the check to handle multi-devices that fall in this category as well.

Matter Switch: add handling for multi-On/Off Light Switch device types

---

drivers/SmartThings/matter-button/profiles/button-battery.yml
drivers/SmartThings/matter-button/profiles/button.yml

The icon for the RemoteController category is not a button icon. This commit changes the category for the single button profile among the matter-button profiles from RemoteController to Button.

matter-button: Change category for icon

---

drivers/SmartThings/matter-window-covering/src/init.lua
drivers/SmartThings/matter-window-covering/src/test/test_matter_window_covering.lua
drivers/SmartThings/zigbee-window-treatment/src/aqara/init.lua
drivers/SmartThings/zigbee-window-treatment/src/aqara/roller-shade/init.lua
drivers/SmartThings/zigbee-window-treatment/src/hanssem/init.lua
drivers/SmartThings/zigbee-window-treatment/src/test/test_zigbee_window_treatment_aqara.lua
drivers/SmartThings/zigbee-window-treatment/src/test/test_zigbee_window_treatment_aqara_roller_shade_rotate.lua
drivers/SmartThings/zigbee-window-treatment/src/test/test_zigbee_window_treatment_hanssem.lua

Some blind drivers have exposed unnecessary information to history. (bug2-1182)
modify the aqara and hansem blind drivers not to show some events
(for supportedWindowShadeCommands, supportedInitializedState)

BUG2-1182-fix: hide non functional attribute update 

---

drivers/SmartThings/zwave-switch/src/aeon-smart-strip/init.lua
drivers/SmartThings/zwave-switch/src/aeotec-smart-switch/init.lua
drivers/SmartThings/zwave-switch/src/dawon-smart-plug/init.lua
drivers/SmartThings/zwave-switch/src/dawon-wall-smart-switch/init.lua
drivers/SmartThings/zwave-switch/src/eaton-5-scene-keypad/init.lua
drivers/SmartThings/zwave-switch/src/eaton-accessory-dimmer/init.lua
drivers/SmartThings/zwave-switch/src/eaton-anyplace-switch/init.lua
drivers/SmartThings/zwave-switch/src/ecolink-switch/init.lua
drivers/SmartThings/zwave-switch/src/fibaro-double-switch/init.lua
drivers/SmartThings/zwave-switch/src/fibaro-single-switch/init.lua
drivers/SmartThings/zwave-switch/src/fibaro-wall-plug-us/init.lua
drivers/SmartThings/zwave-switch/src/init.lua
drivers/SmartThings/zwave-switch/src/inovelli-2-channel-smart-plug/init.lua
drivers/SmartThings/zwave-switch/src/inovelli-LED/init.lua
drivers/SmartThings/zwave-switch/src/multi-metering-switch/init.lua
drivers/SmartThings/zwave-switch/src/multichannel-device/init.lua
drivers/SmartThings/zwave-switch/src/qubino-switches/init.lua
drivers/SmartThings/zwave-switch/src/zooz-power-strip/init.lua
drivers/SmartThings/zwave-switch/src/zooz-zen-30-dimmer-relay/init.lua
drivers/SmartThings/zwave-switch/src/zwave-dual-switch/init.lua

Adds the ability to lazy load sub drivers. Sub driver that are not currently used by the driver will be "lazy loaded", meaning just a smaller version of the sub driver will be loaded until a device joins that requires the entire sub driver, at which point all the sub driver handlers will be loaded. Given the high number of sub drivers in the zwave-switch driver, this should provide a good amount of memory savings in cases where many of the sub drivers go unused.
Note, this will only work with the latest lua libs changes, so the lazy loading is only activated after an API version check.

Z-Wave Switch: lazy load sub drivers

---

drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-switch/src/eve-energy/init.lua

- Add Eve Energy Outlet fingerprint
- Only create the polls (create_poll_schedule and create_poll_report_schedule) if the device supports capabilities.powerConsumptionReport
- When the device is initialized, create child devices with the profile plug-binary for each additional outlet
- Update component_to_endpoint, endpoint_to_component and find_child to support multiple children
- Each time an oulet is turned on or off, store the value in a dictionary
- If one of the outlet is on, we should create the poll to monitor the power consumption
- If all the outlet are off, we should delete the poll

[Eve]: Support for Eve Energy Outlet

---

drivers/SmartThings/matter-switch/fingerprints.yml

This PR was created to break out devices from this original PR. https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1186/files
This PR contains 9 GE Cync Bulbs for Matter WWST Certification that have a device firmware version of 1.01.060 currently and 1 Cync Outdoor Plug

New Device(Matter Switch) Cync Bulbs 1.01.060 and Outdoor Plug

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child.lua

There is a race condition where sometimes the initial subscription report will be handled before child devices are done being created. In this case, the child devices will not recieve the initial value of the attribute, and will appear as just "connected" or "waiting for device to update" until they are  manually refreshed or the state is physically toggled on the device.

Matter Switch: refresh child devices on added event

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/fields.lua
drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/hue/types.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/lunchbox/rest.lua
drivers/SmartThings/philips-hue/src/lunchbox/sse/eventsource.lua
drivers/SmartThings/philips-hue/src/utils.lua

This removes the API version guard on the auto add/delete scan during
event stream connection and instead skips to the next element in the
iterator if it detects that the current iteration target is a device
record that represents a bridge.
We do this because we *do* want the auto-add/auto-delete routine to
run on older firmware, as the delete function does feature detection
on the lua libs and uses `device:offline()` as a fallback. Plus, auto
add will work on all firmware versions, so this is the better UX all
around.
We also address some static analysis lints from the Lua Language Server
VS Code plugin.
Most of these are just refining/augmenting gradual typing to quiet the
IDE warnings, but there were a few places that we were missing nil
checks or otherwise had other potential bugs …

Skip processing Hue Bridges as deletion candidates + some static analysis cleanup

---

drivers/SmartThings/matter-switch/fingerprints.yml

This is a new WWST Certification Request for the Eve Energy Switzerland ModelNumber: 20ECL1301. The Matter Product ID for this device is 0x006A.

New Device (Matter Switch) Eve Energy Switzerland 0x006A

---

drivers/SmartThings/matter-switch/fingerprints.yml

This is a PR for a new WWST Certification request for an Eve Outdoor Device Model Number:  20ECM8301. The Product ID is: 006B.

New Device (Matter Switch) Eve Energy Outdoor 006B

---

drivers/SmartThings/philips-hue/src/disco.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/init.lua

The majority of these fixes are concurrency races:
Due to Hue's heavy usage of additional Cosock coroutines, it can be the
case that functions that have been passed references to device records
will be operating on a device record for a deleted device. This can cause
unexpected nil index errors and crashes.
We attempt to minimize that here with heuristics; in particular, a device
that has been deleted will return `nil` for *any* of its table keys. So
we check a field that we *know* a device record should have, its `.id` field.
We wrap all handlers in a closure that does a sanity check on the status of
the device record using this heuristic, and we wrap the handler itself in a
pcall.
We also address some one-off locations where nil field indexes can occur
for other reasons, and introduce …

fix(hue): Address various nil field index issues

---

drivers/SmartThings/matter-window-covering/fingerprints.yml

This PR is to add the fingerprint for two new Matter WWST Certification requests. 
I reviewed the product pages for the MT25B and MT82 devices. I believe that the MT25B device supports battery, and have fingerprinted that device to the window-covering-battery profile that supports the battery capability. I am following up with PSM to see if this adjustment should be made.

new device (Matter Window Covering): WWST Cert request to add the Zemismart MT25B, MT82, MT25A, ZM25M

---

drivers/SmartThings/matter-appliance/profiles/refrigerator-freezer.yml
drivers/SmartThings/matter-appliance/src/matter-refrigerator/init.lua

IOTE-3354
IOTE-3544
* Sometimes, device.endpoints loop is not working sequentially.
* Adding optional capability to make a superset profile (related to MTR-619)

matter-appliance: Improve refrigerator driver

---

drivers/SmartThings/matter-switch/profiles/light-color-level-2000K-7000K.yml
drivers/SmartThings/matter-switch/profiles/light-color-level.yml
drivers/SmartThings/matter-switch/profiles/light-level-ColorTemperature-1500-9000k.yml
drivers/SmartThings/matter-switch/profiles/light-level-colorTemperature.yml
drivers/SmartThings/matter-switch/profiles/light-level.yml

Updating the "light" matter profiles in the matter switch driver to set the supported range of switchLevel to 1-100 to resolve CHAD-12814. Devices supporting the lighting feature support a minimum value of 1, however, MinLevel is an optional attribute, so currently devices that do not supply this value may use a range of 0-100 even though 0 is not supported.

 Matter Switch: Set switchLevel range to 1-100 for light matter profiles

---

drivers/SmartThings/samsung-audio/README.md
drivers/SmartThings/samsung-audio/src/command.lua
drivers/SmartThings/samsung-audio/src/handlers.lua

Ticket: https://smartthings.atlassian.net/browse/BEE-4280
Currently, the notification could only be played with 'http' method. In order to make the TTS work uniformly, direct fallback method has been adopted to make it work without fail.

audio TTS fix on samsung speakers

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_lights.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_plugs.lua

Child device profiles will now be determined dynamically based on the device type of the child device endpoint. This will improve support for multi-devices.

Matter Switch: improve child device profile support

---

drivers/SmartThings/zigbee-illuminance-sensor/src/aqara/init.lua
drivers/SmartThings/zigbee-illuminance-sensor/src/test/test_illuminance_sensor_aqara.lua
drivers/SmartThings/zigbee-motion-sensor/src/aqara/high-precision-motion/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/aqara/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_aqara_high_precision.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_aqara_motion_illuminance.lua

Fix PLM P240314-06959
There is a problem about the unit translation of "stse.detectionFrequency" in ST App history.
Since "stse.detectionFrequency" history is not critical, ignore it first as a workaround.

Don't log stse.detectionFrequency changelog in ST App history

---

drivers/SmartThings/zigbee-motion-sensor/src/aqara/high-precision-motion/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/aqara/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_aqara_high_precision.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_aqara_motion_illuminance.lua

fix issue that motion detection doesn't work after reonboarding
When reonboard Aqara sensors when device card remain, added event
will not be called, synced with Aqara team, they suggest us to move
write_manufacturer_specific_attribute from added to doConfigure event

Move write_manufacturer_specific_attribute from added to doConfigure event

---

drivers/SmartThings/matter-switch/profiles/light-color-level.yml
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_light_illuminance_motion.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_lights.lua

When device is added, read the color temperature and level cluster min/max and set capability constraint based on the limits.

Matter Switch: Read color temp and level limits on add

---

drivers/SmartThings/zigbee-smoke-detector/src/aqara/init.lua
drivers/SmartThings/zigbee-smoke-detector/src/test/test_aqara_smoke_detector.lua

fix issue that smoke detection doesn't work after reonboarding
This is a fix for re-onboarding scenario:
WASH-2068
STSE-2611

fix aqara smoke detector reonboarding issue

---

drivers/SmartThings/zigbee-lock/src/samsungsds/init.lua
drivers/SmartThings/zigbee-lock/src/test/test_zigbee_samsungsds.lua

https://smartthings.atlassian.net/browse/CHAD-12999

[CHAD-12999] fix (Zigbee Lock): Ignore unknown status for sds lock

---

drivers/SmartThings/zigbee-button/src/aqara/init.lua
drivers/SmartThings/zigbee-button/src/test/test_SLED_button.lua
drivers/SmartThings/zigbee-button/src/test/test_aqara_button.lua
drivers/SmartThings/zigbee-button/src/test/test_wallhero_button.lua

This is a fix for STSE-2620. Added Test Coverage, but wallhero coverage may not be up to 90%. The function that did not coverage is init function. I cannot access by test using virtual devices.

fix Aqara Wireless Button E1 reonboarding issue

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_light_illuminance_motion.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_lights.lua

Subscribe to min/max color temperature and min/max switch level attributes rather than reading them during device init. This is to resolve an issue identified while investigating `InteractionQueueFull` spikes in the exception reports, where onboarding a large number of devices resulted in more attributes being read than the maximum number of attributes per read interaction (9). These attribute reads were split into multiple read requests, which exceeded the maximum number of concurrent requests (5), causing the remaining requests to be dropped.
Utilizing subscriptions for these attributes rather than manually querying the device will take advantage of the current optimizations for subscription requests and avoid this issue.

Matter-Switch: Limit reads subscriptions

---

drivers/SmartThings/philips-hue/PROGRESS.md
drivers/SmartThings/philips-hue/src/disco/init.lua
drivers/SmartThings/philips-hue/src/disco/light_disco.lua
drivers/SmartThings/philips-hue/src/init.lua

This is mostly a structural refactor as opposed to a functional one, but there are subtle changes.
First, we refactored the discovery module in to a directory, as we're going to be breaking the file up. The first extraction here is moving the handler for processing a discovered light in to its own file.
Next, we changed some names of some variables where it was assumed that we were working with lights; this is purely a comprehension/readability refactor.
The only functional change made here was a modification to the `supported_resource_types` mapping, which was originally just a map of booleans. This is now a map from a resource type to a handler function. In this case, we import the handler function from the new file mentioned above.

Refactor discovery for addition of new device types

---

drivers/SmartThings/philips-hue/src/handlers.lua
drivers/SmartThings/philips-hue/src/init.lua

Addition of 'setSaturation' and 'setHue' logic for Philips Hue Lights. The motvation towards this addition comes from the use of some clients that use setHue and setSaturation instead of setColor.

Addition of 'setSaturation' and 'setHue' logic for Philips Hue Lights

---

drivers/SmartThings/matter-switch/fingerprints.yml

This PR is a for a WWST Certification request for the Linkind LS0101911261 Smart Light Bulb A60

New Device (Matter Switch) Linkind Smart Light Bulb A60

---

drivers/SmartThings/zigbee-contact/src/multi-sensor/multi_utils.lua
drivers/SmartThings/zigbee-contact/src/test/test_smartsense_multi.lua

The `convert_to_signedInt16` function had a bug preventing it from handling large negative threeAxis values. This would impact the garage door handling since in the typical orientation the sensor will report approximately -1000 for the Z axis when the door is open.
https://smartthings.atlassian.net/browse/CHAD-13097

SmartSense Multi: Fix handling of large negative threeAxis values

---

drivers/SmartThings/harman-luxury/profiles/maX10.yaml

As told by @Seong-Yeol-Park eCode, AVRs like the ones this profile represent should be under the `Receiver` category instead of `Speaker`.

change JBL MA AVRs category to Receiver

---

drivers/SmartThings/zigbee-illuminance-sensor/src/aqara/init.lua
drivers/SmartThings/zigbee-illuminance-sensor/src/test/test_illuminance_sensor_aqara.lua

Fix possible reboarding issue
- move device settings to doConfigure

Fix possible re-onboarding issue

---

drivers/SmartThings/matter-switch/fingerprints.yml

This PR is to add two devices to WWST Certification. They will be Certified by Simularity. 
In the DCL the two devices are:
Nanoleaf Indoor Lights
VID:4442 (0x115a)
PID: 72 (0x48)
Device ID: 269 (0x10d)
Nanoleaf Outdoor Lights
VID:4442 (0x115a)
73 (0x49)
Device ID: 269 (0x10d)

New Devices (Matter Switch) Nanoleaf Indoor and Outdoor Lights

---

drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temp-battery-aqara.yml

new device category - TempHumiditySensor have been prepared.
So it's better to apply TempHumiditySensor category to Aqara Temperature Humidity Sensor.

Apply new TempHumiditySensor category to Aqara Temperature Humidity Sensor

---

drivers/SmartThings/matter-sensor/profiles/temperature-humidity-battery.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity-pressure-battery.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity-pressure.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity.yml
drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temp-battery.yml
drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temperature.yml
drivers/SmartThings/zwave-sensor/profiles/humidity-temperature-battery.yml

Updates certain profiles to use the new TempHumiditySensor category.
Includes the following profiles: 
drivers/SmartThings/matter-sensor/profiles/temperature-humidity-battery.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity-pressure-battery.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity-pressure.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity.yml
drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temp-battery.yml
drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temperature.yml
Note: drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temp-battery-aqara.yml was updated here: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1398 …

Update profile category to TempHumiditySensor where appropriate

---

drivers/SmartThings/matter-switch/fingerprints.yml

This is a WWST Cert Request, two of the three devices will be CxS. 
From the Matter DCL, here is additional information:
Device 1
Vendor ID | 5020 (0x139c)
Product ID | 53249 (0xd001)
Device Type ID | 269 (0x10d)
Device 2
Vendor ID | 5020 (0x139c)
Product ID | 53250 (0xd002)
Device Type ID | 269 (0x10d)
Device 3
Vendor ID | 5020 (0x139c)
Product ID | 53251 (0xd003)
Device Type ID | 269 (0x10d)

New Devices (Matter Switch) Zemismart Multiple Devices

---

drivers/SmartThings/matter-sensor/profiles/air-quality-sensor-temp-humidity-all-level-all-meas.yml
drivers/SmartThings/matter-sensor/profiles/air-quality-sensor-temp-humidity-all-level.yml
drivers/SmartThings/matter-sensor/profiles/air-quality-sensor-temp-humidity-all-meas.yml
drivers/SmartThings/matter-sensor/profiles/air-quality-sensor-temp-humidity-co2-pm25-tvoc-meas.yml
drivers/SmartThings/matter-sensor/profiles/air-quality-sensor-temp-humidity-tvoc-level-pm25-meas.yml
drivers/SmartThings/matter-sensor/profiles/air-quality-sensor.yml
drivers/SmartThings/matter-sensor/src/air-quality-sensor/init.lua
drivers/SmartThings/matter-sensor/src/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_air_quality_sensor.lua

This pull request contains updates to the matter-sensor driver to resolve issues for the IKEA air quality sensor with the latest matter 1.2 driver, as well as improvements to the profile selection logic.
[CHAD-13070](https://smartthings.atlassian.net/browse/CHAD-13070)
[CHAD-13070]: https://smartthings.atlassian.net/browse/CHAD-13070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Matter-Sensor: Improve AQS Profile Selection

---

drivers/SmartThings/philips-hue/profiles/legacy-color.yml
drivers/SmartThings/philips-hue/profiles/white-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white-and-color-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white.yml

Update Philips Hue light device profiles to reference device configurations that disable the light controls when it is in sync mode. This PR should not be merged until the device configurations have been deployed.

Disable hue light controls when in sync mode

---

drivers/SmartThings/philips-hue/profiles/legacy-color.yml
drivers/SmartThings/philips-hue/profiles/white-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white-and-color-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white.yml

This PR is to hot-release the profile changes to Hue for improved Sync support that landed in #1144.
`DO NOT MERGE` label is being held until other scheduled Tuesday deploys go out across the platform to mitigate load.

Beta release expedite: Disable hue light controls when in sync mode

---

drivers/SmartThings/philips-hue/profiles/legacy-color.yml
drivers/SmartThings/philips-hue/profiles/white-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white-and-color-ambiance.yml
drivers/SmartThings/philips-hue/profiles/white.yml

This PR is to hot-release the profile changes to Hue for improved Sync support that landed in #1144.
`DO NOT MERGE` label is being held until other scheduled Tuesday deploys go out across the platform to mitigate load.

Production release expedite: Disable hue light controls when in sync mode

---

drivers/SmartThings/philips-hue/src/disco/contact.lua
drivers/SmartThings/philips-hue/src/disco/light.lua
drivers/SmartThings/philips-hue/src/disco/motion.lua
drivers/SmartThings/philips-hue/src/handlers/attribute_emitters.lua
drivers/SmartThings/philips-hue/src/handlers/commands.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/bridge.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/contact.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/init.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/light.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/motion.lua
drivers/SmartThings/philips-hue/src/handlers/migration_handlers/bridge.lua
drivers/SmartThings/philips-hue/src/handlers/migration_handlers/light.lua
drivers/SmartThings/philips-hue/src/handlers/refresh_handlers.lua
drivers/SmartThings/philips-hue/src/hue/api.lua
drivers/SmartThings/philips-hue/src/hue_debug/init.lua
drivers/SmartThings/philips-hue/src/init.lua
drivers/SmartThings/philips-hue/src/lunchbox/sse/eventsource.lua
drivers/SmartThings/philips-hue/src/stray_device_helper.lua
drivers/SmartThings/philips-hue/src/utils/hue_bridge_utils.lua
drivers/SmartThings/philips-hue/src/utils/init.lua

We silenced some logging (both driver only and hubcore) because the driver was very chatty, but with the new release, we need to restore it.

chore: restore verbose Hue logs

---

drivers/SmartThings/zigbee-lock/fingerprints.yml
tools/localizations/cn.csv

The fingerprints of TOTEM Door Lock have already existed in the DTH(SmartThings Public). 
I tried to manage to migrate the fingerprints from DTH to Edge Driver.
Zigbee Device ID: "TOTEM H60/H90" & "TOTEM P30"

Add fingerprints of TOTEM Door Lock for SmartThingsEdgeDriver

---

drivers/SmartThings/matter-appliance/src/init.lua
drivers/SmartThings/matter-appliance/src/matter-dishwasher/init.lua
drivers/SmartThings/matter-appliance/src/matter-laundry-washer/init.lua
drivers/SmartThings/matter-rvc/src/init.lua

Currently, the endpoint is hardcoded to the matter default endpoint (1) for some of the appliance device types. This is the default assumption for simple single component devices. However, we should use the `component_to_endpoint` function instead for more robust endpoint handling. In these cases, `component_to_endpoint` will essentially call `find_default_endpoint` and return the first nonzero endpoint on the matter device. In many cases it could be 1, but this change will make the endpoint handling more generic.

Use component_to_endpoint to get default endpoint

---

drivers/SmartThings/matter-switch/fingerprints.yml

This PR is for a WWST CxS Submission for the following Matter Device 
Nanoleaf - Smart Holiday String Lights
VID: 4442 (0x115a)
PID:  71 (0x47)
According to the DCL this device has a device type = 10d

New Device (Matter Switch) NanoLeaf Smart Holiday String Lights

---

drivers/SmartThings/philips-hue/run_specs.sh
drivers/SmartThings/philips-hue/src/test/spec/device_faker.lua
drivers/SmartThings/philips-hue/src/test/spec/fakers/bridge_faker.lua
drivers/SmartThings/philips-hue/src/test/spec/fakers/driver_faker.lua
drivers/SmartThings/philips-hue/src/test/spec/fakers/light_faker.lua
drivers/SmartThings/philips-hue/src/test/spec/test_helpers/init.lua
drivers/SmartThings/philips-hue/src/test/spec/unit/utils_spec.lua
drivers/SmartThings/philips-hue/src/utils/init.lua

We don't run Busted tests in CI, but the Hue driver is now very testable after the recent refactor. The ability to write integration tests for LAN Drivers is still forthcoming, but we're also going to be accumulating unit tests for Hue going forward as well.
We keep the `spec` folder as a sibling to the `src` folder so that it doesn't get included in the driver package, so care should be taken when setting up the LUA PATH to run these tests.
We also fix a bug that was reported by some community users, the presence of which was validated by and is also now covered by the new specs.
The PR is broken up in to two commits. The first commits are all of the new Busted work. The second commit is the bugfix.

Busted tests for Hue driver + Bugfix for migrated lights

---

drivers/SmartThings/matter-appliance/src/matter-dishwasher/init.lua
drivers/SmartThings/matter-appliance/src/matter-laundry-washer/init.lua
drivers/SmartThings/matter-appliance/src/matter-refrigerator/init.lua

If two or more same application device types are connected, a conflict occurs in the list supported by the mode or temperature level. This patch is for fixing this part.

Store local variables by using set/get_field api

---

drivers/SmartThings/zigbee-lock/fingerprints.yml

Hi, @lelandblue @greens.
After the discussion between us and the TOTEM manufacturer, the TOTEM door lock, including H60, H90 and P30 does not support the 'lockCodes' and the 'firmwareUpdate' capabilities.
For this consideration, we adjusted the files as follows:
1. Create a new profile named 'totem-lock'
2. Change the fingerprints of the three types of TOTEM door locks from 'base-lock' to 'totem-lock'.
WWST link: https://smartthings.atlassian.net/browse/WWST-8010
PIOT link: https://smartthings.atlassian.net/browse/PIOT-139

Change the totem device profile

---

drivers/SmartThings/matter-pump/src/init.lua

This was accidentally missed in the initial commit. This adds the include for the embedded cluster defs in the situation that the hub is running older lua libs (api version < 10)

Matter Pump: add missing embedded cluster include

---

drivers/SmartThings/matter-window-covering/src/init.lua

Previously, the window covering driver was modified because the windowshade value was sometimes wrong.
And there was a part of mis-implementation.
So the issue was reported as below.
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/issues/1436
This is a patch that fix the issue.

Fix a part of mis-implementation for window covering device type

---

drivers/SmartThings/matter-appliance/src/matter-dishwasher/init.lua
drivers/SmartThings/matter-appliance/src/matter-laundry-washer/init.lua
drivers/SmartThings/matter-appliance/src/matter-refrigerator/init.lua
drivers/SmartThings/matter-rvc/src/init.lua
drivers/SmartThings/matter-thermostat/src/init.lua

Currently, The supportedXXX of mode and temperature level capability is updated to history. but It should be modified not to be updated.

Remove history of the Supported list

---

drivers/SmartThings/matter-thermostat/src/test/test_matter_air_purifier.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_room_ac.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat_composed_bridged.lua

Fixes some unit tests that were broken by the changes in this commit: e372124dddaf1d44ddedb08b3fb18fd261cfb2ea.
These changes were intentional, but the unit tests were not updated to reflect the changes.

Fix unit tests with supportedModes visibility

---

drivers/SmartThings/matter-switch/fingerprints.yml

This PR is for a WWST Certification request to add the Zemismart ZM606-3 device. According to the DCL it has a  device type of 0x103. 
Here is the VID and the PID for this device
- vendorId: 0x139C
- productId: 0xAB31

New Device (Matter Switch) Zemismart ZM606-3

---

drivers/SmartThings/matter-switch/fingerprints.yml

This PR is for a WWST Certification request to add the Zemismart ZM606-3 device. According to the DCL it has a device type of 0x103.

Matter Switch: add Zemismart ZM606-3 fingerprint

---

drivers/SmartThings/matter-switch/fingerprints.yml

This PR is for a WWST Certification request to add the Zemismart ZM606-6 device. According to the DCL it has a device type of 0x103.

Matter Switch: add Zemismart ZM606-6 fingerprint

---

drivers/SmartThings/matter-lock/fingerprints.yml
drivers/SmartThings/matter-lock/src/aqara-lock/init.lua
drivers/SmartThings/matter-lock/src/init.lua
drivers/SmartThings/matter-lock/src/lock_utils.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_cota.lua

Cherry pick matter lock aqara hotfix to beta
Revert Aqara matter-lock changes and move them to sub driver
This reverts commit d0a77c936e3ea9e7dfbf99220f3f0fa63051754b. 
This reverts commit 1f1df0610a47daca75913b0323774ef91a197f34. 
Add back profiles and fixes after moving Aqara to sub driver Add COTA recovery logic on init

Hotfix: Revert matter lock changes and move aqara to sub driver

---

drivers/SmartThings/matter-sensor/src/smoke-co-alarm/init.lua

Resubscribe whenever there is a profile switch so that new attributes can be subscribed to if the new profile includes new capabilities.

Matter Sensor: resubscribe on profile switch

---

drivers/SmartThings/matter-switch/fingerprints.yml

This PR is to add a fingerprint for a Matter Switch device:  Cync Full Color Deco Candle Base. In the DCL the Product ID for this device is 101 (0x65) and the Matter Device ID is  269 (0x10d).

New Device (Matter Switch) Cync Full Color Deco 

---

drivers/SmartThings/matter-switch/fingerprints.yml

This PR is for a WWST CERT submission for a multiple Matter Switch Devices their brands are related:  
1. Orien OS0100411267 
-- According to the DCL the PID = 1007 (0x3ef) and the Matter Device Type ID = 269 (0x10d)
2. Linkind LS01009110
-- According to the DCL the PID = 1005 (0x3ed) and the Matter Device Type ID = 269 (0x10d)
3. Orien OS01006110
-- According to the DCL the PID = 1006 (0x3ee) Matter Device Type ID = 269 (0x10d)
<br class="Apple-interchange-newline">
This will be CxS and merged / deployed after PR approval.

New Device (Matter Switch) Orein OS0100411267

---

drivers/SmartThings/matter-switch/fingerprints.yml

- [ **X** ] WWST Certification Request
- [  **X** ] I have performed a self-review of my code
This PR is adding 4 new devices to the Matter Switch Driver the devices are:
1. Cync Full Color A21 Model Number: CLEDA2116CDMS. According to the DCL:
PID: 0x0069
VID: 0x1339
Matter Device Type ID: 10D
2. Cync Full Color BR30 Model Number: CLEDR309CD1MS. According to the DCL:
PID: 0x00AD
VID: 0x1339
Matter Device Type ID: 10D 
3. Matter Smart Plug from Winees (owned by AiDot) Model Number WC0900184. According to the DCL: 
PID: 0x044E
VID: 0x1168
Matter Device Type: 10A 
4. Additional commit due to a recently opened WWSTCERT request for a Cync Reveal Full Color A19
- id: "4921/107"
deviceLabel: Cync Reveal Full Color A19
vendorId: 0x1339
productId: 0x006B
deviceProfileName: …

New Devices (Matter Switch) Cync Bulbs and Winees Plug

---

drivers/SmartThings/matter-switch/fingerprints.yml

This cherry-pick's the following PR's in to Beta ahead of the production release so that they will be hotfixed to production:
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1530
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1514
- https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1531
N/A

Cherry-pick WWST Matter Switch fingerprints in to Beta ahead of production

---

drivers/SmartThings/zigbee-window-treatment/src/aqara/aqara_utils.lua
drivers/SmartThings/zigbee-window-treatment/src/aqara/init.lua
drivers/SmartThings/zigbee-window-treatment/src/aqara/roller-shade/init.lua
drivers/SmartThings/zigbee-window-treatment/src/test/test_zigbee_window_treatment_aqara.lua
drivers/SmartThings/zigbee-window-treatment/src/test/test_zigbee_window_treatment_aqara_roller_shade_rotate.lua

- [ X ] Refactor
To prepare for the production release on Monday July 29, we need to revert changes merged to beta specific to PR [1494](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1494). There are open discussions on slack regarding a device failure. 
- This PR will not be tested specifically

Revert (Zigbee Window Treatment) Aqara/Roller Shade PR 1494

---

drivers/SmartThings/zigbee-power-meter/src/ezex/init.lua
drivers/SmartThings/zigbee-switch/src/aqara/init.lua
drivers/SmartThings/zigbee-switch/src/aqara/version/init.lua
drivers/SmartThings/zigbee-switch/src/ezex/init.lua
drivers/SmartThings/zigbee-switch/src/robb/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_robb_smarrt_2-wire_dimmer.lua
drivers/SmartThings/zigbee-switch/src/zigbee-metering-plug-power-consumption-report/init.lua

This emulated reset behavior is defined in the defaults, but some sub-drivers overwrote the defaults without including it.
Adds default emulated reset behavior to sub-drivers that chose to overwrite it.
Existing unit tests were not affected by this change

CHAD-13655 Add emulated reset implementation

---

drivers/SmartThings/matter-appliance/profiles/dishwasher-tn-tl.yml
drivers/SmartThings/matter-appliance/profiles/dishwasher-tn.yml
drivers/SmartThings/matter-appliance/profiles/dishwasher.yml
drivers/SmartThings/matter-appliance/profiles/laundry-washer-tl.yml
drivers/SmartThings/matter-appliance/profiles/laundry-washer-tn-tl.yml
drivers/SmartThings/matter-appliance/profiles/laundry-washer-tn.yml
drivers/SmartThings/matter-appliance/profiles/laundry-washer.yml
drivers/SmartThings/matter-appliance/profiles/refrigerator-freezer-tl.yml
drivers/SmartThings/matter-appliance/profiles/refrigerator-freezer-tn-tl.yml
drivers/SmartThings/matter-appliance/profiles/refrigerator-freezer-tn.yml
drivers/SmartThings/matter-appliance/profiles/refrigerator-freezer.yml
drivers/SmartThings/matter-rvc/profiles/rvc.yml
drivers/SmartThings/matter-rvc/src/init.lua

In the case of mode capability, presentation is implemented in the list display type.
Therefore, device configuration was added to support automation in the device type that supports the mode capability.

Add device configuration for supporting Routine

---

drivers/SmartThings/matter-appliance/src/matter-refrigerator/init.lua

Fix an issue that driver can't control temperature level.
this issue can occur according to the endpoint order in which the handler is called.
IOTE-4259

Fix an issue that temperature level can't be controlled

---

drivers/SmartThings/hub/config.yml
drivers/SmartThings/hub/fingerprints.yml
drivers/SmartThings/hub/profiles/hub-thing.yml
drivers/SmartThings/hub/profiles/refrigerator-hub.yml
drivers/SmartThings/hub/profiles/soundbar-hub.yml
drivers/SmartThings/hub/profiles/tv-hub.yml

Adding some basic profiles for 4 types of hubs:
1. Refrigerator
2. TV Hub
3. Soundbar
4. Everything else

[HCS-5080] Add hub drivers for TV, Fridge, Soundbar, and all other types

---

drivers/SmartThings/philips-hue/src/hue_driver_template.lua
drivers/SmartThings/philips-hue/src/init.lua

This change calls `datastore:commit()` every time a Hue Bridge API key is captured/modified/removed. This is an API that's gated behind a SmartThings controlled allowlist, so it will not currently work until the Hue driver has been added to the allowlist. But I have tested that it does not cause a crash or issues with the driver's operation in any way, so the change is safe.
Real device developer testing has been performed.

Add datastore:commit() calls around API key operations

---

drivers/SmartThings/matter-thermostat/fingerprints.yml

This is a new Matter WWST request for a Eve Thermostat. The product ID for this device is "79 (0x4f)" and has a matter device type id of "769 (0x301)".

New Device (Matter Thermostat) Eve Thermostat

---

drivers/SmartThings/hub/fingerprints.yml

Changed hub driver fingerprints - specifically the hardwareType used by the tv-hub and soundbar-hub.

[HCS-5080] Change hardwareType used for hub fingerprints

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/zigbee-switch/src/init.lua
drivers/SmartThings/zwave-bulb/src/init.lua
drivers/SmartThings/zwave-switch/src/init.lua

Only switch and switchLevel capabilities will be supported for Matter, Zigbee, and Z-Wave devices in the 0.54.x firmware. Using this functionality give a huge latency improvement for handling these capability commands which is important when a driver is handling several commands all at once (i.e. a routine is triggered that toggles a bunch of switches). 
These changes are backwards compatible with old FW so we can get them released prior to the hub FW being released (and should to ensure we get runtime during customer beta for 0.54)
* Tested on 0.53 FW

Enable native handlers for drivers that can use them

---

drivers/SmartThings/matter-button/profiles/5-button-battery.yml
drivers/SmartThings/matter-button/profiles/5-button.yml
drivers/SmartThings/matter-button/src/init.lua
drivers/SmartThings/matter-button/src/test/test_matter_button_parent_child.lua

There are some 5-button Matter devices out there so the addition of the 5-button profiles will allow those devices to join as a single multi-component device instead of a parent/child device.
https://smartthings.atlassian.net/browse/CHAD-13761

Matter Button: Add profile for 5-button devices

---

drivers/SmartThings/matter-switch/fingerprints.yml

This device is pursuing WWST Certification. It is not published in the DCL, however on the CSA website this[ information was available](https://csa-iot.org/csa_product/cync-indoor-plug-3/). 
When I looked at the PICS documents for this device, in the on/off cluster test plan I see "Level Control for Lighting Matter_App_Clusters_1.5.4. O true". I concluded based on that information that this device supports Level Control and therefor the SwitchLevel capability withen the `deviceProfileName: plug-level`.

New Device (Matter Switch) Cync Indoor Plug CPLGSTDBLW1MS

---

drivers/SmartThings/matter-switch/fingerprints.yml

- [  X] Release
There are no additional changes between main and beta currently beyond the fingerprint addition for the  Cync Indoor Plug that recently passed WWST. I would like to do a release now to prevent a potential cherry pick later.

Moving Main to Beta to support WWST Cync Indoor Plug CPLGSTDBLW1MS Early

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_plugs.lua

[CHAD-13811](https://smartthings.atlassian.net/browse/CHAD-13811)
Add the ability to override the child profile that would be assigned based on the child's device type. This is done because some devices have the "On/Off Plug" device type, but it would make more sense for them to appear with the switch icon as indicated in their WWST fingerprint.
A unit test has been added to test this behavior.
Additionally, testing was done with the Sonoff 3-key switch, which is a device that would need a child profile override to show up correctly. This is because the child devices have the "On Off Plug" device type (which is correct in this case), but it would make more sense for this device to appear with our `switch` icon rather …

Matter Switch: add child profile overrides

---

drivers/SmartThings/matter-lock/fingerprints.yml
drivers/SmartThings/matter-lock/src/aqara-lock/init.lua

* new-device-Matter-Lock-Aqara-U300
* Matter Lock: add Aqara U300 to Aqara Lock sub driver
* Remove product ID from aqara-lock sub driver, use vendor id only
---------

Cherry-pick WWSTCERT-3390 into Beta ahead of production

---

drivers/SmartThings/matter-lock/src/aqara-lock/init.lua
drivers/SmartThings/matter-lock/src/init.lua
drivers/SmartThings/matter-lock/src/test/test_aqara_matter_lock.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock.lua

Previously we were mapping the 'not fully locked' to 'unknown' but now that the lock attribute has the 'not fully locked' variant we can expose that directly.
https://smartthings.atlassian.net/browse/CHAD-11259
Tested with a Yale Matter lock

matter-lock: Expose 'not fully locked' when reported by the lock

---

drivers/SmartThings/matter-lock/fingerprints.yml
drivers/SmartThings/matter-lock/src/aqara-lock/init.lua
drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-sensor/profiles/motion.yml
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua
drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_air_purifier.lua

Rolling up main into beta

---

drivers/SmartThings/matter-sensor/profiles/temperature-humidity-battery.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity-pressure-battery.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity-pressure.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity.yml
drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temp-battery.yml
drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temperature.yml
drivers/SmartThings/zwave-sensor/profiles/humidity-temperature-battery.yml

Updates profile to show both temperature and humidity on the device card for zigbee humidity/temperature sensors.

BUG2-2243 Add composite display to zigbee humidity sensors

---

drivers/SmartThings/matter-lock/profiles/base-lock.yml
drivers/SmartThings/matter-lock/profiles/lock-lockalarm-nobattery.yml
drivers/SmartThings/matter-lock/profiles/lock-lockalarm.yml
drivers/SmartThings/matter-lock/profiles/lock-nocodes-notamper.yml
drivers/SmartThings/matter-lock/profiles/lock-without-codes.yml

Without this change the 'not fully locked' was being displayed but without the correct translations.
https://smartthings.atlassian.net/browse/CHAD-11259
Tested with a Yale lock

matter-lock: Add 'not fully locked' to the embedded device config

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/multi-switch-no-master/init.lua

This cherry-picks the following PR to Beta ahead of the production release:
* https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1604

Cherry-pick WWST SiHAS buttons to beta before production release

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua

[CHAD-13828](https://smartthings.atlassian.net/browse/CHAD-13828)
This change adjusts the way that the color temperature bounds are rounded while converting them from mireds into Kelvin. Previously, they were rounded to the nearest hundreds value and this sometimes resulted in the range displayed in the ST app being larger than the range supported by the device. This change will prevent this from occurring by shortening the range, if needed, to always be within the range supported by the device.
See [here](https://smartthings.atlassian.net/wiki/spaces/CHIP/pages/3386376304/Color+Temperature+Range+Selection+Proposal) for a comparison of the current rounding method to the method proposed by this PR.
Note that the `mired_to_kelvin` function is …

Matter-Switch: Improve color temp conversion rounding

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/aqara/init.lua
drivers/SmartThings/zigbee-switch/src/aqara/multi-switch/init.lua
tools/localizations/cn.csv

Aqara smart wall switch T1

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding two unique fingerprints for CSA Certified Matter devices, with the Matter device type id of 268 (0x10c). 
Device 1:
vendorId: 0x1168
productId: 0x03FB
Device 2:
vendorId: 0x1168
productId: 0x03FC
Provided by partner using the ATS, no further testing will occur

New Devices (Matter Switch) AiDot Orein St58CCT Bulbs 

---

drivers/SmartThings/philips-hue/src/handlers/attribute_emitters.lua
drivers/SmartThings/philips-hue/src/handlers/commands.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/init.lua
drivers/SmartThings/philips-hue/src/handlers/refresh_handlers.lua
drivers/SmartThings/philips-hue/src/hue_driver_template.lua
drivers/SmartThings/philips-hue/src/stray_device_helper.lua
drivers/SmartThings/philips-hue/src/utils/init.lua

This fixes an edge case where we were assuming that a persistent field on a device was always present; while this should more or less hold true, there are times when it won't. In those cases, the driver would crash.
Drivers in this state would already be nonfunctional, but we want to avoid chewing up resources with a hot crash loop.
I tested this locally by onboarding my Hue setup and then deliberaly taking actions that would lead to the persisted fields getting blown away; the driver is nonfunctional, but no longer hits a hot crash loop.

fix: Avoid a nil index crash when data loss occurs

---

drivers/SmartThings/zigbee-lock/src/test/test_zigbee_yale.lua
drivers/SmartThings/zigbee-lock/src/yale/init.lua

When setting the code at index 0 for yale locks, the MASTER_CODE user type should be sent.

Yale Zigbee Locks: Use MASTER_CODE user type

---

drivers/SmartThings/virtual-switch/profiles/virtual-dimmer-switch.yml
drivers/SmartThings/virtual-switch/profiles/virtual-dimmer.yml
drivers/SmartThings/virtual-switch/profiles/virtual-switch.yml
drivers/SmartThings/virtual-switch/src/init.lua
drivers/SmartThings/virtual-switch/src/test/test_virtual_switch.lua

Adds a new certified preference 'forceStateChange' that allows users to select whether they want their virtual device events to always be a state change or not.

CHAD-13777 Allow virtual device events to not always be a state change

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch_device_types.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_lights.lua

[PR 1547](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1547) introduced a minor regression where the device endpoints are not being sorted before creating child devices. This is causing labels for child devices to be incorrect in some cases, as in [MTR-828](https://smartthings.atlassian.net/browse/MTR-828).
A new test case was added to verify that child devices are created in order of their endpoints. The child devices listed in the mock device are in a different order than their endpoints sequentially, but they are created in the correct order. This test case fails without this change.
[MTR-828]: https://smartthings.atlassian.net/browse/MTR-828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …

Sort endpoints before initializing switch

---

.github/workflows/create-channel.yml
.github/workflows/delete-channel.yml

As the number of channels has grown, it sometimes takes the API longer than 5s to return all the channels. This should be a little bandage on that issue.

CI: Increase timeout for getting all channels

---

drivers/SmartThings/zwave-switch/fingerprints.yml

- [  X] Refactor
This PR is a request of @Brianj94 on behalf of Jasco. There are two existing fingerprints that need a device label name change only.
id: 0063/4944, current device label   `GE Dimmer Switch`, to JascoPro In-Wall Dimmer
id: 0063/4952, current device label `deviceLabel: GE Switch`, to Jasco Pro In-Wall Switch
No tests completed beyond unit tests

Device Label (Z-Wave Switch) for two devices

---

drivers/SmartThings/matter-sensor/src/embedded-cluster-utils.lua

Adds the BooleanStateConfiguration to the cluster list in the embedded cluster utils so that get_endpoints() calls will work correctly on hub running older lua libs.
Resolves [CHAD-14121](https://smartthings.atlassian.net/browse/CHAD-14121)
Each of the boolean sensors were testing on a hub running 53 lua libs to confirm that the embedded clusters are working as expected and the device joins to the correct profile:
- Water Freeze Detector
- Water Leak Detector
- Rain Sensor
[CHAD-14121]: https://smartthings.atlassian.net/browse/CHAD-14121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Matter Sensor: add BooleanStateConfiguration in embedded cluster utils

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua

[CHAD-14135](https://smartthings.atlassian.net/browse/CHAD-14135)
The driver currently attempts to only read `MinSetpointDeadBand` once during the first time `device_init` is called, but the `MIN_SETPOINT_DEADBAND_CHECKED` field is not persisted, so the read request is sent during each device init. This is contributing to a spike in `InteractionQueueFull` exceptions. This change ensures that the field is persisted so that the read request is only sent once.
Added unit test to verify that the `MIN_SETPOINT_DEADBAND_CHECKED` flag is set after the `MinSetpointDeadBand` attribute is received to ensure that this value is only read one time.
Tested with a VDA bridge consisting of 20 thermostats and 20 color temperature lights to ensure that no …

Prevent multiple reads of MinSetpointDeadBand

---

drivers/SmartThings/philips-hue/src/hue_driver_template.lua
drivers/SmartThings/philips-hue/src/init.lua

The Lua commit function checks for the existence of the upstream commit RPC, but on very old hubs that are still active, this method doesn't exist on the libs side.

fix: Check that commit method exists

---

.github/workflows/run-tests.yml

The version of `luacov-cobertura` on Luarocks is no longer available on `github`, and the rockspec we're downloading uses the GitHub source URL in its source definition, so we're failing to acquire it.
There's an alternative rockspec for this package, that's even recommended by the README of `luacov`, but it's not on Luarocks. So we acquire it from its release tag on GitHub.
The `sed` one-liners are because the rockspec from the tag reference the artifact from `master` instead of the artifact from the tag itself, and the version number wasn't properly incremented.
**This will need to be hotfixed to Beta and Prod once we're happy with it**

fix: luacov-cobertura dependency acquisition

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_electrical_sensor.lua

The Electrical Energy Measurement cluster and Electrical Power Measurement cluster report readings in mWh and mW respectively, but SmartThings uses W and Wh for our capabilities. This change converts the read values into those of the correct unit. 
Unit tests were converted to match the new system.
See user testing reports in [this Slack page](https://smartthings.slack.com/archives/CDNPD1P8Q/p1728941844831519):

Convert Power and Energy reads from mW(h) to W(h). 

---

drivers/SmartThings/matter-lock/fingerprints.yml
drivers/SmartThings/matter-lock/profiles/base-lock-nobattery.yml
drivers/SmartThings/matter-lock/profiles/lock-without-codes-nobattery.yml
drivers/SmartThings/matter-lock/src/init.lua
drivers/SmartThings/matter-lock/src/test/test_bridged_matter_lock.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_cota.lua

Jira ticket showing mis-profiling of a bridged door lock: https://smartthings.atlassian.net/browse/MTR-821
Further, there is a general ticket on adding dynamic profiling to this driver: https://smartthings.atlassian.net/browse/CHAD-13948
This logic will permit dynamic profiling on the base-lock profile depending on the Power Source cluster, and will ignore devices that do not auto-profile as base-lock.
Unit tests
Bridged Switchbot device - Passed
VDA Door Lock - Passed
VDA Door Lock (Lock Codes) - Passed
Yale Assure Matter Lock - Passed

Add Dynamic Battery Support for Base-Lock Profiled Door Lock Devices 

---

drivers/SmartThings/matter-switch/src/init.lua

Per the [spec](https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/LevelControl.adoc#71-movetolevel-command), the rate value should be sent over as nil if it is not filled.
Tested on-device

let cmd.args.rate be nil

---

drivers/SmartThings/philips-hue/src/consts.lua
drivers/SmartThings/philips-hue/src/fields.lua
drivers/SmartThings/philips-hue/src/handlers/attribute_emitters.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/light.lua
drivers/SmartThings/philips-hue/src/types.lua

Adds dynamic constraint ranges to the `switchLevel` and the
`colorTemperatureLevel` capabilities, now that they're fully rolled out.
Existing light devices will update these ranges the next time they emit a
capability attribute event for the given capability. New devices will
emit these during onboarding.

feat: Hue dynamic constraints

---

drivers/SmartThings/matter-switch/src/init.lua

[CHAD-14220](https://smartthings.atlassian.net/browse/CHAD-14220)
When the button driver was merged into the switch driver, the old paths for cluster type definitions for the Switch cluster were updated to use the new paths defined in the lua libs. For example, `clusters.Switch.types.SwitchFeature.MOMENTARY_SWITCH` was changed to `clusters.Switch.types.Feature.MOMENTARY_SWITCH`. However, hubs running firmware 52 or below still use the old path which results in the driver not being able to find the type definition.
Using the new paths for existing cluster definitions is common in other drivers, however in all of these cases, embedded cluster definitions were included so this issue was not noticed before.
A Color Temperature Light was tested …

Matter Switch: Use previous cluster feature path name

---

drivers/Aqara/aqara-presence-sensor/search-parameters.yml

The mDNS service name of the actual Aqara FP2 is “_Aqara-FP2. _tcp".
if the search parameter is "_Aqara-FP2. _tcp", the driver is executed in V3 and SmartThings Station, but not in the hub on the monitor.
if the search parameter is "_aqara-fp2. _tcp", the driver is executed in the hub on the monitor, but not in V3 and SmartThings Station.
if the search parameter contains both “_Aqara-FP2. _tcp” and “_Aqara-fp2. _tcp”, the driver runs well in both v3, station, and hub on the monitor.
complete fp2 registration test on hub on monitor M5, v3, smartthings station

fp2: add lowercase search parameter

---

drivers/Aqara/aqara-presence-sensor/search-parameters.yml
drivers/SmartThings/matter-switch/fingerprints.yml

Cherry pick just #1722, #1653, and #1717 from beta to production.

Expedite fingerprints and Aqara change to production

---

drivers/SmartThings/hub/profiles/hub-thing.yml
drivers/SmartThings/hub/profiles/refrigerator-hub.yml
drivers/SmartThings/hub/profiles/soundbar-hub.yml
drivers/SmartThings/hub/profiles/tv-hub.yml

Plugin team want to apply an unified plugin for all hubs in R4.
For that, deviceConfig(new key&value and mandatory things) should be added in all hub's presentation.
※deviceConfig(icons / dashboard / dpInfo)

Add deviceConfig in hub profiles for plugin unification

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua

There's a issue that if the setpoint is set to a value which is in the deadband range, the setpoint of device isn't set to the value and the setpoint of SmartThings plugin keeps the value.
You can refer to below link for detail.
https://smartthings.atlassian.net/browse/IOTE-4626

Set setpoint to original value

---

drivers/SmartThings/matter-appliance/src/init.lua
drivers/SmartThings/matter-appliance/src/matter-dishwasher/init.lua
drivers/SmartThings/matter-appliance/src/matter-laundry/init.lua
drivers/SmartThings/matter-appliance/src/matter-oven/init.lua
drivers/SmartThings/matter-appliance/src/matter-refrigerator/init.lua
drivers/SmartThings/matter-appliance/src/test/test_dishwasher.lua
drivers/SmartThings/matter-appliance/src/test/test_laundry_dryer.lua
drivers/SmartThings/matter-appliance/src/test/test_oven.lua
drivers/SmartThings/matter-appliance/src/test/test_refrigerator.lua
drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua

If the unit value is changed in the cloud and then the setpoint value is changed, there is an issue of out of range. For the information, you can refer to the link below.
https://smartthings.atlassian.net/browse/IOTE-4629

Set setpointRange when setpoint is set

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-switch/fingerprints.yml

This PR is in support of 3 new WWST Certification Request(s)
1.   deviceLabel: RFGB-40B(W)/MT, by Elko that has a Matter Device Type ID of (0xf)
2.  deviceLabel: RFWD-100/MT, by Elko, that has a Matter Device Type ID of (0x15)
3.   deviceLabel: RFSAI-62B-SL/MT, by Elko, that has a Matter Device Type ID of (0x100) according to the DCL
Please review the profile assignments. 
These devices may have to be broken up in to multiple PRs later but for now I kept them (to avoid merge conflicts) as one but am open to breaking them up if needed.

New Devices (Matter Switch and Matter Sensor) 4 Elko devices

---

drivers/SmartThings/zigbee-valve/src/ezex/init.lua
drivers/SmartThings/zigbee-valve/src/init.lua
drivers/SmartThings/zigbee-valve/src/test/test_ezex_valve.lua

This valve uses the IAS Zone Status to report low battery and does not otherwise support the PowerConfiguration cluster, which is usually used for reporting the battery. The porting work done for the DTH missed this behavior.

CHAD-14369 Add ezex valve sub-driver

---

drivers/Aqara/aqara-presence-sensor/src/discovery.lua
drivers/Aqara/aqara-presence-sensor/src/fp2/api.lua
drivers/Aqara/aqara-presence-sensor/src/fp2/device_manager.lua
drivers/Aqara/aqara-presence-sensor/src/fp2/discovery_helper.lua
drivers/Aqara/aqara-presence-sensor/src/init.lua
drivers/Aqara/aqara-presence-sensor/src/lunchbox/rest.lua
drivers/Aqara/aqara-presence-sensor/src/lunchbox/sse/eventsource.lua

**fp2: add get_credential failure handling** 
When 403 error occurs after get_credential during device registration, the driver is waiting for socket timeout to occur while calling fill_body().
In the event of a 403 error, there is no need to fill the body, so in this case, the fill_body() is not called and treated as an error so that a quick return can be made.
This will help users with multiple devices quickly register their devices.
In addition, the log was changed more clearly when get_creditial failed.
**fp2: add nil check in eventsource**
add nil check for sock.
As shown below, there was a driver restart due to sock nil, so there was a request for modification.
2024-11-14_05:01:00.094 | E | edi | <Aqara Presence …

Fp2:Stabilization of connection and addition of convenience functions

---

drivers/Aqara/aqara-presence-sensor/src/discovery.lua
drivers/Aqara/aqara-presence-sensor/src/fp2/api.lua
drivers/Aqara/aqara-presence-sensor/src/fp2/device_manager.lua
drivers/Aqara/aqara-presence-sensor/src/fp2/discovery_helper.lua
drivers/Aqara/aqara-presence-sensor/src/init.lua
drivers/Aqara/aqara-presence-sensor/src/lunchbox/rest.lua
drivers/Aqara/aqara-presence-sensor/src/lunchbox/sse/eventsource.lua
drivers/SmartThings/matter-window-covering/fingerprints.yml
tools/localizations/cn.csv

Rolling up main to beta

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding a new fingerprint for the  Cync Reveal Full Color A21 device. This device will be CxS. According to the Matter DCL this device is certified as a Matter device type = (0x10D)

New Device (Matter Switch) Cync Reveal Full Color A21

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-switch/fingerprints.yml

This PR is for  seperate WWST Requests but they will follow the same release timing so I have added them together. 
1. Zemismart Wifi Switch, which has a Matter Device ID in the DCL as (0x103)
2. Zemismart Wifi Smart Switch , which has a Matter Device ID in the DCL as (0x103)
3. Heiman CO Sensor, which has a Matter Device ID in the DCL as (0x76)

New Devices (Matter Switch + Matter Sensor) 1 Heiman Co Sensor and 2 Zemismart Devices

---

drivers/SmartThings/zigbee-switch/src/aqara-light/init.lua
drivers/SmartThings/zigbee-switch/src/preferences.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_led_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_light.lua

This pull-request fixes Aqara Dimmer Controller T1 Pro blinking issue (STSE-3372)
Test has done with
- Aqara Dimmer Controller T1 Pro
- Aqara LED Bulb T1

STSE-3372: fix Aqara dimmer blinking

---

drivers/SmartThings/zigbee-lock/src/init.lua

Fixes a crash seen when some locks report an invalid value for the LockState

CHAD-12279 Some zigbee locks reporting invalid lockStates

---

drivers/SmartThings/matter-thermostat/src/init.lua

[CHAD-14525](https://smartthings.atlassian.net/browse/CHAD-14525)
Add a check that a non-nil value was recieved before using the value to avoid an error with trying to divide a nil value.
Tested with VDA bridged thermostat devices.
[CHAD-14525]: https://smartthings.atlassian.net/browse/CHAD-14525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Matter Thermostat: check for nil in temp attribute handler

---

drivers/SmartThings/zwave-smoke-alarm/src/fibaro-smoke-sensor/init.lua

This is done to get some memory and latency performance increases. Tested with the Orvibo gas detector.

Remove health_check functionality from zigbee-smoke-detector

---

drivers/SmartThings/matter-switch/profiles/plug-button.yml

[CHAD-14507](https://smartthings.atlassian.net/browse/CHAD-14507)
Add a new profile in the matter-switch driver for NEO plug + button device (see WWSTCERT-4757). Note that this profile was originally going to be added by [PR 1799](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1799), but that PR was split into two, so that the profile could be expediated into production to support the WWST certification.
[CHAD-14507]: https://smartthings.atlassian.net/browse/CHAD-14507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add profile for NEO SmartPlug/Button device

---

drivers/Aqara/aqara-presence-sensor/src/fp2/api.lua
drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-switch/profiles/plug-button.yml
drivers/SmartThings/matter-window-covering/fingerprints.yml
drivers/SmartThings/zigbee-lock/fingerprints.yml
drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/multi-switch-no-master/init.lua
tools/deploy.py
tools/localizations/cn.csv

Expedite changes to beta for 12-09-2024 production release

---

drivers/SmartThings/zigbee-thermostat/src/init.lua

This is not needed to keep device online, and so its being removed to gain the small memory/latency savings of having it disabled. Tested with a Sinope thermostat.

Remove health check from zigbee thermostat

---

drivers/SmartThings/matter-switch/src/test/test_matter_multi_button_switch_mcd.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch_device_types.lua
drivers/SmartThings/zigbee-switch/src/test/test_all_capability_zigbee_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_led_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_light.lua
drivers/SmartThings/zigbee-switch/src/test/test_rgb_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_rgbw_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_zll_rgbw_bulb.lua
drivers/SmartThings/zwave-switch/src/test/test_fibaro_walli_double_switch.lua
drivers/SmartThings/zwave-switch/src/test/test_zooz_double_plug.lua

This fixes unit tests to reflect new native handlers released in 0.55 FW/api v12 lua libs (Note we still need to enable colorTemperature and colorControl cmd registration in the matter-switch driver).
There was also an integration test framework bug that was fixed in api v12, that caused some tests to fail that should have never been passing (related to native handler registration for parent child/ mcd device)
One other test started failing with the integration test framework bugfix that needs analysis by someone more familiar with the matter profile switching

Chore/fixup unit tests for 0.55 api v12 release

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-switch/fingerprints.yml

- [ X  I have performed a self-review of my code
This PR is adding multiple NEO devices for WWST. Its possible more devices will be added to this PR. 
Motion Sensor: Matter Device Type  (0x107), with a PID of (0x0463)
Door Sensor: Matter Device Type (0x15), with a PID of (0x462)
Power Plug: Matter Device Type (0x10A), with a PID of ( 0x027B)
ATS Only

New Device (Matter Sensor + Matter Switch) Neo

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat_composed_bridged.lua

Based on [MTR-878](https://smartthings.atlassian.net/browse/MTR-878) there is a typo in the thermostat driver for setting the automode feature.
[MTR-878]: https://smartthings.atlassian.net/browse/MTR-878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Thermostat Auto setting in Matter Thermostat 

---

drivers/SmartThings/matter-lock/profiles/lock-unlatch.yml
drivers/SmartThings/matter-lock/profiles/lock-user-pin-schedule-unlatch.yml
drivers/SmartThings/matter-lock/profiles/lock-user-pin-unlatch.yml
drivers/SmartThings/matter-lock/profiles/lock-user-schedule-unlatch.yml
drivers/SmartThings/matter-lock/profiles/lock-user-unlatch.yml
drivers/SmartThings/matter-lock/src/new-matter-lock/init.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_unlatch.lua
drivers/SmartThings/matter-lock/src/test/test_new_matter_lock.lua

To support the Unbolt feature
https://smartthings.atlassian.net/browse/CPBLTS-2481

Add Unlatch command and Unlatched status (Unbolt feature)

---

drivers/SmartThings/matter-lock/profiles/lock-user-pin-battery.yml
drivers/SmartThings/matter-lock/profiles/lock-user-pin-batteryLevel.yml
drivers/SmartThings/matter-lock/profiles/lock-user-pin-schedule-battery.yml
drivers/SmartThings/matter-lock/profiles/lock-user-pin-schedule-batteryLevel.yml
drivers/SmartThings/matter-lock/src/new-matter-lock/init.lua
drivers/SmartThings/matter-lock/src/test/test_new_matter_lock_battery.lua

https://smartthings.atlassian.net/browse/IOTE-4705

Update matter-lock driver for U-tec

---

drivers/SmartThings/matter-sensor/src/air-quality-sensor/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_air_quality_sensor.lua
drivers/SmartThings/matter-thermostat/src/init.lua

[CHAD-14452](https://smartthings.atlassian.net/browse/CHAD-14452)
TVOC measurements are typically under 1 ppm for normal conditions for indoor air quality (see [here](https://smartthings.atlassian.net/wiki/spaces/STSE/pages/2556166348/airQualitySensor+enhancement+-+cancelled#Indoor-Air-Quality-(IAQ))). Rounding to the nearest 0.5 ppm is therefore not the most accurate representation and ppb should be used instead.
See testing info in the ticket as well as new unit test.
[CHAD-14452]: https://smartthings.atlassian.net/browse/CHAD-14452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use PPB for TVOC measurement units

---

drivers/SmartThings/matter-switch/fingerprints.yml

This PR adds Four new Fingerprints for the following devices:
1. Aqara LED Bulb T2 CCT, Matter Device Type ID: 10c
2. Aqara LED Bulb T2 RGB CCT, Matter Device Type ID: 10d
3. Aidot OREiN Matter Smart Light Bulb BR30 RGBTW 1200lm, Matter Device Type ID: 10d
4. Aidot Linkind Matter Smart Light Bulb BR30 RGBTW 1200lm, Matter Device Type ID: 10d
Additionally I moved up the "AiDot fingerprints" to be in alphabetical order compared to the other MFG fingerprints and rearranged them to be ordered more by their ProductIDs.
No additional testing is planned

New Devices (Matter Switch) 2 Aqara 2 AiDot

---

drivers/SmartThings/matter-lock/src/new-matter-lock/init.lua

- Add VID/PID of eufy C34 to new-matter-lock sub-driver
- https://smartthings.atlassian.net/wiki/spaces/DLT/pages/3636429393/eufy+C34+door+lock+testing

Add eufy C34 to new-matter-lock driver

---

drivers/SmartThings/matter-lock/fingerprints.yml
drivers/SmartThings/matter-switch/fingerprints.yml

1. I am adding two new fingerprints for Matter Nuki Locks the devices are
a. Model Number: 221148, PID: 0x00C1, Matter Device Type ID: (0xa)
b.  Model Number: 221147, PID: 0x00B2, Matter Device Type ID: (0xa)
- Please note these devices will later re-certify under the new door lock experience
2. I also re-arranged the fingerprints in the Nuki section of the Matter lock to be organized by product ID

New Devices (Matter Lock) Nuki

---

drivers/SmartThings/matter-sensor/profiles/aqs-level.yml
drivers/SmartThings/matter-sensor/profiles/aqs-temp-humidity-all-level-all-meas.yml
drivers/SmartThings/matter-sensor/profiles/aqs-temp-humidity-all-level.yml
drivers/SmartThings/matter-sensor/profiles/aqs-temp-humidity-all-meas.yml
drivers/SmartThings/matter-sensor/profiles/aqs-temp-humidity-co2-pm25-tvoc-meas.yml
drivers/SmartThings/matter-sensor/profiles/aqs-temp-humidity-pressure-tvoc-meas.yml
drivers/SmartThings/matter-sensor/profiles/aqs-temp-humidity-tvoc-level-pm25-meas.yml
drivers/SmartThings/matter-sensor/profiles/motion-illuminance-temperature-battery.yml
drivers/SmartThings/matter-sensor/profiles/motion-illuminance-temperature.yml
drivers/SmartThings/matter-sensor/profiles/sensor.yml
drivers/SmartThings/matter-sensor/profiles/smoke-co-temp-humidity-comeas.yml

[CHAD-14584](https://smartthings.atlassian.net/browse/CHAD-14584)
Note: This is a profile-only change!
Adds temperatureOffset and relativeHumidityOffset preferences to profiles that support the temperatureMeasurement and relativeHumidityMeasurement capabilities.
This is a profile change only to add preferences.
Onboarded a device using one of the updated profiles (`aqs-temp-humidity-all-meas`) without the changes. Preferences were not visible in the "Settings" menu of the device card. Then, the driver was updated to the new profile with the preferences added from this PR. Confirmed that the preferences are now visible in the "Settings" menu of the device after the driver is updated. No reonboarding is needed.
[CHAD-14584]: …

Matter Sensor: add temp/humidity offset preferences to profiles

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua

[MTR-849](https://smartthings.atlassian.net/browse/MTR-849)
This change improves edge condition logic when a device sends a color temperature value at or beyond its limits in mireds and also when a capability command is received that is at or beyond the limits in Kelvin.
If a device reports a value at/beyond the limits determined by `ColorTempPhysicalMaxMireds`/`ColorTempPhysicalMinMireds`, the converted Kelvin value would exceed the rounded min/max kelvin values calculated by the driver. The current behavior results in the `colorTemperature` capability being emitted with a value beyond the limits allowed by the plugin, and causes an "Out of range" error in the plugin. Instead, the kelvin value emitted in the capability should be set to the …

Matter Switch: Improve color temp boundary logic

---

drivers/SmartThings/matter-hrap/capabilities/routerName.yml
drivers/SmartThings/matter-hrap/capabilities/routerState.yml
drivers/SmartThings/matter-hrap/capabilities/threadVersion.yml
drivers/SmartThings/matter-hrap/capabilities/wifiSsid.yml
drivers/SmartThings/matter-hrap/config.yml
drivers/SmartThings/matter-hrap/fingerprints.yml
drivers/SmartThings/matter-hrap/profiles/network-infrastructure-manager.yml
drivers/SmartThings/matter-hrap/profiles/thread-border-router.yml
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/init.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/server/attributes/BorderRouterName.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/server/attributes/InterfaceEnabled.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/server/attributes/ThreadVersion.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/server/attributes/init.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/types/Feature.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/types/init.lua
drivers/SmartThings/matter-hrap/src/WiFiNetworkManagement/init.lua
drivers/SmartThings/matter-hrap/src/WiFiNetworkManagement/server/attributes/Ssid.lua
drivers/SmartThings/matter-hrap/src/WiFiNetworkManagement/server/attributes/init.lua
drivers/SmartThings/matter-hrap/src/embedded-cluster-utils.lua
drivers/SmartThings/matter-hrap/src/init.lua
drivers/SmartThings/matter-hrap/src/test/test_network_infrastructure_manager.lua
drivers/SmartThings/matter-hrap/src/test/test_thread_border_router.lua

This includes support for the device types Network Infrastructure Manager and Thread Border Router. 
It includes embedded definitions of two clusters- WifiNetworkManagement and ThreadBorderRouterManagement (with only the pertinent sections added, and four custom capabilities, including routerState, routerName, threadVersion, and wifiSsid. All four of these return a string, and routerState uses a single enum value (off, enabled). 
For SSID's handling, there is a check for if the reported name is TLV null, in which it returns nothing. Then, it checks whether the input is a valid utf8 input. If so, it emits a capability with the given Ssid. If not, it reports a failure. This is expected, as any other service disocvery system would also be unable to display an Ssid if it was not written using …

Add initial driver support for HRAP devices

---

drivers/SmartThings/jbl/profiles/jbl.yml
drivers/SmartThings/jbl/src/init.lua
drivers/SmartThings/jbl/src/jbl/api.lua
drivers/SmartThings/jbl/src/jbl/capability_handler.lua
drivers/SmartThings/jbl/src/jbl/device_manager.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_codes.lua
drivers/SmartThings/matter-switch/profiles/3-button-battery-temperature-humidity.yml
drivers/SmartThings/matter-switch/profiles/light-power-energy-powerConsumption.yml
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_climate_sensor_w100.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_light_switch_h2.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua

Normal deploy from main branch to the Beta branch

Rolling Main to Beta 23-Jan

---

drivers/SmartThings/matter-switch/src/init.lua

This comment should not have been applied as a log statement- it would not be meaningful and would cause confusion in any logs.

Fixup: Remove unclear log statement and apply it as an internal driver comment 

---

drivers/SmartThings/matter-sensor/profiles/aqs-temp-humidity-co2-pm1-pm25-pm10-meas.yml
drivers/SmartThings/matter-sensor/src/air-quality-sensor/init.lua

This change adds a new profile in matter sensor to support an air quality sensor device with the following clusters:
- Air Quality Cluster
- PM 1.0 Measurement Cluster
- PM 2.5 Measurement Cluster
- PM 10 Measurement Cluster
- CO2 Measurement  Cluster
- Temperatrue Measurement Cluster
- Humidity Measurement Cluster
Needed by WWST cert request: [WWSTCERT-5427](https://smartthings.atlassian.net/browse/WWSTCERT-5427), but since this is a generic profile it may be used by other devices in the future as well.
[WWSTCERT-5427]: https://smartthings.atlassian.net/browse/WWSTCERT-5427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Create new profile for Air Quality Sensor

---

drivers/SmartThings/philips-hue/src/disco/button.lua
drivers/SmartThings/philips-hue/src/handlers/attribute_emitters.lua
drivers/SmartThings/philips-hue/src/handlers/refresh_handlers.lua
drivers/SmartThings/philips-hue/src/utils/hue_bridge_utils.lua
drivers/SmartThings/philips-hue/src/utils/init.lua

The recent release that un-stuck the onboarding of multi-component devices has revealed that there are several setups on the platform where users have "stale" multi-component devices in their inventories. These devices appear to no longer be joined to the Hue Bridge topology (perhaps they were deleted then re-onboarded), but have not been deleted from the Edge Driver. We're not sure what causes this yet, but we have seen it happen rarely. These crashes can impede proper driver functionality, as well as preventing cleanup code that *could* fix the inconsistent state from executing.
It's unclear how hubs ended up in this state, and it is difficult to reproduce. So this PR avoids crashing the driver when devices are in this …

fix(hue): Various nil index crashes for "stale" devices

---

drivers/SmartThings/matter-switch/fingerprints.yml

- [  X] I have performed a self-review of my code
Adding a fingerprint for a Matter Bridge device listed in the DCL with the Matter Device type = 14 (0xe)

New Device (Matter Switch) Eltako Matter Bridge

---

drivers/SmartThings/matter-lock/src/init.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_battery.lua
drivers/SmartThings/matter-lock/src/test/test_matter_lock_cota.lua

[CHAD-12161](https://smartthings.atlassian.net/browse/CHAD-12161)
Matter drivers currently assume that `BatPercentRemaining` is available if the `BAT` feature is supported, but this attribute is only optionally required if this feature is present. The changes in this PR improve the profile selection logic in matter-lock by reading the `AttributeList`, checking if `BatPercentRemaining` or `BatChargeLevel` is available, and then profiling the device as needed.
Note that these changes were originally in [PR 1796](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1796) but this PR was split up into 5 separate PRs, one for each affected driver.
Tested with a Yale lock. Relevant logs:
```
2025-01-30_19:39:40.041 | I | broker …
```

Add batteryLevel to matter lock

---

drivers/SmartThings/matter-sensor/profiles/contact-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/freeze-batteryLevel-fault-freezeSensitivity.yml
drivers/SmartThings/matter-sensor/profiles/freeze-batteryLevel-fault.yml
drivers/SmartThings/matter-sensor/profiles/freeze-batteryLevel-freezeSensitivity.yml
drivers/SmartThings/matter-sensor/profiles/freeze-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/humidity-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/illuminance-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/leak-batteryLevel-fault-leakSensitivity.yml
drivers/SmartThings/matter-sensor/profiles/leak-batteryLevel-fault.yml
drivers/SmartThings/matter-sensor/profiles/leak-batteryLevel-leakSensitivity.yml
drivers/SmartThings/matter-sensor/profiles/leak-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/matter-motion-batteryLevel-illuminance.yml
drivers/SmartThings/matter-sensor/profiles/matter-motion-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/motion-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/motion-contact-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/motion-illuminance-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/motion-illuminance-temperature-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/pressure-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/rain-batteryLevel-fault-rainSensitivity.yml
drivers/SmartThings/matter-sensor/profiles/rain-batteryLevel-fault.yml
drivers/SmartThings/matter-sensor/profiles/rain-batteryLevel-rainSensitivity.yml
drivers/SmartThings/matter-sensor/profiles/rain-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/sensor-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/temperature-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/temperature-humidity-pressure-batteryLevel.yml
drivers/SmartThings/matter-sensor/src/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_sensor_battery.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_sensor_featuremap.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_smoke_co_alarm.lua

[CHAD-12161](https://smartthings.atlassian.net/browse/CHAD-12161)
Matter drivers currently assume that `BatPercentRemaining` is available if the `BAT` feature is supported, but this attribute is only optionally required if this feature is present. The changes in this PR improve the profile selection logic in matter-sensor by reading the `AttributeList`, checking if `BatPercentRemaining` or `BatChargeLevel` is available, and then profiling the device as needed.
Note that these changes were originally in [PR 1796](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1796) but this PR was split up into 5 separate PRs, one for each affected driver.
Tested with a Contact Sensor device. This device supports `BatPercentRemaining` and …

Add batteryLevel to matter sensor

---

drivers/SmartThings/matter-thermostat/profiles/thermostat-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-cooling-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-cooling-only-nostate-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-cooling-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-cooling-only-nostate-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-heating-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-heating-only-nostate-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-nostate-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-heating-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-heating-only-nostate-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-cooling-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-cooling-only-nostate-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-fan-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-fan-heating-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-fan-heating-only-nostate-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-fan-nostate-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-heating-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-heating-only-nostate-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-nostate-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-nostate-batteryLevel.yml
drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_battery.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_featuremap.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua

[CHAD-12161](https://smartthings.atlassian.net/browse/CHAD-12161)
Matter drivers currently assume that `BatPercentRemaining` is available if the `BAT` feature is supported, but this attribute is only optionally required if this feature is present. The changes in this PR improve the profile selection logic in matter-thermostat by reading the `AttributeList`, checking if `BatPercentRemaining` or `BatChargeLevel` is available, and then profiling the device as needed.
Note that these changes were originally in [PR 1796](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1796) but this PR was split up into 5 separate PRs, one for each affected driver.
Tested with an Eve Thermo, which supports …

Add batteryLevel to matter thermostat

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_light_switch_h2.lua
drivers/SmartThings/matter-switch/src/test/test_electrical_sensor.lua

- Solve the problem that the timer callback function becomes nil.
- Support powerConsumptionReport when energy management is at root endpoint(0).
Fix assertion problem and support SmartThings Energy feature
Check that the powerConsumptionReport is transmitted normally at every set timer interval (15 minutes).

Enable SmartThings Energy to Aqara Light Switch H2

---

drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temp-battery-aqara.yml
drivers/SmartThings/zigbee-humidity-sensor/src/aqara/init.lua
drivers/SmartThings/zigbee-humidity-sensor/src/test/test_aqara_sensor.lua

[Aqara] Humidity_temp_sensor Battery capability change

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_lights.lua

Devices that utilize the child_device_profile_overrides table may contain other endpoints that should not have their profile overridden when the child device is created. This PR ensures that the profile is only overridden for profiles listed in  child_device_profile_overrides. See the discussion from [PR 1872](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1872/files#r1915492561).
Note that `GENERIC_SWITCH_ID` was removed from `device_type_profile_map`. This is because it is never used in this table and also to make it clear that device types in this table may have their child device profile overridden (buttons do not use parent-child).
Unit test update to verify child device profile override works as intended.

Conditionally override child profiles

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_climate_sensor_w100.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_light_switch_h2.lua
drivers/SmartThings/matter-switch/src/test/test_electrical_sensor.lua
drivers/SmartThings/matter-switch/src/test/test_matter_bridge.lua
drivers/SmartThings/matter-switch/src/test/test_matter_button.lua
drivers/SmartThings/matter-switch/src/test/test_matter_multi_button.lua
drivers/SmartThings/matter-switch/src/test/test_matter_multi_button_switch_mcd.lua

This change is an attempt to condense and clarify some of the main functionality of the switch-button device initialization. This includes clarifying logic blocks by moving them into helper functions and integrating some low hanging optimizations.
- Unit tests continue to pass
- A physical 3-button parent-child switch device correctly onboarded 
- A physical 7-button device correctly onboarded

Refactor Matter Switch Initialization

---

drivers/SmartThings/matter-window-covering/profiles/window-covering-tilt-battery.yml
drivers/SmartThings/matter-window-covering/profiles/window-covering-tilt-only-battery.yml
drivers/SmartThings/matter-window-covering/profiles/window-covering-tilt-only.yml
drivers/SmartThings/matter-window-covering/profiles/window-covering-tilt.yml
drivers/SmartThings/matter-window-covering/src/init.lua
drivers/SmartThings/matter-window-covering/src/test/test_matter_window_covering.lua

[CHAD-14539](https://smartthings.atlassian.net/browse/CHAD-14539)
This change adds support for the tilt feature in the `WindowCovering` cluster, to subscribe to the `CurrentPositionTiltPercent100ths` attribute and map this value to the the `windowShadeTiltLevel` capability.
Tested with the VDA Window Covering device. This has recently been updated to support tilt in addition to lift. Also see new unit tests.
[CHAD-14539]: https://smartthings.atlassian.net/browse/CHAD-14539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Matter Window Covering: Support the tilt feature

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat_composed_bridged.lua

The ControlSequenceOfOperations attribute handling defines which operations are disallowed for the thermostat. Per the spec: 
- “This attribute SHALL indicate the overall operating environment of the thermostat, and thus the possible system modes that the thermostat can operate in.”
From a spec perspective, the different values in ControlSequenceOfOperationsEnum only specify what is disallowed. Everything else is optional.
The SystemMode attribute, which is handled with system_mode_handler should be limited by this "disallow" list . Per the spec:
- “This attribute SHALL indicate the current operating mode of the thermostat. Its value SHALL be limited by the ControlSequenceOfOperation attribute.”
We currently update the supported modes with whatever is sent, without regard to the …

Matter Thermostat: Update system_mode_handler

---

drivers/SmartThings/matter-switch/src/init.lua

These require statements are needed before the first reference of these clusters in the file, so they are moved to the top.
Loaded Matter switch driver on hub running api v10 lua libs (corresponding to the FW 53 release) and confirmed that the issue was resolved and the driver works correctly. Driver continues to work as expected on the latest lua libs as well with these changes.

Matter Switch: move embedded cluster includes to top of file

---

drivers/SmartThings/matter-sensor/src/smoke-co-alarm/init.lua
drivers/SmartThings/matter-switch/src/init.lua

Matter Switch:
- CUMULATIVE_REPORTS_NOT_SUPPORTED should be saved. This will not change after driver init.
- ENERGY_MANAGEMENT_ENDPOINT should be saved. This will not be saved, or re-initialized due to gating after the first driver init.
- SWITCH_INITIALIZED is used in init, but is set in init. A driver restart would not save this, and so the field is never being used.
- MOST_RECENT_TEMP should be saved. Low importance, but this doesn't need to be made nil on a driver restart
- TOTAL_IMPORTED_ENERGY must be persisted. This should never be reset on a driver restart.
Smoke Alarm Sub-Driver:
- PROFILE_MATCHED is used in init, but is set in init. A driver restart would not save this, and so the field is never being used.
Hub restart attempted in Matter Switch to ensure that init continues to …

Persist fields across multiple Drivers

---

drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/button.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/contact.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/light.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/motion.lua
drivers/SmartThings/philips-hue/src/utils/hue_bridge_utils.lua

We had reports of an issue where a child device that onboards as offline, and then transitions to online, was in a state where it wouldn't be controllable due to the fact that no attribute events had been emitted for the device (since it onboarded as offline).
This change injects a refresh capability command event in to the device whenever it is marked `online` as a result of a connectivity event on the Hue Bridge's SSE stream.
We also clean up a few other places where we should be using injected refreshes instead of using the handlers directly, though there are a few places where using the handlers directly is still preferred.
Tested on my personal setup by onboarding my setup while a bulb is removed from the socket, then securing it back …

fix(hue): Inject refresh when transitioning online

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding a fingerprint the Cync Keypad Dimmer device
Link to the CSA website https://csa-iot.org/csa_product/cync-keypad-dimmer/

New Device (Matter Switch) Cync Keypad Dimmer

---

drivers/SmartThings/hub/fingerprints.yml
drivers/SmartThings/hub/profiles/cooktop-hub.yml
drivers/SmartThings/hub/profiles/washer-dryer-hub.yml

Draft PR in support of CHAD-14786
- [ X ] New feature
- [ X] I have commented my code in hard-to-understand areas
- [X ] I have verified my changes by testing with a device or have communicated a plan for testing
- [ X] I am adding new behavior, such as adding a sub-driver, and have added and run new unit tests to cover the new behavior
Adding two new profiles and two new fingerprints

New Feature (Hub Driver) Adding profiles and fingerprints  CHAD-14786

---

drivers/SmartThings/zigbee-switch/src/zll-dimmer-bulb/ikea-xy-color-bulb/init.lua
drivers/SmartThings/zigbee-window-treatment/src/invert-lift-percentage/init.lua
drivers/SmartThings/zigbee-window-treatment/src/somfy/init.lua

We were seeing errors when attempting to cancel a timer that no longer existed caused by never setting the timer field to nil after executing the timer.
There were errors happening from trying to cancel a timer that didn't exist
Fixes: https://smartthings.atlassian.net/issues/CHAD-14291

Zigbee Window Shade set timer to nil after executed

---

drivers/SmartThings/matter-switch/fingerprints.yml

A duplicate fingerprint was inadvertently added during a skip beta soak PR. An extra deviceProfileName was also causing driver packaging to fail locally.
Tested that the matter-switch driver can now be properly packaged locally and tested a few devices to ensure that the driver works as expected. This issue didn't seem to cause any ill effects besides causing packaging to fail locally.

Fix duplicate fingerprint in matter switch

---

drivers/SmartThings/matter-sensor/profiles/co-comeas.yml
drivers/SmartThings/matter-sensor/profiles/co.yml

Sensitivity levels do not apply to CO detectors and can be removed from profiles.

Matter Sensor: Remove sensitivity preference from co profiles

---

drivers/SmartThings/matter-switch/src/init.lua

- 2 Buttons, 1 Channel (PID=0x1003)
- 2 Buttons, 2 Channels (PID=0x1004)
- 4 Buttons, 3 Channels (PID=0x1005)
Add additional Aqara Light Switch H2 models
Check normal operation through test for existing model

Add additional Aqara Light Switch H2 models

---

drivers/SmartThings/matter-lock/fingerprints.yml

Adding a new fingerprint for WWST, Matter Lock Eufy Device
These devices has support to use the new Matter door lock Experience as part of a previous PR [https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1851](url)
The Devices are in the DCL as a Matter Device Type 10 (0xa)
eufy Smart Lock C34
VID: 0x1533
PID: 0x0003
eufy Smart Lock E31
VID: 0x1533
PID: 0x0001

New Device (Matter Lock) Eufy C34 + E31 + E30

---

drivers/SmartThings/wemo/src/protocol.lua
drivers/SmartThings/wemo/src/subscription_server.lua

This was done based on crashes that have been reported a lot in the field, but should be handled better.

Fix a few places where nil causes crashes in wemo

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat.lua

As it stands, any optional added SystemMode value will be removed from the SupportedModes table on a driver restart. This PR introduces a persisted table that records all of the mode values added in `system_mode_handler`. Then, on a driver restart, the persisted table (`ALLOWED_OPTIONAL_THERMOSTAT_MODES`) is read in `sequence_of_operation_handler` as the base values to be added to the `supportedThermostatModes` table. 
To note: two similar checks are added, one under the `COOLING_WITH_REHEAT` if-else branch that specifically removes the `emergency heat` and `heat` value if they're found (since this would no longer be allowed) and vice versa with the `HEATING_WITH_REHEAT` branch and the `precooling` and `cool` values. This accounts for the case where the `ControlSequenceOfOperation` …

Use Persisted State cache for Thermostat SystemMode attribute

---

drivers/SmartThings/philips-hue/src/handlers/attribute_emitters.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/light.lua
drivers/SmartThings/philips-hue/src/test/spec/unit/utils_spec.lua
drivers/SmartThings/philips-hue/src/utils/init.lua

There was a slight bug with the previous port of the rounding logic from Matter/Zigbee over to Hue because I was reading two different places in the code and getting them confused in my head.
This change does the following:
1. Only use the 100 step size constraint when computing the min/max values instead of everywhere. This is in line with how this is handled elsewhere on the platform.
2. Use normal rounding everywhere else.
- Busted tests still pass
- ThinkTank will be QA'ing after merge to Alpha

fix(hue): Make rounding logic platform consistent

---

drivers/SmartThings/zigbee-button/fingerprints.yml
drivers/SmartThings/zigbee-button/profiles/two-buttons-no-fw-update.yml
drivers/SmartThings/zigbee-button/src/test/test_vimar_button.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/init.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/supported_values.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/vimar/init.lua

Add support for:
- Vimar Remote Control (xx591, IoT Connected Device Mechanism)

Add zigbee-button for Vimar xx591 (Wall-mounted Remote Control)

---

drivers/SmartThings/zwave-thermostat/src/init.lua
drivers/SmartThings/zwave-thermostat/src/test/test_stelpro_ki_thermostat.lua
drivers/SmartThings/zwave-thermostat/src/test/test_zwave_thermostat.lua

Some z-wave thermostats are choking when told to be set to non-whole numbers. This fixes our base behavior for values that aren't half degrees (which are usually celsius).
Intended to be temporary

BUG2-4037 Z-Wave Thermostat: Whole number workaround

---

drivers/SmartThings/zigbee-switch/fingerprints.yml
drivers/SmartThings/zigbee-switch/src/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_tuya_multi_switch.lua
drivers/SmartThings/zigbee-switch/src/tuya-multi/init.lua

add support for generic zigbee multi-switch

add support for generic zigbee multi-switch

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_air_purifier.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_fan.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_heat_pump.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_room_ac.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_battery.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_featuremap.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua

This has been a TODO for a long time.
This change performs a read of the Thermostat AttributeList in added and checks whether the ThermostatRunningState attribute is included. Whether it is or isn't, the device is profiled accordingly.
Further, the powerSource attribute list read system was refactored a bit to play more nicely with this change, as well as any future changes. Both reads were moved to device_added with a cluster/feature gate, and a gating helper function was added to match_profile to ensure all reads have returned the necessary profiling information before profiling is completed.
Unit tests updated to handle these changes. Some include a positive read and others a negative read to get a variety of test coverage. 
Tested successfully on a physical device needing both a …

Include dynamic handling of the ThermostatOperatingState capability

---

drivers/SmartThings/matter-switch/fingerprints.yml

Adding a Fingerprint for a new Matter Switch Shelly Device
Pid: 0x0001
VendorID: 0x1490
Matter Device Type ID: 0x010A

New Device (Matter Switch) Shelly Plug PID 0001

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_room_ac.lua

Currently, it would be possible for match_profile to choose a profile that does not currently exist for the Room AC device type. New profiles could be added and the new logic in this PR could be removed in the future once the total number of allowed profiles is increased.
New unit test added.

Only support nostate for existing Room AC profiles

---

drivers/SmartThings/matter-thermostat/fingerprints.yml

Conflicts were likely introduced during prior cherry-pick/expedite operations.

fix: Resolves a conflict between the `main` and `beta` branches

---

drivers/SmartThings/matter-lock/profiles/lock-battery.yml
drivers/SmartThings/matter-lock/profiles/lock-batteryLevel.yml
drivers/SmartThings/matter-lock/profiles/lock-unlatch-battery.yml
drivers/SmartThings/matter-lock/profiles/lock-unlatch-batteryLevel.yml
drivers/SmartThings/matter-lock/profiles/lock-unlatch.yml
drivers/SmartThings/matter-lock/profiles/lock-user-pin-schedule-unlatch-battery.yml
drivers/SmartThings/matter-lock/profiles/lock-user-pin-schedule-unlatch-batteryLevel.yml
drivers/SmartThings/matter-lock/profiles/lock-user-pin-schedule-unlatch.yml
drivers/SmartThings/matter-lock/profiles/lock-user-pin-unlatch.yml
drivers/SmartThings/matter-lock/profiles/lock-user-schedule-unlatch.yml
drivers/SmartThings/matter-lock/profiles/lock-user-unlatch.yml
drivers/SmartThings/matter-lock/src/new-matter-lock/init.lua
drivers/SmartThings/matter-lock/src/test/test_new_matter_lock_battery.lua

1. Issue
User is allowed to lock or unlock from the device card if door lock status is unlatched, but user is not allowed to do the same from Plugin.
2. Solution
Add Visible Condition to the profiles that have unlatched status
3. Changes
Add Visible Condition to the profiles that have unlatched status
Add some profiles for unlatch feature

Update new-matter-lock driver

---

drivers/SmartThings/sonos/capabilities/softwareGeneration.yaml
drivers/SmartThings/sonos/profiles/sonos-player.yml
drivers/SmartThings/sonos/src/disco.lua
drivers/SmartThings/sonos/src/fields.lua
drivers/SmartThings/sonos/src/init.lua
drivers/SmartThings/sonos/src/types.lua

Adds support for the `stus` custom capability `softwareGeneration`, which allow for reporting of the `swGen` field on the Sonos Player Info.
This field reports whether or not the speaker has been onboarded to Sonos via the S1 app or the modern Sonos app.
Tested locally on a hubv3.
cc @bflorian would we be able to get the capability published to the lower envs for `stus`? I was only able to do it to Production, and I think it'll break packaging of the driver if they don't exist in the lower environments.

feat(sonos): Add reporting for Sonos App `swGen`

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_climate_sensor_w100.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_light_switch_h2.lua
drivers/SmartThings/matter-switch/src/test/test_matter_button.lua
drivers/SmartThings/matter-switch/src/test/test_matter_multi_button.lua
drivers/SmartThings/matter-switch/src/test/test_matter_multi_button_switch_mcd.lua

When a fingerprint for a button device exists, and matches the profile that the switch driver would select for the device, the `info_changed` event occurs after attempting to update the profile, but since the profile did not change, `configure_buttons` is not called. This leads to the following issues:
- `MultiPressMax` is not read and the driver reports multiple events for a double/multi button press ("Pressed" and "Double pressed" for example)
- `supportedButtonValues` is not emitted, and the button capabilities display all of the possible values for this attribute rather than the ones supported by the device
This change addresses this by always calling `configure_buttons` during button initialization. Then, inside `configure_buttons`, …

Fix button configuration not occuring when a fingerprint exists for a button device

---

drivers/SmartThings/matter-thermostat/profiles/air-purifier-hepa-ac-rock-wind-thermostat-humidity-fan-heating-only-nostate-nobattery-aqs-pm10-pm25-ch2o-meas-pm10-pm25-ch2o-no2-tvoc-level.yml
drivers/SmartThings/matter-thermostat/profiles/room-air-conditioner-fan-heating-cooling.yml
drivers/SmartThings/matter-thermostat/profiles/room-air-conditioner-fan-wind-heating-cooling.yml
drivers/SmartThings/matter-thermostat/profiles/room-air-conditioner-heating-cooling.yml
drivers/SmartThings/matter-thermostat/profiles/room-air-conditioner-humidity-fan-heating-cooling.yml
drivers/SmartThings/matter-thermostat/profiles/room-air-conditioner-humidity-heating-cooling.yml
drivers/SmartThings/matter-thermostat/profiles/room-air-conditioner.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-cooling-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-cooling-only.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-cooling-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-cooling-only.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-heating-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan-heating-only.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-fan.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-heating-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-heating-only.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-cooling-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-cooling-only.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-fan-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-fan-cooling-only.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-fan-heating-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-fan-heating-only.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-fan.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-heating-only-batteryLevel.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity-heating-only.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-humidity.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat.yml

This change will ensure that only the expected and desired allowed values for the ThermsotatOperatingState capability will display on the routines/automations display. Because this is a read-only value from the device card, it will not affect anything on that front.
This has been tested on a VDA Room Air Conditioner to ensure only the config-specified values show up on the routines sub-page for this capabilty. It has also been tested on a physical device using this capability.

Update Allowed Config Values for ThermostatOperatingState capability

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_light_illuminance_motion.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua

Following a device power cycle, hub power cycle, or device going offline and then back online, it sends a subscription report with Hue, Saturation, X, and Y values. The ColorMode needs to be checked before emitting the colorControl capability with the hue and saturation values. The issue is that the ColorMode attribute is not guaranteed to be processed by the driver before the other color attributes. Therefore, the ColorMode handler should send a read request for the proper color attributes after checking the ColorMode.
Changes were previously made by [PR 1772](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1772), but that only addressed hub power cycles. This PR handles every case in which the driver might receive a …

Fix wrong colorControl values emitted after device power cycle

---

drivers/SmartThings/sonos/src/init.lua

We're calling a non-existent method on a log table in the `init.lua` file because we added some extra diagnostics using a shadowing log table in that file.
This fixes the crash by calling the correct method on the correct table.

fix(sonos): Fix crash calling wrong log table

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_heat_pump.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat_composed_bridged.lua

The current SystemMode / ControlSequenceofOperation handling expects for ControlSequenceofOperation to be handled first in all cases, but this is not necessarily the case. This change ensures a particular ordering by early exiting the SystemMode handler if a table that is initialized in the ControlSequenceofOperation handler has not been initialized yet. Then, in the ControlSequenceofOperation handler, it always does a read of SystemMode. At worst, this will cause a dual handling of a single SystemMode value, which will not do anything detrimental. Further, ControlSequenceofOperation should only be run on a subscription.  
Tested on device by SRPOL.
Uni tests updated.

Early return and Re-read In Case of SystemMode Race Conditions

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_heat_pump.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat_composed_bridged.lua

set a field in the case of out of order handlers instead of doing a read request, and run the handler later.

Remove Read Operation for SystemMode

---

drivers/SmartThings/matter-sensor/fingerprints.yml
drivers/SmartThings/matter-sensor/profiles/flow-battery.yml
drivers/SmartThings/matter-sensor/profiles/flow-batteryLevel.yml
drivers/SmartThings/matter-sensor/profiles/flow.yml
drivers/SmartThings/matter-sensor/src/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_flow_sensor.lua

This change adds support for the Flow Sensor device type. This device type was added to matter spec a while ago but has not been implemented into our platform yet.
New unit tests were implemented to verify the cluster -> capability mappings. Tested with VDA Flow Sensor device.

Implement Flow Sensor device type

---

drivers/SmartThings/matter-switch/fingerprints.yml
drivers/SmartThings/matter-switch/profiles/light-color-level-fan.yml
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_matter_light_fan.lua

This change adds driver support for a new profile for a fan+color light device added by a previous PR, brings in handlers for fan attributes and capabilities, and adds new logic to select the new profile and create the component map.
Tested with: Orein fan+light and regression tested with Inovelli dimmer switch, Ikea 7 button remote, and VDA water valve device.

Matter Switch: Support Fan/Light device

---

drivers/SmartThings/matter-sensor/profiles/co-battery.yml
drivers/SmartThings/matter-sensor/profiles/co-comeas-battery.yml
drivers/SmartThings/matter-sensor/profiles/smoke-battery.yml
drivers/SmartThings/matter-sensor/profiles/smoke-co-battery.yml
drivers/SmartThings/matter-sensor/profiles/smoke-co-comeas-battery.yml
drivers/SmartThings/matter-sensor/profiles/smoke-co-temp-humidity-comeas-battery.yml
drivers/SmartThings/matter-sensor/src/smoke-co-alarm/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_smoke_co_alarm.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_smoke_co_alarm_battery.lua

Support the SmokeCOAlarm attribute BatteryAlert through the hardwareFault capability. Support the batteryLevel capability with the PowerSource attribute BatChargeLevel, and include battery capability support with the PowerSource attribute BatPercentRemaining.
Testd on device. New unit tests written and updated for the updated handling.

Update smoke co alarm fault support

---

drivers/SmartThings/zigbee-button/profiles/button-profile.yml
drivers/SmartThings/zigbee-button/profiles/iris-one-button-battery.yml
drivers/SmartThings/zigbee-button/profiles/one-button-battery.yml
drivers/SmartThings/zigbee-button/profiles/one-button.yml

- [o] Refactor
- [o] I have performed a self-review of my code
This change is similar to the previous PR. 
> The icon for the RemoteController category is not a button icon. This commit changes the category for the single button profile among the matter-button profiles from RemoteController to Button.
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1163

change one button categories from RemoteController to Button

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/zigbee-carbon-monoxide-detector/src/init.lua
drivers/SmartThings/zigbee-contact/src/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/init.lua
drivers/SmartThings/zigbee-smoke-detector/src/init.lua
drivers/SmartThings/zigbee-sound-sensor/src/init.lua
drivers/SmartThings/zigbee-switch/src/init.lua
drivers/SmartThings/zigbee-water-leak-sensor/src/init.lua
drivers/SmartThings/zwave-switch/src/init.lua

This will be enabled in the next lua lib release (v14)

Enable native attribute handlers for Zigbee/Z-Wave/Matter drivers

---

drivers/Aqara/aqara-presence-sensor/src/discovery.lua
drivers/Aqara/aqara-presence-sensor/src/fields.lua
drivers/Aqara/aqara-presence-sensor/src/fp2/discovery_helper.lua
drivers/Aqara/aqara-presence-sensor/src/init.lua
drivers/Aqara/aqara-presence-sensor/src/lunchbox/sse/eventsource.lua

apply necessary modifications and improvements for new fp2 firmware
- Token initialization function is added to new firmware. Exception handling is added for when tokens for already registered devices are invalidated.
-  Add the time information log received from fp2 of the important event
- Check whether the device is registered again for cases where there are many devices on the same network.
- Modify the driver not to shut down too early for remove processing when removing the device
- Other inefficient code improvement

[FP2] apply necessary modifications and improvements 

---

drivers/SmartThings/matter-switch/profiles/light-color-level-fan.yml

Update Min Kelvin value to 2700K to reflect the minimum value supported by the Orein fan light device, needed for WWST certification.

Update Fan/Light profile min kelvin value

---

drivers/SmartThings/zigbee-switch/src/init.lua

We reproduced this issue by powering off and then powering on the SmartThings hub. After doing so, the child switch device of the multi-switch does not function correctly.
The root cause appears to be that, in the current `zigbee-switch` driver's `device_init` function, the `find_child` function is not called. As a result, when the hub is powered off and then powered on again, the driver is unable to locate the multi-switch's child device.
Therefore, we added the call to `find_child` in the `device_init` function, and it works as expected. We tested it multiple times, and it consistently functions correctly.

【P250418-01789】fix bugs for zigbee-switch

---

drivers/SmartThings/matter-rvc/src/init.lua
drivers/SmartThings/matter-rvc/src/test/test_matter_rvc.lua

https://smartthings.atlassian.net/browse/IOTE-5115
https://smartthings.atlassian.net/browse/IOTE-5115

Matter RVC: Add mode id to supported_modes field

---

drivers/SmartThings/matter-switch/src/init.lua

Remove the unique handle_refresh call in matter switch to allow the native capability handler to run instead. This will allow a greater number of distinct attributes to be refreshed in a refresh call, as is expected.
Current unit tests continue to pass.

Remove unique refresh handler in matter switch

---

drivers/SmartThings/matter-switch/src/aqara-cube/init.lua
drivers/SmartThings/matter-switch/src/eve-energy/init.lua
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_climate_sensor_w100.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_light_switch_h2.lua
drivers/SmartThings/matter-switch/src/test/test_matter_button.lua
drivers/SmartThings/matter-switch/src/test/test_matter_multi_button.lua
drivers/SmartThings/matter-switch/src/test/test_matter_multi_button_switch_mcd.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch_device_types.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_lights.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_plugs.lua

This change moves the initialization logic for buttons and switches to `do_configure`. This consolidates all of the profile selection logic to be within doConfigure and allows the removal of logic gates from `device_init` that were there to ensure init code only ran one time.
Also added is a new function that runs at init that can rename or delete persisted fields on the device. The original `__component_to_endpoint_map` field can now be utilized by buttons and other devices because `initialize_buttons_and_switches` is ensured to only run one time, meaning that old MCD switch devices will not be affected. Also, the `__switch_intialized` field can now be deleted from devices.
Tested with various matter buttons and lights to ensure no change …

Matter Switch move button and switch initialization to doConfigure

---

drivers/SmartThings/zigbee-sensor/fingerprints.yml
drivers/SmartThings/zigbee-sensor/profiles/generic-motion-illuminance.yml
drivers/SmartThings/zigbee-sensor/src/contact/init.lua
drivers/SmartThings/zigbee-sensor/src/init.lua
drivers/SmartThings/zigbee-sensor/src/motion-illuminance/init.lua
drivers/SmartThings/zigbee-sensor/src/motion/init.lua
drivers/SmartThings/zigbee-sensor/src/test/test_zigbee_sensor.lua
drivers/SmartThings/zigbee-sensor/src/waterleak/init.lua

Refactoring zigbee-sensor driver.

Refactoring driver and support for PIR Motion Sensor

---

drivers/SmartThings/zigbee-contact/fingerprints.yml
drivers/SmartThings/zigbee-contact/profiles/contact-batteryLevel-profile.yml
drivers/SmartThings/zigbee-contact/profiles/contact-batteryLevel.yml
drivers/SmartThings/zigbee-contact/src/aqara/init.lua
drivers/SmartThings/zigbee-contact/src/test/test_aqara_contact_sensor.lua

…ol, changed capability from battery to batteryLevel, and applied battery info in status messages.

[Aqara] Update Aqara Door and Window Sensor T1 driver

---

drivers/Unofficial/tuya-zigbee/config.yml
drivers/Unofficial/tuya-zigbee/fingerprints.yml
drivers/Unofficial/tuya-zigbee/profiles/basic-switch.yml
drivers/Unofficial/tuya-zigbee/profiles/motion-sensor.yml
drivers/Unofficial/tuya-zigbee/profiles/one-button-battery.yml
drivers/Unofficial/tuya-zigbee/profiles/smoke-battery.yml
drivers/Unofficial/tuya-zigbee/profiles/smoke-detector.yml
drivers/Unofficial/tuya-zigbee/profiles/window-treatment-reverse.yml
drivers/Unofficial/tuya-zigbee/src/button/init.lua
drivers/Unofficial/tuya-zigbee/src/button/meian-button/init.lua
drivers/Unofficial/tuya-zigbee/src/curtain/init.lua
drivers/Unofficial/tuya-zigbee/src/init.lua
drivers/Unofficial/tuya-zigbee/src/motion-sensor/init.lua
drivers/Unofficial/tuya-zigbee/src/smoke-detector/init.lua
drivers/Unofficial/tuya-zigbee/src/switch/init.lua
drivers/Unofficial/tuya-zigbee/src/test/test_meian_button.lua
drivers/Unofficial/tuya-zigbee/src/test/test_tuya_button.lua
drivers/Unofficial/tuya-zigbee/src/test/test_tuya_curtain.lua
drivers/Unofficial/tuya-zigbee/src/test/test_tuya_motion_sensor.lua
drivers/Unofficial/tuya-zigbee/src/test/test_tuya_smoke_detector.lua
drivers/Unofficial/tuya-zigbee/src/test/test_tuya_switch.lua
drivers/Unofficial/tuya-zigbee/src/tuya_utils.lua

add support for tuya devices

---

drivers/Unofficial/tuya-zigbee/src/button/init.lua
drivers/Unofficial/tuya-zigbee/src/test/test_tuya_button.lua

Some Tuya button send two times message while button is pressed, causing duplicate event send to cloud. Therefore, we remove the duplicated capability handlers for tuya-button driver.

fix an issue of Tuya button send duplicate event 

---

drivers/SmartThings/matter-sensor/profiles/aqs-modular-humidity.yml
drivers/SmartThings/matter-sensor/profiles/aqs-modular-temp-humidity.yml
drivers/SmartThings/matter-sensor/profiles/aqs-modular-temp.yml
drivers/SmartThings/matter-sensor/profiles/aqs-modular.yml
drivers/SmartThings/matter-sensor/src/air-quality-sensor/init.lua
drivers/SmartThings/matter-sensor/src/test/test_matter_air_quality_sensor_modular.lua

Added additional unit tests for common AQS configuration.
Onboarded AQS VDA device and confirmed functionality of all available attributes and capabilities.
Completed test plan as defined in REQ

Matter Sensor: Add modular profile supports for AQS

---

drivers/SmartThings/matter-thermostat/profiles/air-purifier-modular.yml
drivers/SmartThings/matter-thermostat/profiles/room-air-conditioner-modular.yml
drivers/SmartThings/matter-thermostat/profiles/thermostat-modular.yml
drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_air_purifier_modular.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_room_ac_modular.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_featuremap.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat_modular.lua

Added unit tests for common device configs for Air Purifers, Thermostats, and Room ACs
Onboarded VDA devices for each of these device types
Completed test plan as defined in REQ

Matter Thermostat: add support for modular profiles

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua

For RPC >= 6, the hub converts temperature values from capability commands to Celsius, meaning the driver no longer needs to use separate ranges for Celsius and Fahrenheit in order to determine the unit as Celsius can always be assumed. A range is still used, in order to filter out values received from the device that are likely to be erroneous, but it is now larger and will be able to accommodate the temperature range for more use cases.
A similar change was made to matter-appliance in https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1757
Verified with unit tests and tested with VDA Thermostat.

Matter Thermostat: Use larger temperature range

---

tools/deploy.py

We now need to inject two different API keys in to the Sonos driver. The changes for the driver have already landed, and they have landed in a way that is backwards compatible with the previous deploy script as well: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/8b2d6f571eda5b8a5ce31db5e3094d23af38d2de/drivers/SmartThings/sonos/src/api/init.lua#L6-L23

deploy: Update Sonos secret injection/packaging.

---

drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_electrical_sensor.lua

Remove `emit_event` calls in added. In the case of `powerMeter`, this will be populated with a distinct value after `subscribe` occurs either in `device_init` or `info_changed`. It is the same in the case of `energyMeter`. In both cases, setting an initial value of 0 on added does not add any meaningful data to the capability handling, and so this is a wasted call.
One test removed related to ensuring this was running.

Matter Switch: Remove Energy Setters in added

---

drivers/SmartThings/matter-lock/src/new-matter-lock/init.lua
drivers/SmartThings/matter-lock/src/test/test_new_matter_lock.lua

https://github.ecodesamsung.com/iot/SmartThingsCapabilities/pull/651 changed the weekdays attribute to weekDays. This applies the same change to the new lock subdriver.

matter-lock: Update weekdays -> weekDays

---

drivers/SmartThings/sonos/src/api/sonos_connection.lua
drivers/SmartThings/sonos/src/api/sonos_ssdp_discovery.lua
drivers/SmartThings/sonos/src/api/sonos_websocket_router.lua
drivers/SmartThings/sonos/src/lifecycle_handlers.lua
drivers/SmartThings/sonos/src/sonos_driver.lua
drivers/SmartThings/sonos/src/utils.lua

A few of the code paths around offline speakers were hitting OAuth code paths, which was causing issues on API versions that don't support Sonos OAuth.
Rollback testing with real devices

fix: backwards compat bugs around offline speakers

---

drivers/SmartThings/zigbee-switch/src/aqara/multi-switch/init.lua
drivers/SmartThings/zigbee-switch/src/configurations.lua
drivers/SmartThings/zigbee-switch/src/ezex/init.lua
drivers/SmartThings/zigbee-switch/src/hanssem/init.lua
drivers/SmartThings/zigbee-switch/src/init.lua
drivers/SmartThings/zigbee-switch/src/inovelli-vzm31-sn/init.lua
drivers/SmartThings/zigbee-switch/src/laisiao/init.lua
drivers/SmartThings/zigbee-switch/src/multi-switch-no-master/init.lua
drivers/SmartThings/zigbee-switch/src/robb/init.lua
drivers/SmartThings/zigbee-switch/src/test/test_all_capability_zigbee_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_smart_plug.lua
drivers/SmartThings/zigbee-switch/src/test/test_aqara_smart_plug_t1.lua
drivers/SmartThings/zigbee-switch/src/test/test_aurora_relay.lua
drivers/SmartThings/zigbee-switch/src/test/test_enbrighten_metering_dimmer.lua
drivers/SmartThings/zigbee-switch/src/test/test_jasco_switch.lua
drivers/SmartThings/zigbee-switch/src/test/test_multi_switch_power.lua
drivers/SmartThings/zigbee-switch/src/test/test_robb_smarrt_2-wire_dimmer.lua
drivers/SmartThings/zigbee-switch/src/test/test_robb_smarrt_knob_dimmer.lua
drivers/SmartThings/zigbee-switch/src/test/test_switch_power.lua
drivers/SmartThings/zigbee-switch/src/test/test_zigbee_dimmer_power_energy.lua
drivers/SmartThings/zigbee-switch/src/wallhero/init.lua
drivers/SmartThings/zigbee-switch/src/zigbee-dimmer-power-energy/enbrighten-metering-dimmer/init.lua
drivers/SmartThings/zigbee-switch/src/zigbee-dimming-light/init.lua
drivers/SmartThings/zigbee-switch/src/zigbee-dual-metering-switch/init.lua
drivers/SmartThings/zigbee-switch/src/zigbee-metering-plug-power-consumption-report/init.lua
drivers/SmartThings/zigbee-switch/src/zll-dimmer-bulb/ikea-xy-color-bulb/init.lua

This PR adds code to reconfigure devices supporting the powerMeter capability to reduce the minimum reporting interval.  This changes to 5 seconds instead of 1 second.  On device init, if a device is detected as having not performed this migration (based on a field set on the device datastore), and supporting the capability a 5 minute timer is started if one isn't already running.  At the end of the 5 minutes, all devices the driver knows about are checked and the reconfiguration is attempted.  When we hear a success back from the device, the migration is marked as complete.  This will be attempted at most once per device init, but won't be reattempted periodically without another eligible device being initted.  This means for offline devices, this won't be re-attempted until the driver …

Add reconfiguration for zigbee power meter to reduce reporting

---

drivers/SmartThings/sonos/src/api/event_handlers.lua
drivers/SmartThings/sonos/src/api/sonos_connection.lua
drivers/SmartThings/sonos/src/api/sonos_ssdp_discovery.lua

When we refactored the API Key so that it wasn't global state, we missed making sure it was properly constructed and injected in to the call for querying Favorites on notification that the list of favorites had changed.
Found while updating our internal regression test plan coverage, tested on my speakers.

fix: Missing headers when querying Sonos for Presets

---

drivers/SmartThings/matter-appliance/src/common-utils.lua
drivers/SmartThings/matter-appliance/src/embedded-cluster-utils.lua
drivers/SmartThings/matter-appliance/src/init.lua
drivers/SmartThings/matter-appliance/src/matter-cook-top/init.lua
drivers/SmartThings/matter-appliance/src/matter-dishwasher/init.lua
drivers/SmartThings/matter-appliance/src/matter-extractor-hood/init.lua
drivers/SmartThings/matter-appliance/src/matter-laundry/init.lua
drivers/SmartThings/matter-appliance/src/matter-microwave-oven/init.lua
drivers/SmartThings/matter-appliance/src/matter-oven/init.lua
drivers/SmartThings/matter-appliance/src/matter-refrigerator/init.lua
drivers/SmartThings/matter-appliance/src/test/test_cook_top.lua
drivers/SmartThings/matter-appliance/src/test/test_dishwasher.lua
drivers/SmartThings/matter-appliance/src/test/test_extractor_hood.lua
drivers/SmartThings/matter-appliance/src/test/test_laundry_dryer.lua
drivers/SmartThings/matter-appliance/src/test/test_laundry_washer.lua
drivers/SmartThings/matter-appliance/src/test/test_matter_appliance_rpc_5.lua
drivers/SmartThings/matter-appliance/src/test/test_microwave_oven.lua
drivers/SmartThings/matter-appliance/src/test/test_oven.lua
drivers/SmartThings/matter-appliance/src/test/test_refrigerator.lua

This change moves some common functionality into common-utils.lua, implements do_configure in the subdrivers rather than the main driver, and also contains some minor fixes involving embedded clusters.
Regression tested with VDA for each supported device type.

Matter Appliance minor refactor

---

drivers/SmartThings/sonos/src/sonos_driver.lua

A follow-on to the previous fix, some crash log investigations show that some setups are getting further along than they were before but have run in to a new crash.

fix: Another nil index along a REST response error handling path

---

drivers/SmartThings/zigbee-contact/src/smartsense-multi/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/smartsense/init.lua
drivers/SmartThings/zigbee-motion-sensor/src/test/test_smartsense_motion_sensor.lua
drivers/SmartThings/zigbee-switch/src/test/test_zll_color_temp_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_zll_dimmer.lua
drivers/SmartThings/zigbee-switch/src/test/test_zll_dimmer_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_zll_rgb_bulb.lua
drivers/SmartThings/zigbee-switch/src/test/test_zll_rgbw_bulb.lua
drivers/SmartThings/zigbee-switch/src/zll-polling/init.lua

endpoint ids change from numbers to strings shortly after install. This also fixes some incorrectly-addressed fields for kickstarter sensors.

CHAD-15418 workaround

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat.lua

This is a follow on PR to #2205 to ensure that a capability event is not sent when a FanMode of OFF is reported for a device supporting the thermostatFanMode capability, which doesn't support an 'off' fan mode.

Matter Thermostat: Avoid sending nil capability event

---

drivers/SmartThings/zigbee-humidity-sensor/fingerprints.yml
drivers/SmartThings/zigbee-humidity-sensor/src/test/test_humidity_temperature_battery.lua

add battery capability for generic temp/humidity sensor

Add a generic fingerprint for Zigbee humidity sensors that include battery capability

---

drivers/Aqara/aqara-presence-sensor/src/discovery.lua
drivers/Aqara/aqara-presence-sensor/src/fields.lua
drivers/Aqara/aqara-presence-sensor/src/init.lua
drivers/Aqara/aqara-presence-sensor/src/lunchbox/sse/eventsource.lua

- Added error handling for potential errors that may occur when adding a device.
- Modified the offline detection logic to align with Aqara's logic.
- Reset the device exclusion list on every discovery
Verified operation with 3 FP2 devices connected at the same time to:
- SmartThings Hub V2
- SmartThings Hub V3
- SmartThings Station
- SmartMonitor M5's built-in hub

Aqara-FP2: Add error handling and modify offline logic

---

drivers/SmartThings/matter-lock/src/new-matter-lock/init.lua

DoorLockAlarm event is manadatory event in Matter spec and LockJammed is mandatory enum value.
So this patch add unableToLockTheDoor value that is mapped to LockJammed of Matter spec to supportedAlarmValues.
supportedAlarmValues is used in Routine. If supportedAlarmValues is nil, user can select all of lockAlarm Enum value. Even if device does not support some enum values, user can select those values. So we decide to add default value(unableToLockTheDoor) to supportedAlarmVlaues.

Add default enum value to supportedAlarmvalues

---

drivers/SmartThings/matter-switch/fingerprints.yml

WWSTCERT-6426 LG Smart Wall Switch (2 Button)
WWSTCERT-6429 LG Smart Wall Switch (1 Button)

WWSTCERT-6423 LG Smart Wall Switch (3 Button)

---

drivers/SmartThings/zigbee-button/fingerprints.yml
drivers/SmartThings/zigbee-button/profiles/eight-buttons-temp-battery.yml
drivers/SmartThings/zigbee-button/src/test/test_zunzunbee_8_button.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/init.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/supported_values.lua
drivers/SmartThings/zigbee-button/src/zigbee-multi-button/zunzunbee/init.lua

- [ X] I have reviewed the README.md file
- [X ] I plan on entering a WWST Certification Request or have entered a request through the WWST Certification console at developer.smartthings.com
- [ X] New feature
- [ X] I have commented my code in hard-to-understand areas
- [ X] I have verified my changes by testing with a device or have communicated a plan for testing
- [X ] I am adding new behavior, such as adding a sub-driver, and have added and run new unit tests to cover the new behavior
New zigbee multi button sub driver added for support of zunzunbee Slate Switch (model: SSWZ8T)
1. Zigbee 3.0 independent lab tests
2. Works With …

Pull request for zunzunbee Slate Switch zigbee button edge driver

---

drivers/SmartThings/matter-window-covering/src/init.lua
drivers/SmartThings/matter-window-covering/src/matter-window-covering-position-updates-while-moving/init.lua
drivers/SmartThings/matter-window-covering/src/test/test_matter_window_covering.lua

This change inverts the interpretation of open/closed when the Reverse preference is set. This means that when the preference is set, a `windowShadeLevel` of 100% is interpreted as Closed and 0% as Open. This approach replaces a previous change that inverted the percentage values received from the device, which was more complex and has some edge cases that caused occasional issues.
Tested with VDA window covering, Zemismart MotionBlinds, and updated unit tests.

Fix reverse preference in matter window covering

---

drivers/SmartThings/matter-switch/profiles/light-level-power-energy-powerConsumption.yml
drivers/SmartThings/matter-switch/profiles/light-power-energy-powerConsumption.yml
drivers/SmartThings/matter-switch/src/init.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_climate_sensor_w100.lua
drivers/SmartThings/matter-switch/src/test/test_aqara_light_switch_h2.lua
drivers/SmartThings/matter-switch/src/test/test_electrical_sensor.lua
drivers/SmartThings/matter-switch/src/test/test_matter_button.lua
drivers/SmartThings/matter-switch/src/test/test_matter_light_fan.lua
drivers/SmartThings/matter-switch/src/test/test_matter_multi_button.lua
drivers/SmartThings/matter-switch/src/test/test_matter_multi_button_switch_mcd.lua
drivers/SmartThings/matter-switch/src/test/test_matter_switch_device_types.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_lights.lua
drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_plugs.lua

Reverts https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/2199 and adds a check on `init` to set the previously used `ENERGY_MANAGEMENT_ENDPOINT` field on init for energy devices with child devices.

Revert energy profiling changes

---

tools/deploy.py

This is important because if we dont do this, the bulk upload will
unassign any driver that was not a part of the changed drivers for this
deploy.

Fail deploy if we fail to get the existing drivers for a channel

---

drivers/SmartThings/matter-thermostat/src/init.lua
drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat_modular.lua

ce5622b47b6d3db40a2cd1a401f30b5e0c3ee480 updated `get_device_type` to include the Thermostat device type ID, but it wasn't accounted for in `supports_modular_profiles`.
Tested the following cases on device: (1) onboard Thermostat. Device joins modular profile as expected. (2) onboard to production driver, device joins static profile. After updating the driver to include the changes from this PR, device remains on static profile with no unexpected behavior.
Adding the `Thermostat` device type to the mock device within `test_matter_thermostat_modular.lua` verifies that modular profiles are used when the thermostat device type is present and not used otherwise. Before, `get_device_type` returned false for this mock device so it would still use modular profiles.

Update supports_modular_profiles to account for Thermostats

---

drivers/SmartThings/matter-hrap/config.yml
drivers/SmartThings/matter-hrap/fingerprints.yml
drivers/SmartThings/matter-hrap/profiles/network-infrastructure-manager.yml
drivers/SmartThings/matter-hrap/profiles/thread-border-router.yml
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/client/commands/DatasetResponse.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/client/commands/init.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/init.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/server/attributes/ActiveDatasetTimestamp.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/server/attributes/BorderRouterName.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/server/attributes/InterfaceEnabled.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/server/attributes/ThreadVersion.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/server/attributes/init.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/server/commands/GetActiveDatasetRequest.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/server/commands/init.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/types/Feature.lua
drivers/SmartThings/matter-hrap/src/ThreadBorderRouterManagement/types/init.lua
drivers/SmartThings/matter-hrap/src/WiFiNetworkManagement/init.lua
drivers/SmartThings/matter-hrap/src/WiFiNetworkManagement/server/attributes/Ssid.lua
drivers/SmartThings/matter-hrap/src/WiFiNetworkManagement/server/attributes/init.lua
drivers/SmartThings/matter-hrap/src/embedded-cluster-utils.lua
drivers/SmartThings/matter-hrap/src/init.lua
drivers/SmartThings/matter-hrap/src/test/test_thread_border_router_network.lua

Implements handling for the TBR and NIM Device Types. Includes a basic thread operational dataset parser.
Tested using CHIP Example App, VDA, and is verified with unit tests.

Add Matter HRAP Support

---

drivers/SmartThings/matter-switch/src/init.lua

Quick fix to move the registering of powermeter native handler for matter-switch to not rely on the endpoint ID of the device.

CHAD-15951: fix moved matter powerMeter NH registration to not rely on endpoint ID

---

drivers/SmartThings/matter-sensor/profiles/freeze.yml
drivers/SmartThings/matter-sensor/profiles/leak.yml
drivers/SmartThings/matter-sensor/profiles/rain.yml

From a community post: https://community.smartthings.com/t/matter-smart-home-connectivity-standard-formerly-project-chip/180934/1475
and a comment mentioned here: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/issues/2376#issuecomment-3257478374
it has been identified that we are missing a couple of base profiles for the following Matter 1.3 device types.

matter sensor: Add base rain, leak, and freeze profiles

---

drivers/SmartThings/sonos/src/api/event_handlers.lua
drivers/SmartThings/sonos/src/api/sonos_connection.lua
drivers/SmartThings/sonos/src/api/sonos_ssdp_discovery.lua
drivers/SmartThings/sonos/src/fields.lua
drivers/SmartThings/sonos/src/init.lua
drivers/SmartThings/sonos/src/lifecycle_handlers.lua
drivers/SmartThings/sonos/src/sonos_driver.lua
drivers/SmartThings/sonos/src/sonos_state.lua
drivers/SmartThings/sonos/src/types.lua
drivers/SmartThings/sonos/src/utils.lua

We have historically ignored non-primary devices in bonded sets during discovery/onboarding, going back to the pre-Edge days. 
Bonded sets are things like stereo pairs or home theater setups.
These devices cannot be controlled via the WSS LAN API at all, and they aren't treated as being part of a Group in the Sonos group model; the intent is for API consumers to treat the entire bonded set as a single "player". Only one of the devices in the set exposes an API endpoint, which differs from a Group where all the players expose an endpoint. While groups service most commands via calling the API endpoint on the Group Coordinator, certain commands like volume can be sent to non-coordinator players. This is not the case with bonded sets; the entire set always acts atomically, and only the …

fix(sonos): Improved handling of bonded set membership changes.

---

drivers/SmartThings/sonos/src/api/cmd_handlers.lua
drivers/SmartThings/sonos/src/api/sonos_connection.lua
drivers/SmartThings/sonos/src/lifecycle_handlers.lua
drivers/SmartThings/sonos/src/sonos_driver.lua
drivers/SmartThings/sonos/src/token_refresher.lua

This change fixes a potential issue where the driver's oauth token is expired and a capability command comes in before the hourly auth check (via SSDP event handler) happens. The command would not be handled because the driver doesn't have a valid token and there is no retry mechanism.
The crux of this change is adding a persistent token refresher task that tracks when the token expires and refreshes the token when it will expire in under a minute (Same value Viper uses when determining to refresh a token). 
The token refresher task has 3 actions that it can take based off the current state of the driver:
- If oauth is not connected, then the refresher will wait until it is connected. We cannot request tokens if this is …

sonos: Add persistent token refresher task

---

drivers/SmartThings/sonos/src/api/sonos_connection.lua
drivers/SmartThings/sonos/src/lifecycle_handlers.lua
drivers/SmartThings/sonos/src/sonos_driver.lua

This was a miss by me that I thought I had tested in the token refresher PR that was found when during regression testing. When we request a token, if the call returns a 404, then we will make another api call which will trigger a notification to the user guiding them to link their sonos account.
This change adds a function `SonosDriver:alert_unauthorized()` that will go through the token request flow and trigger a notification to the user. This is called when the websocket closes due to being unauthorized, when we determine we are unauthorized in the websocket reconnect task, and in the device init lifecycle handler task when we determine we are unauthorized.
This is done outside of the token refresher task because …

sonos: Fix oauth account linking notifications

---

drivers/SmartThings/matter-lock/fingerprints.yml

We were notified that Level Lock did support the Matter attribute that we use as a mapping to the batteryLevel capability, and that this was a small miss in their initial WWST request. Therefore, they have requested we update the fingerprint to allow this support. Further, it has been communicated that these should be safe to change from a WWST perspective since "these should have been "certified by similarity" based on one of the locks that used the correct profile."

Update Level Lock fingerprint to use batteryLevel

---

drivers/SmartThings/philips-hue/src/disco/init.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/button.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/contact.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/init.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/light.lua
drivers/SmartThings/philips-hue/src/handlers/lifecycle_handlers/motion.lua
drivers/SmartThings/philips-hue/src/hue_driver_template.lua
drivers/SmartThings/philips-hue/src/utils/grouped_utils.lua
drivers/SmartThings/philips-hue/src/utils/hue_bridge_utils.lua
drivers/SmartThings/philips-hue/src/utils/hue_multi_service_device_utils/sensor.lua
drivers/SmartThings/philips-hue/src/utils/init.lua

This change is to help facilitate the migration of an old hue bridge to the pro hue bridge. Currently, the driver holds a mapping of hue resource IDs to smartthings devices records. This becomes a problem when adding the new pro to smartthings because the children of the pro will have the same resource ids as they did when on the old bridge. Child creation is gated by if we already have a record of that hue resource ID. The driver also makes assumptions throughout that the hue resource ID is unique.
By splitting up the mapping by hue bridge, we shouldn't run into any issues with collusions and should be able to re-create the devices on the new pro bridge.
By hue setup is currently offline so I haven't had a chance to …

philips-hue: Split mapping of hue resource IDs by bridge

---

drivers/SmartThings/zwave-switch/profiles/leviton-zw6hd.yml

We are seeing issues when the zwave range is report is 99, the ST app claims it is out of range.   All other drivers go to 100 range, so I believe this is the source of the issue, so changing our driver to match
- X Bug fix
- X I have performed a self-review of my code
- X I have commented my code in hard-to-understand areas
- X I have verified my changes by testing with a device or have communicated a plan for testing
Change the max range of z-wave dimmer from 99 to 100

Update leviton-zw6hd.yml to expand range 99->100

---

drivers/SmartThings/matter-sensor/src/air-quality-sensor/init.lua
drivers/SmartThings/matter-thermostat/src/init.lua

In the case a hub on 58 FW fails over to a hub on 57 FW, this table being removed will lead to incorrect handling.

Keep SUPPORTED_COMPONENT_CAPABILITIES table on driver
